// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Represents a transaction that a parent transaction (e.g., a Payment) has been applied to.  This element is typically found in response objects like ReceivePaymentRet or BillPaymentCheckRet.
    /// </summary>
    public partial class AppliedToTxn : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppliedToTxn" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="objectType">objectType</param>
        /// <param name="type">type</param>
        /// <param name="transactionDate">transactionDate</param>
        /// <param name="refNumber">The primary reference number for the transaction this one is applied to.</param>
        /// <param name="balanceRemaining">The balance remaining on the applied-to transaction.</param>
        /// <param name="paymentAmount">The amount of the parent transaction applied to this one.</param>
        /// <param name="discountAmount">The discount amount given on the applied-to transaction.</param>
        /// <param name="discountAccount">Reference to the discount account used.</param>
        /// <param name="discountClass">Reference to the class used for the discount.</param>
        /// <param name="linkedTransactions">linkedTransactions</param>
        /// <param name="appliedCredits">appliedCredits</param>
        [JsonConstructor]
        public AppliedToTxn(string id, Option<string?> objectType = default, Option<string?> type = default, Option<DateOnly?> transactionDate = default, Option<string?> refNumber = default, Option<double?> balanceRemaining = default, Option<double?> paymentAmount = default, Option<double?> discountAmount = default, Option<QbdRef?> discountAccount = default, Option<QbdRef?> discountClass = default, Option<List<LinkedTransaction>?> linkedTransactions = default, Option<List<SetCredit>?> appliedCredits = default)
        {
            Id = id;
            ObjectTypeOption = objectType;
            TypeOption = type;
            TransactionDateOption = transactionDate;
            RefNumberOption = refNumber;
            BalanceRemainingOption = balanceRemaining;
            PaymentAmountOption = paymentAmount;
            DiscountAmountOption = discountAmount;
            DiscountAccountOption = discountAccount;
            DiscountClassOption = discountClass;
            LinkedTransactionsOption = linkedTransactions;
            AppliedCreditsOption = appliedCredits;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Used to track the state of ObjectType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ObjectTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ObjectType
        /// </summary>
        [JsonPropertyName("objectType")]
        public string? ObjectType { get { return this.ObjectTypeOption.Value; } set { this.ObjectTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string? Type { get { return this.TypeOption.Value; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [JsonPropertyName("transactionDate")]
        public DateOnly? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// The primary reference number for the transaction this one is applied to.
        /// </summary>
        /// <value>The primary reference number for the transaction this one is applied to.</value>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of BalanceRemaining
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> BalanceRemainingOption { get; private set; }

        /// <summary>
        /// The balance remaining on the applied-to transaction.
        /// </summary>
        /// <value>The balance remaining on the applied-to transaction.</value>
        [JsonPropertyName("balanceRemaining")]
        public double? BalanceRemaining { get { return this.BalanceRemainingOption.Value; } set { this.BalanceRemainingOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PaymentAmountOption { get; private set; }

        /// <summary>
        /// The amount of the parent transaction applied to this one.
        /// </summary>
        /// <value>The amount of the parent transaction applied to this one.</value>
        [JsonPropertyName("paymentAmount")]
        public double? PaymentAmount { get { return this.PaymentAmountOption.Value; } set { this.PaymentAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiscountAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> DiscountAmountOption { get; private set; }

        /// <summary>
        /// The discount amount given on the applied-to transaction.
        /// </summary>
        /// <value>The discount amount given on the applied-to transaction.</value>
        [JsonPropertyName("discountAmount")]
        public double? DiscountAmount { get { return this.DiscountAmountOption.Value; } set { this.DiscountAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiscountAccount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QbdRef?> DiscountAccountOption { get; private set; }

        /// <summary>
        /// Reference to the discount account used.
        /// </summary>
        /// <value>Reference to the discount account used.</value>
        [JsonPropertyName("discountAccount")]
        public QbdRef? DiscountAccount { get { return this.DiscountAccountOption.Value; } set { this.DiscountAccountOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiscountClass
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QbdRef?> DiscountClassOption { get; private set; }

        /// <summary>
        /// Reference to the class used for the discount.
        /// </summary>
        /// <value>Reference to the class used for the discount.</value>
        [JsonPropertyName("discountClass")]
        public QbdRef? DiscountClass { get { return this.DiscountClassOption.Value; } set { this.DiscountClassOption = new(value); } }

        /// <summary>
        /// Used to track the state of LinkedTransactions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LinkedTransaction>?> LinkedTransactionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets LinkedTransactions
        /// </summary>
        [JsonPropertyName("linkedTransactions")]
        public List<LinkedTransaction>? LinkedTransactions { get { return this.LinkedTransactionsOption.Value; } set { this.LinkedTransactionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AppliedCredits
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SetCredit>?> AppliedCreditsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AppliedCredits
        /// </summary>
        [JsonPropertyName("appliedCredits")]
        public List<SetCredit>? AppliedCredits { get { return this.AppliedCreditsOption.Value; } set { this.AppliedCreditsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppliedToTxn {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ObjectType: ").Append(ObjectType).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  BalanceRemaining: ").Append(BalanceRemaining).Append("\n");
            sb.Append("  PaymentAmount: ").Append(PaymentAmount).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  DiscountAccount: ").Append(DiscountAccount).Append("\n");
            sb.Append("  DiscountClass: ").Append(DiscountClass).Append("\n");
            sb.Append("  LinkedTransactions: ").Append(LinkedTransactions).Append("\n");
            sb.Append("  AppliedCredits: ").Append(AppliedCredits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AppliedToTxn" />
    /// </summary>
    public class AppliedToTxnJsonConverter : JsonConverter<AppliedToTxn>
    {
        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="AppliedToTxn" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AppliedToTxn Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> objectType = default;
            Option<string?> type = default;
            Option<DateOnly?> transactionDate = default;
            Option<string?> refNumber = default;
            Option<double?> balanceRemaining = default;
            Option<double?> paymentAmount = default;
            Option<double?> discountAmount = default;
            Option<QbdRef?> discountAccount = default;
            Option<QbdRef?> discountClass = default;
            Option<List<LinkedTransaction>?> linkedTransactions = default;
            Option<List<SetCredit>?> appliedCredits = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "objectType":
                            objectType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "balanceRemaining":
                            balanceRemaining = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "paymentAmount":
                            paymentAmount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "discountAmount":
                            discountAmount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "discountAccount":
                            discountAccount = new Option<QbdRef?>(JsonSerializer.Deserialize<QbdRef>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "discountClass":
                            discountClass = new Option<QbdRef?>(JsonSerializer.Deserialize<QbdRef>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "linkedTransactions":
                            linkedTransactions = new Option<List<LinkedTransaction>?>(JsonSerializer.Deserialize<List<LinkedTransaction>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "appliedCredits":
                            appliedCredits = new Option<List<SetCredit>?>(JsonSerializer.Deserialize<List<SetCredit>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class AppliedToTxn.", nameof(id));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class AppliedToTxn.");

            if (objectType.IsSet && objectType.Value == null)
                throw new ArgumentNullException(nameof(objectType), "Property is not nullable for class AppliedToTxn.");

            if (linkedTransactions.IsSet && linkedTransactions.Value == null)
                throw new ArgumentNullException(nameof(linkedTransactions), "Property is not nullable for class AppliedToTxn.");

            if (appliedCredits.IsSet && appliedCredits.Value == null)
                throw new ArgumentNullException(nameof(appliedCredits), "Property is not nullable for class AppliedToTxn.");

            return new AppliedToTxn(id.Value!, objectType, type, transactionDate, refNumber, balanceRemaining, paymentAmount, discountAmount, discountAccount, discountClass, linkedTransactions, appliedCredits);
        }

        /// <summary>
        /// Serializes a <see cref="AppliedToTxn" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="appliedToTxn"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AppliedToTxn appliedToTxn, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, appliedToTxn, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AppliedToTxn" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="appliedToTxn"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AppliedToTxn appliedToTxn, JsonSerializerOptions jsonSerializerOptions)
        {
            if (appliedToTxn.Id == null)
                throw new ArgumentNullException(nameof(appliedToTxn.Id), "Property is required for class AppliedToTxn.");

            if (appliedToTxn.ObjectTypeOption.IsSet && appliedToTxn.ObjectType == null)
                throw new ArgumentNullException(nameof(appliedToTxn.ObjectType), "Property is required for class AppliedToTxn.");

            if (appliedToTxn.LinkedTransactionsOption.IsSet && appliedToTxn.LinkedTransactions == null)
                throw new ArgumentNullException(nameof(appliedToTxn.LinkedTransactions), "Property is required for class AppliedToTxn.");

            if (appliedToTxn.AppliedCreditsOption.IsSet && appliedToTxn.AppliedCredits == null)
                throw new ArgumentNullException(nameof(appliedToTxn.AppliedCredits), "Property is required for class AppliedToTxn.");

            writer.WriteString("id", appliedToTxn.Id);

            if (appliedToTxn.ObjectTypeOption.IsSet)
                writer.WriteString("objectType", appliedToTxn.ObjectType);

            if (appliedToTxn.TypeOption.IsSet)
                if (appliedToTxn.TypeOption.Value != null)
                    writer.WriteString("type", appliedToTxn.Type);
                else
                    writer.WriteNull("type");

            if (appliedToTxn.TransactionDateOption.IsSet)
                if (appliedToTxn.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", appliedToTxn.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (appliedToTxn.RefNumberOption.IsSet)
                if (appliedToTxn.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", appliedToTxn.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (appliedToTxn.BalanceRemainingOption.IsSet)
                if (appliedToTxn.BalanceRemainingOption.Value != null)
                    writer.WriteNumber("balanceRemaining", appliedToTxn.BalanceRemainingOption.Value!.Value);
                else
                    writer.WriteNull("balanceRemaining");

            if (appliedToTxn.PaymentAmountOption.IsSet)
                if (appliedToTxn.PaymentAmountOption.Value != null)
                    writer.WriteNumber("paymentAmount", appliedToTxn.PaymentAmountOption.Value!.Value);
                else
                    writer.WriteNull("paymentAmount");

            if (appliedToTxn.DiscountAmountOption.IsSet)
                if (appliedToTxn.DiscountAmountOption.Value != null)
                    writer.WriteNumber("discountAmount", appliedToTxn.DiscountAmountOption.Value!.Value);
                else
                    writer.WriteNull("discountAmount");

            if (appliedToTxn.DiscountAccountOption.IsSet)
                if (appliedToTxn.DiscountAccountOption.Value != null)
                {
                    writer.WritePropertyName("discountAccount");
                    JsonSerializer.Serialize(writer, appliedToTxn.DiscountAccount, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("discountAccount");
            if (appliedToTxn.DiscountClassOption.IsSet)
                if (appliedToTxn.DiscountClassOption.Value != null)
                {
                    writer.WritePropertyName("discountClass");
                    JsonSerializer.Serialize(writer, appliedToTxn.DiscountClass, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("discountClass");
            if (appliedToTxn.LinkedTransactionsOption.IsSet)
            {
                writer.WritePropertyName("linkedTransactions");
                JsonSerializer.Serialize(writer, appliedToTxn.LinkedTransactions, jsonSerializerOptions);
            }
            if (appliedToTxn.AppliedCreditsOption.IsSet)
            {
                writer.WritePropertyName("appliedCredits");
                JsonSerializer.Serialize(writer, appliedToTxn.AppliedCredits, jsonSerializerOptions);
            }
        }
    }
}
