// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Public developer-facing connection response returned by the v1 connections endpoints.
    /// </summary>
    public partial class ConnectionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionResponse" /> class.
        /// </summary>
        /// <param name="id">Developer-facing connection ID in prefixed form, e.g. &#x60;conn_01965a3f2e7b7000b4c1d2e3f4a5b6c7&#x60;.</param>
        /// <param name="createdAt">When the connection record was created.</param>
        /// <param name="objectType">Constant resource discriminator.</param>
        /// <param name="externalId">Your own external identifier for the connection, if supplied.</param>
        /// <param name="description">Human-friendly label for the connection.</param>
        /// <param name="mode">Connection mode, either &#x60;development&#x60; or &#x60;production&#x60;.</param>
        /// <param name="lifecycleState">Lifecycle state, e.g. &#x60;active&#x60; or &#x60;archived&#x60;.</param>
        /// <param name="restrictionReason">Restriction reason when access is limited by policy.</param>
        /// <param name="isActive">True when the tenant may currently access the connection.</param>
        /// <param name="isArchived">True when the connection has been archived.</param>
        /// <param name="isOperational">True when the connection is usable for sync and API operations.</param>
        /// <param name="requiresPayment">True when the connection requires billing completion before it can operate.</param>
        /// <param name="billingStatus">Billing status for production connections.</param>
        /// <param name="billingUrl">Hosted billing URL when payment is required.</param>
        /// <param name="billingCheckoutEndpoint">Relative API endpoint the client can call to start checkout.</param>
        /// <param name="companyName">Company name reported by QuickBooks.</param>
        /// <param name="companyFile">Company file path reported by QuickBooks.</param>
        /// <param name="edition">QuickBooks edition, e.g. Pro or Enterprise.</param>
        /// <param name="lastConnectedAt">Last observed QuickBooks connection timestamp.</param>
        /// <param name="updatedAt">When the connection record was last updated.</param>
        [JsonConstructor]
        public ConnectionResponse(string id, DateTimeOffset createdAt, Option<string?> objectType = default, Option<string?> externalId = default, Option<string?> description = default, Option<string?> mode = default, Option<string?> lifecycleState = default, Option<string?> restrictionReason = default, Option<bool?> isActive = default, Option<bool?> isArchived = default, Option<bool?> isOperational = default, Option<bool?> requiresPayment = default, Option<string?> billingStatus = default, Option<string?> billingUrl = default, Option<string?> billingCheckoutEndpoint = default, Option<string?> companyName = default, Option<string?> companyFile = default, Option<string?> edition = default, Option<DateTimeOffset?> lastConnectedAt = default, Option<DateTimeOffset?> updatedAt = default)
        {
            Id = id;
            CreatedAt = createdAt;
            ObjectTypeOption = objectType;
            ExternalIdOption = externalId;
            DescriptionOption = description;
            ModeOption = mode;
            LifecycleStateOption = lifecycleState;
            RestrictionReasonOption = restrictionReason;
            IsActiveOption = isActive;
            IsArchivedOption = isArchived;
            IsOperationalOption = isOperational;
            RequiresPaymentOption = requiresPayment;
            BillingStatusOption = billingStatus;
            BillingUrlOption = billingUrl;
            BillingCheckoutEndpointOption = billingCheckoutEndpoint;
            CompanyNameOption = companyName;
            CompanyFileOption = companyFile;
            EditionOption = edition;
            LastConnectedAtOption = lastConnectedAt;
            UpdatedAtOption = updatedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Developer-facing connection ID in prefixed form, e.g. &#x60;conn_01965a3f2e7b7000b4c1d2e3f4a5b6c7&#x60;.
        /// </summary>
        /// <value>Developer-facing connection ID in prefixed form, e.g. &#x60;conn_01965a3f2e7b7000b4c1d2e3f4a5b6c7&#x60;.</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// When the connection record was created.
        /// </summary>
        /// <value>When the connection record was created.</value>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of ObjectType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ObjectTypeOption { get; private set; }

        /// <summary>
        /// Constant resource discriminator.
        /// </summary>
        /// <value>Constant resource discriminator.</value>
        [JsonPropertyName("objectType")]
        public string? ObjectType { get { return this.ObjectTypeOption.Value; } set { this.ObjectTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Your own external identifier for the connection, if supplied.
        /// </summary>
        /// <value>Your own external identifier for the connection, if supplied.</value>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Human-friendly label for the connection.
        /// </summary>
        /// <value>Human-friendly label for the connection.</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Mode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ModeOption { get; private set; }

        /// <summary>
        /// Connection mode, either &#x60;development&#x60; or &#x60;production&#x60;.
        /// </summary>
        /// <value>Connection mode, either &#x60;development&#x60; or &#x60;production&#x60;.</value>
        [JsonPropertyName("mode")]
        public string? Mode { get { return this.ModeOption.Value; } set { this.ModeOption = new(value); } }

        /// <summary>
        /// Used to track the state of LifecycleState
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LifecycleStateOption { get; private set; }

        /// <summary>
        /// Lifecycle state, e.g. &#x60;active&#x60; or &#x60;archived&#x60;.
        /// </summary>
        /// <value>Lifecycle state, e.g. &#x60;active&#x60; or &#x60;archived&#x60;.</value>
        [JsonPropertyName("lifecycleState")]
        public string? LifecycleState { get { return this.LifecycleStateOption.Value; } set { this.LifecycleStateOption = new(value); } }

        /// <summary>
        /// Used to track the state of RestrictionReason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RestrictionReasonOption { get; private set; }

        /// <summary>
        /// Restriction reason when access is limited by policy.
        /// </summary>
        /// <value>Restriction reason when access is limited by policy.</value>
        [JsonPropertyName("restrictionReason")]
        public string? RestrictionReason { get { return this.RestrictionReasonOption.Value; } set { this.RestrictionReasonOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// True when the tenant may currently access the connection.
        /// </summary>
        /// <value>True when the tenant may currently access the connection.</value>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsArchived
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsArchivedOption { get; private set; }

        /// <summary>
        /// True when the connection has been archived.
        /// </summary>
        /// <value>True when the connection has been archived.</value>
        [JsonPropertyName("isArchived")]
        public bool? IsArchived { get { return this.IsArchivedOption.Value; } set { this.IsArchivedOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsOperational
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsOperationalOption { get; private set; }

        /// <summary>
        /// True when the connection is usable for sync and API operations.
        /// </summary>
        /// <value>True when the connection is usable for sync and API operations.</value>
        [JsonPropertyName("isOperational")]
        public bool? IsOperational { get { return this.IsOperationalOption.Value; } set { this.IsOperationalOption = new(value); } }

        /// <summary>
        /// Used to track the state of RequiresPayment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> RequiresPaymentOption { get; private set; }

        /// <summary>
        /// True when the connection requires billing completion before it can operate.
        /// </summary>
        /// <value>True when the connection requires billing completion before it can operate.</value>
        [JsonPropertyName("requiresPayment")]
        public bool? RequiresPayment { get { return this.RequiresPaymentOption.Value; } set { this.RequiresPaymentOption = new(value); } }

        /// <summary>
        /// Used to track the state of BillingStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BillingStatusOption { get; private set; }

        /// <summary>
        /// Billing status for production connections.
        /// </summary>
        /// <value>Billing status for production connections.</value>
        [JsonPropertyName("billingStatus")]
        public string? BillingStatus { get { return this.BillingStatusOption.Value; } set { this.BillingStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of BillingUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BillingUrlOption { get; private set; }

        /// <summary>
        /// Hosted billing URL when payment is required.
        /// </summary>
        /// <value>Hosted billing URL when payment is required.</value>
        [JsonPropertyName("billingUrl")]
        public string? BillingUrl { get { return this.BillingUrlOption.Value; } set { this.BillingUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of BillingCheckoutEndpoint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BillingCheckoutEndpointOption { get; private set; }

        /// <summary>
        /// Relative API endpoint the client can call to start checkout.
        /// </summary>
        /// <value>Relative API endpoint the client can call to start checkout.</value>
        [JsonPropertyName("billingCheckoutEndpoint")]
        public string? BillingCheckoutEndpoint { get { return this.BillingCheckoutEndpointOption.Value; } set { this.BillingCheckoutEndpointOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompanyName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyNameOption { get; private set; }

        /// <summary>
        /// Company name reported by QuickBooks.
        /// </summary>
        /// <value>Company name reported by QuickBooks.</value>
        [JsonPropertyName("companyName")]
        public string? CompanyName { get { return this.CompanyNameOption.Value; } set { this.CompanyNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompanyFile
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyFileOption { get; private set; }

        /// <summary>
        /// Company file path reported by QuickBooks.
        /// </summary>
        /// <value>Company file path reported by QuickBooks.</value>
        [JsonPropertyName("companyFile")]
        public string? CompanyFile { get { return this.CompanyFileOption.Value; } set { this.CompanyFileOption = new(value); } }

        /// <summary>
        /// Used to track the state of Edition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EditionOption { get; private set; }

        /// <summary>
        /// QuickBooks edition, e.g. Pro or Enterprise.
        /// </summary>
        /// <value>QuickBooks edition, e.g. Pro or Enterprise.</value>
        [JsonPropertyName("edition")]
        public string? Edition { get { return this.EditionOption.Value; } set { this.EditionOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastConnectedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> LastConnectedAtOption { get; private set; }

        /// <summary>
        /// Last observed QuickBooks connection timestamp.
        /// </summary>
        /// <value>Last observed QuickBooks connection timestamp.</value>
        [JsonPropertyName("lastConnectedAt")]
        public DateTimeOffset? LastConnectedAt { get { return this.LastConnectedAtOption.Value; } set { this.LastConnectedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// When the connection record was last updated.
        /// </summary>
        /// <value>When the connection record was last updated.</value>
        [JsonPropertyName("updatedAt")]
        public DateTimeOffset? UpdatedAt { get { return this.UpdatedAtOption.Value; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectionResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ObjectType: ").Append(ObjectType).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  LifecycleState: ").Append(LifecycleState).Append("\n");
            sb.Append("  RestrictionReason: ").Append(RestrictionReason).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsArchived: ").Append(IsArchived).Append("\n");
            sb.Append("  IsOperational: ").Append(IsOperational).Append("\n");
            sb.Append("  RequiresPayment: ").Append(RequiresPayment).Append("\n");
            sb.Append("  BillingStatus: ").Append(BillingStatus).Append("\n");
            sb.Append("  BillingUrl: ").Append(BillingUrl).Append("\n");
            sb.Append("  BillingCheckoutEndpoint: ").Append(BillingCheckoutEndpoint).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  CompanyFile: ").Append(CompanyFile).Append("\n");
            sb.Append("  Edition: ").Append(Edition).Append("\n");
            sb.Append("  LastConnectedAt: ").Append(LastConnectedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConnectionResponse" />
    /// </summary>
    public class ConnectionResponseJsonConverter : JsonConverter<ConnectionResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastConnectedAt
        /// </summary>
        public static string LastConnectedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ConnectionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConnectionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<string?> objectType = default;
            Option<string?> externalId = default;
            Option<string?> description = default;
            Option<string?> mode = default;
            Option<string?> lifecycleState = default;
            Option<string?> restrictionReason = default;
            Option<bool?> isActive = default;
            Option<bool?> isArchived = default;
            Option<bool?> isOperational = default;
            Option<bool?> requiresPayment = default;
            Option<string?> billingStatus = default;
            Option<string?> billingUrl = default;
            Option<string?> billingCheckoutEndpoint = default;
            Option<string?> companyName = default;
            Option<string?> companyFile = default;
            Option<string?> edition = default;
            Option<DateTimeOffset?> lastConnectedAt = default;
            Option<DateTimeOffset?> updatedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "objectType":
                            objectType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "mode":
                            mode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "lifecycleState":
                            lifecycleState = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "restrictionReason":
                            restrictionReason = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isArchived":
                            isArchived = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isOperational":
                            isOperational = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "requiresPayment":
                            requiresPayment = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "billingStatus":
                            billingStatus = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "billingUrl":
                            billingUrl = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "billingCheckoutEndpoint":
                            billingCheckoutEndpoint = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "companyName":
                            companyName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "companyFile":
                            companyFile = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "edition":
                            edition = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastConnectedAt":
                            lastConnectedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ConnectionResponse.", nameof(id));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class ConnectionResponse.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ConnectionResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ConnectionResponse.");

            if (objectType.IsSet && objectType.Value == null)
                throw new ArgumentNullException(nameof(objectType), "Property is not nullable for class ConnectionResponse.");

            if (mode.IsSet && mode.Value == null)
                throw new ArgumentNullException(nameof(mode), "Property is not nullable for class ConnectionResponse.");

            if (lifecycleState.IsSet && lifecycleState.Value == null)
                throw new ArgumentNullException(nameof(lifecycleState), "Property is not nullable for class ConnectionResponse.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class ConnectionResponse.");

            if (isArchived.IsSet && isArchived.Value == null)
                throw new ArgumentNullException(nameof(isArchived), "Property is not nullable for class ConnectionResponse.");

            if (isOperational.IsSet && isOperational.Value == null)
                throw new ArgumentNullException(nameof(isOperational), "Property is not nullable for class ConnectionResponse.");

            if (requiresPayment.IsSet && requiresPayment.Value == null)
                throw new ArgumentNullException(nameof(requiresPayment), "Property is not nullable for class ConnectionResponse.");

            if (billingStatus.IsSet && billingStatus.Value == null)
                throw new ArgumentNullException(nameof(billingStatus), "Property is not nullable for class ConnectionResponse.");

            return new ConnectionResponse(id.Value!, createdAt.Value!.Value!, objectType, externalId, description, mode, lifecycleState, restrictionReason, isActive, isArchived, isOperational, requiresPayment, billingStatus, billingUrl, billingCheckoutEndpoint, companyName, companyFile, edition, lastConnectedAt, updatedAt);
        }

        /// <summary>
        /// Serializes a <see cref="ConnectionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConnectionResponse connectionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, connectionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConnectionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="connectionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConnectionResponse connectionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (connectionResponse.Id == null)
                throw new ArgumentNullException(nameof(connectionResponse.Id), "Property is required for class ConnectionResponse.");

            if (connectionResponse.ObjectTypeOption.IsSet && connectionResponse.ObjectType == null)
                throw new ArgumentNullException(nameof(connectionResponse.ObjectType), "Property is required for class ConnectionResponse.");

            if (connectionResponse.ModeOption.IsSet && connectionResponse.Mode == null)
                throw new ArgumentNullException(nameof(connectionResponse.Mode), "Property is required for class ConnectionResponse.");

            if (connectionResponse.LifecycleStateOption.IsSet && connectionResponse.LifecycleState == null)
                throw new ArgumentNullException(nameof(connectionResponse.LifecycleState), "Property is required for class ConnectionResponse.");

            if (connectionResponse.BillingStatusOption.IsSet && connectionResponse.BillingStatus == null)
                throw new ArgumentNullException(nameof(connectionResponse.BillingStatus), "Property is required for class ConnectionResponse.");

            writer.WriteString("id", connectionResponse.Id);

            writer.WriteString("createdAt", connectionResponse.CreatedAt.ToString(CreatedAtFormat));

            if (connectionResponse.ObjectTypeOption.IsSet)
                writer.WriteString("objectType", connectionResponse.ObjectType);

            if (connectionResponse.ExternalIdOption.IsSet)
                if (connectionResponse.ExternalIdOption.Value != null)
                    writer.WriteString("externalId", connectionResponse.ExternalId);
                else
                    writer.WriteNull("externalId");

            if (connectionResponse.DescriptionOption.IsSet)
                if (connectionResponse.DescriptionOption.Value != null)
                    writer.WriteString("description", connectionResponse.Description);
                else
                    writer.WriteNull("description");

            if (connectionResponse.ModeOption.IsSet)
                writer.WriteString("mode", connectionResponse.Mode);

            if (connectionResponse.LifecycleStateOption.IsSet)
                writer.WriteString("lifecycleState", connectionResponse.LifecycleState);

            if (connectionResponse.RestrictionReasonOption.IsSet)
                if (connectionResponse.RestrictionReasonOption.Value != null)
                    writer.WriteString("restrictionReason", connectionResponse.RestrictionReason);
                else
                    writer.WriteNull("restrictionReason");

            if (connectionResponse.IsActiveOption.IsSet)
                writer.WriteBoolean("isActive", connectionResponse.IsActiveOption.Value!.Value);

            if (connectionResponse.IsArchivedOption.IsSet)
                writer.WriteBoolean("isArchived", connectionResponse.IsArchivedOption.Value!.Value);

            if (connectionResponse.IsOperationalOption.IsSet)
                writer.WriteBoolean("isOperational", connectionResponse.IsOperationalOption.Value!.Value);

            if (connectionResponse.RequiresPaymentOption.IsSet)
                writer.WriteBoolean("requiresPayment", connectionResponse.RequiresPaymentOption.Value!.Value);

            if (connectionResponse.BillingStatusOption.IsSet)
                writer.WriteString("billingStatus", connectionResponse.BillingStatus);

            if (connectionResponse.BillingUrlOption.IsSet)
                if (connectionResponse.BillingUrlOption.Value != null)
                    writer.WriteString("billingUrl", connectionResponse.BillingUrl);
                else
                    writer.WriteNull("billingUrl");

            if (connectionResponse.BillingCheckoutEndpointOption.IsSet)
                if (connectionResponse.BillingCheckoutEndpointOption.Value != null)
                    writer.WriteString("billingCheckoutEndpoint", connectionResponse.BillingCheckoutEndpoint);
                else
                    writer.WriteNull("billingCheckoutEndpoint");

            if (connectionResponse.CompanyNameOption.IsSet)
                if (connectionResponse.CompanyNameOption.Value != null)
                    writer.WriteString("companyName", connectionResponse.CompanyName);
                else
                    writer.WriteNull("companyName");

            if (connectionResponse.CompanyFileOption.IsSet)
                if (connectionResponse.CompanyFileOption.Value != null)
                    writer.WriteString("companyFile", connectionResponse.CompanyFile);
                else
                    writer.WriteNull("companyFile");

            if (connectionResponse.EditionOption.IsSet)
                if (connectionResponse.EditionOption.Value != null)
                    writer.WriteString("edition", connectionResponse.Edition);
                else
                    writer.WriteNull("edition");

            if (connectionResponse.LastConnectedAtOption.IsSet)
                if (connectionResponse.LastConnectedAtOption.Value != null)
                    writer.WriteString("lastConnectedAt", connectionResponse.LastConnectedAtOption.Value!.Value.ToString(LastConnectedAtFormat));
                else
                    writer.WriteNull("lastConnectedAt");

            if (connectionResponse.UpdatedAtOption.IsSet)
                if (connectionResponse.UpdatedAtOption.Value != null)
                    writer.WriteString("updatedAt", connectionResponse.UpdatedAtOption.Value!.Value.ToString(UpdatedAtFormat));
                else
                    writer.WriteNull("updatedAt");
        }
    }
}
