// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// CreateServiceItemRequest
    /// </summary>
    public partial class CreateServiceItemRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateServiceItemRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="barCode">barCode</param>
        /// <param name="externalId">externalId</param>
        /// <param name="isActive">isActive</param>
        /// <param name="classId">classId</param>
        /// <param name="parentId">parentId</param>
        /// <param name="salesTaxCodeId">salesTaxCodeId</param>
        /// <param name="unitOfMeasureSetId">unitOfMeasureSetId</param>
        /// <param name="forceUOMChange">forceUOMChange</param>
        /// <param name="isTaxIncluded">isTaxIncluded</param>
        /// <param name="dataExt">dataExt</param>
        /// <param name="salesOrPurchase">salesOrPurchase</param>
        /// <param name="salesAndPurchase">salesAndPurchase</param>
        [JsonConstructor]
        public CreateServiceItemRequest(string name, Option<BarCodeRequest?> barCode = default, Option<string?> externalId = default, Option<bool?> isActive = default, Option<string?> classId = default, Option<string?> parentId = default, Option<string?> salesTaxCodeId = default, Option<string?> unitOfMeasureSetId = default, Option<bool?> forceUOMChange = default, Option<bool?> isTaxIncluded = default, Option<List<QbdDataExt>?> dataExt = default, Option<CreateSalesOrPurchaseRequest?> salesOrPurchase = default, Option<CreateSalesAndPurchaseRequest?> salesAndPurchase = default)
        {
            Name = name;
            BarCodeOption = barCode;
            ExternalIdOption = externalId;
            IsActiveOption = isActive;
            ClassIdOption = classId;
            ParentIdOption = parentId;
            SalesTaxCodeIdOption = salesTaxCodeId;
            UnitOfMeasureSetIdOption = unitOfMeasureSetId;
            ForceUOMChangeOption = forceUOMChange;
            IsTaxIncludedOption = isTaxIncluded;
            DataExtOption = dataExt;
            SalesOrPurchaseOption = salesOrPurchase;
            SalesAndPurchaseOption = salesAndPurchase;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of BarCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BarCodeRequest?> BarCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets BarCode
        /// </summary>
        [JsonPropertyName("barCode")]
        public BarCodeRequest? BarCode { get { return this.BarCodeOption.Value; } set { this.BarCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClassId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClassIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ClassId
        /// </summary>
        [JsonPropertyName("classId")]
        public string? ClassId { get { return this.ClassIdOption.Value; } set { this.ClassIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ParentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [JsonPropertyName("parentId")]
        public string? ParentId { get { return this.ParentIdOption.Value; } set { this.ParentIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesTaxCodeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesTaxCodeIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesTaxCodeId
        /// </summary>
        [JsonPropertyName("salesTaxCodeId")]
        public string? SalesTaxCodeId { get { return this.SalesTaxCodeIdOption.Value; } set { this.SalesTaxCodeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of UnitOfMeasureSetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UnitOfMeasureSetIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UnitOfMeasureSetId
        /// </summary>
        [JsonPropertyName("unitOfMeasureSetId")]
        public string? UnitOfMeasureSetId { get { return this.UnitOfMeasureSetIdOption.Value; } set { this.UnitOfMeasureSetIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ForceUOMChange
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ForceUOMChangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ForceUOMChange
        /// </summary>
        [JsonPropertyName("forceUOMChange")]
        public bool? ForceUOMChange { get { return this.ForceUOMChangeOption.Value; } set { this.ForceUOMChangeOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsTaxIncluded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsTaxIncludedOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsTaxIncluded
        /// </summary>
        [JsonPropertyName("isTaxIncluded")]
        public bool? IsTaxIncluded { get { return this.IsTaxIncludedOption.Value; } set { this.IsTaxIncludedOption = new(value); } }

        /// <summary>
        /// Used to track the state of DataExt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<QbdDataExt>?> DataExtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DataExt
        /// </summary>
        [JsonPropertyName("dataExt")]
        public List<QbdDataExt>? DataExt { get { return this.DataExtOption.Value; } set { this.DataExtOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesOrPurchase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CreateSalesOrPurchaseRequest?> SalesOrPurchaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesOrPurchase
        /// </summary>
        [JsonPropertyName("salesOrPurchase")]
        public CreateSalesOrPurchaseRequest? SalesOrPurchase { get { return this.SalesOrPurchaseOption.Value; } set { this.SalesOrPurchaseOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesAndPurchase
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CreateSalesAndPurchaseRequest?> SalesAndPurchaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesAndPurchase
        /// </summary>
        [JsonPropertyName("salesAndPurchase")]
        public CreateSalesAndPurchaseRequest? SalesAndPurchase { get { return this.SalesAndPurchaseOption.Value; } set { this.SalesAndPurchaseOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateServiceItemRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BarCode: ").Append(BarCode).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ClassId: ").Append(ClassId).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  SalesTaxCodeId: ").Append(SalesTaxCodeId).Append("\n");
            sb.Append("  UnitOfMeasureSetId: ").Append(UnitOfMeasureSetId).Append("\n");
            sb.Append("  ForceUOMChange: ").Append(ForceUOMChange).Append("\n");
            sb.Append("  IsTaxIncluded: ").Append(IsTaxIncluded).Append("\n");
            sb.Append("  DataExt: ").Append(DataExt).Append("\n");
            sb.Append("  SalesOrPurchase: ").Append(SalesOrPurchase).Append("\n");
            sb.Append("  SalesAndPurchase: ").Append(SalesAndPurchase).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ParentId (string) maxLength
            if (this.ParentId != null && this.ParentId.Length > 159)
            {
                yield return new ValidationResult("Invalid value for ParentId, length must be less than 159.", new [] { "ParentId" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateServiceItemRequest" />
    /// </summary>
    public class CreateServiceItemRequestJsonConverter : JsonConverter<CreateServiceItemRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateServiceItemRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateServiceItemRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<BarCodeRequest?> barCode = default;
            Option<string?> externalId = default;
            Option<bool?> isActive = default;
            Option<string?> classId = default;
            Option<string?> parentId = default;
            Option<string?> salesTaxCodeId = default;
            Option<string?> unitOfMeasureSetId = default;
            Option<bool?> forceUOMChange = default;
            Option<bool?> isTaxIncluded = default;
            Option<List<QbdDataExt>?> dataExt = default;
            Option<CreateSalesOrPurchaseRequest?> salesOrPurchase = default;
            Option<CreateSalesAndPurchaseRequest?> salesAndPurchase = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "barCode":
                            barCode = new Option<BarCodeRequest?>(JsonSerializer.Deserialize<BarCodeRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "classId":
                            classId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "parentId":
                            parentId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "salesTaxCodeId":
                            salesTaxCodeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "unitOfMeasureSetId":
                            unitOfMeasureSetId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "forceUOMChange":
                            forceUOMChange = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isTaxIncluded":
                            isTaxIncluded = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "dataExt":
                            dataExt = new Option<List<QbdDataExt>?>(JsonSerializer.Deserialize<List<QbdDataExt>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "salesOrPurchase":
                            salesOrPurchase = new Option<CreateSalesOrPurchaseRequest?>(JsonSerializer.Deserialize<CreateSalesOrPurchaseRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "salesAndPurchase":
                            salesAndPurchase = new Option<CreateSalesAndPurchaseRequest?>(JsonSerializer.Deserialize<CreateSalesAndPurchaseRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateServiceItemRequest.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateServiceItemRequest.");

            if (dataExt.IsSet && dataExt.Value == null)
                throw new ArgumentNullException(nameof(dataExt), "Property is not nullable for class CreateServiceItemRequest.");

            return new CreateServiceItemRequest(name.Value!, barCode, externalId, isActive, classId, parentId, salesTaxCodeId, unitOfMeasureSetId, forceUOMChange, isTaxIncluded, dataExt, salesOrPurchase, salesAndPurchase);
        }

        /// <summary>
        /// Serializes a <see cref="CreateServiceItemRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createServiceItemRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateServiceItemRequest createServiceItemRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createServiceItemRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateServiceItemRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createServiceItemRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateServiceItemRequest createServiceItemRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createServiceItemRequest.Name == null)
                throw new ArgumentNullException(nameof(createServiceItemRequest.Name), "Property is required for class CreateServiceItemRequest.");

            if (createServiceItemRequest.DataExtOption.IsSet && createServiceItemRequest.DataExt == null)
                throw new ArgumentNullException(nameof(createServiceItemRequest.DataExt), "Property is required for class CreateServiceItemRequest.");

            writer.WriteString("name", createServiceItemRequest.Name);

            if (createServiceItemRequest.BarCodeOption.IsSet)
                if (createServiceItemRequest.BarCodeOption.Value != null)
                {
                    writer.WritePropertyName("barCode");
                    JsonSerializer.Serialize(writer, createServiceItemRequest.BarCode, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("barCode");
            if (createServiceItemRequest.ExternalIdOption.IsSet)
                if (createServiceItemRequest.ExternalIdOption.Value != null)
                    writer.WriteString("externalId", createServiceItemRequest.ExternalId);
                else
                    writer.WriteNull("externalId");

            if (createServiceItemRequest.IsActiveOption.IsSet)
                if (createServiceItemRequest.IsActiveOption.Value != null)
                    writer.WriteBoolean("isActive", createServiceItemRequest.IsActiveOption.Value!.Value);
                else
                    writer.WriteNull("isActive");

            if (createServiceItemRequest.ClassIdOption.IsSet)
                if (createServiceItemRequest.ClassIdOption.Value != null)
                    writer.WriteString("classId", createServiceItemRequest.ClassId);
                else
                    writer.WriteNull("classId");

            if (createServiceItemRequest.ParentIdOption.IsSet)
                if (createServiceItemRequest.ParentIdOption.Value != null)
                    writer.WriteString("parentId", createServiceItemRequest.ParentId);
                else
                    writer.WriteNull("parentId");

            if (createServiceItemRequest.SalesTaxCodeIdOption.IsSet)
                if (createServiceItemRequest.SalesTaxCodeIdOption.Value != null)
                    writer.WriteString("salesTaxCodeId", createServiceItemRequest.SalesTaxCodeId);
                else
                    writer.WriteNull("salesTaxCodeId");

            if (createServiceItemRequest.UnitOfMeasureSetIdOption.IsSet)
                if (createServiceItemRequest.UnitOfMeasureSetIdOption.Value != null)
                    writer.WriteString("unitOfMeasureSetId", createServiceItemRequest.UnitOfMeasureSetId);
                else
                    writer.WriteNull("unitOfMeasureSetId");

            if (createServiceItemRequest.ForceUOMChangeOption.IsSet)
                if (createServiceItemRequest.ForceUOMChangeOption.Value != null)
                    writer.WriteBoolean("forceUOMChange", createServiceItemRequest.ForceUOMChangeOption.Value!.Value);
                else
                    writer.WriteNull("forceUOMChange");

            if (createServiceItemRequest.IsTaxIncludedOption.IsSet)
                if (createServiceItemRequest.IsTaxIncludedOption.Value != null)
                    writer.WriteBoolean("isTaxIncluded", createServiceItemRequest.IsTaxIncludedOption.Value!.Value);
                else
                    writer.WriteNull("isTaxIncluded");

            if (createServiceItemRequest.DataExtOption.IsSet)
            {
                writer.WritePropertyName("dataExt");
                JsonSerializer.Serialize(writer, createServiceItemRequest.DataExt, jsonSerializerOptions);
            }
            if (createServiceItemRequest.SalesOrPurchaseOption.IsSet)
                if (createServiceItemRequest.SalesOrPurchaseOption.Value != null)
                {
                    writer.WritePropertyName("salesOrPurchase");
                    JsonSerializer.Serialize(writer, createServiceItemRequest.SalesOrPurchase, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("salesOrPurchase");
            if (createServiceItemRequest.SalesAndPurchaseOption.IsSet)
                if (createServiceItemRequest.SalesAndPurchaseOption.Value != null)
                {
                    writer.WritePropertyName("salesAndPurchase");
                    JsonSerializer.Serialize(writer, createServiceItemRequest.SalesAndPurchase, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("salesAndPurchase");
        }
    }
}
