// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// A reusable request DTO for adding an Item Line to a transaction.  Based on the ItemLineAdd QBXML type.
    /// </summary>
    public partial class CreateItemLineRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateItemLineRequest" /> class.
        /// </summary>
        /// <param name="itemId">(Optional) The ListID or FullName of the item.</param>
        /// <param name="description">(Optional) Description for the line item.</param>
        /// <param name="quantity">(Optional) Quantity of the item.</param>
        /// <param name="unitOfMeasure">(Optional) Unit of measure.</param>
        /// <param name="cost">(Optional) Cost per item (used in purchases).</param>
        /// <param name="rate">(Optional) Price per item (used in sales).</param>
        /// <param name="amount">(Optional) Total amount for the line.</param>
        /// <param name="customerId">(Optional) The ListID or FullName of the customer or job.</param>
        /// <param name="classId">(Optional) The ListID or FullName of the class.</param>
        /// <param name="salesTaxCodeId">(Optional) The ListID or FullName of the sales tax code.</param>
        /// <param name="billableStatus">(Optional) Billable status (Billable, NotBillable, HasBeenBilled).</param>
        /// <param name="inventorySiteId">(Optional) The ListID or FullName of the inventory site.</param>
        /// <param name="inventorySiteLocationId">(Optional) The ListID or FullName of the inventory site location.</param>
        /// <param name="serialNumber">(Optional) Serial number for the item.</param>
        /// <param name="lotNumber">(Optional) Lot number for the item.</param>
        /// <param name="expirationDateForSerialLotNumber">(Optional) Expiration date for serial/lot number (v16.0).</param>
        /// <param name="overrideItemAccountId">(Optional) Overrides the default income/expense account associated with the item.</param>
        /// <param name="linkToTransaction">linkToTransaction</param>
        /// <param name="salesRepresentativeId">salesRepresentativeId</param>
        /// <param name="customFields">customFields</param>
        [JsonConstructor]
        public CreateItemLineRequest(Option<string?> itemId = default, Option<string?> description = default, Option<double?> quantity = default, Option<string?> unitOfMeasure = default, Option<double?> cost = default, Option<double?> rate = default, Option<double?> amount = default, Option<string?> customerId = default, Option<string?> classId = default, Option<string?> salesTaxCodeId = default, Option<string?> billableStatus = default, Option<string?> inventorySiteId = default, Option<string?> inventorySiteLocationId = default, Option<string?> serialNumber = default, Option<string?> lotNumber = default, Option<string?> expirationDateForSerialLotNumber = default, Option<string?> overrideItemAccountId = default, Option<LinkToTransactionLineRequest?> linkToTransaction = default, Option<string?> salesRepresentativeId = default, Option<List<DataExtRequest>?> customFields = default)
        {
            ItemIdOption = itemId;
            DescriptionOption = description;
            QuantityOption = quantity;
            UnitOfMeasureOption = unitOfMeasure;
            CostOption = cost;
            RateOption = rate;
            AmountOption = amount;
            CustomerIdOption = customerId;
            ClassIdOption = classId;
            SalesTaxCodeIdOption = salesTaxCodeId;
            BillableStatusOption = billableStatus;
            InventorySiteIdOption = inventorySiteId;
            InventorySiteLocationIdOption = inventorySiteLocationId;
            SerialNumberOption = serialNumber;
            LotNumberOption = lotNumber;
            ExpirationDateForSerialLotNumberOption = expirationDateForSerialLotNumber;
            OverrideItemAccountIdOption = overrideItemAccountId;
            LinkToTransactionOption = linkToTransaction;
            SalesRepresentativeIdOption = salesRepresentativeId;
            CustomFieldsOption = customFields;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ItemId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ItemIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the item.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the item.</value>
        [JsonPropertyName("itemId")]
        public string? ItemId { get { return this.ItemIdOption.Value; } set { this.ItemIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// (Optional) Description for the line item.
        /// </summary>
        /// <value>(Optional) Description for the line item.</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> QuantityOption { get; private set; }

        /// <summary>
        /// (Optional) Quantity of the item.
        /// </summary>
        /// <value>(Optional) Quantity of the item.</value>
        [JsonPropertyName("quantity")]
        public double? Quantity { get { return this.QuantityOption.Value; } set { this.QuantityOption = new(value); } }

        /// <summary>
        /// Used to track the state of UnitOfMeasure
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UnitOfMeasureOption { get; private set; }

        /// <summary>
        /// (Optional) Unit of measure.
        /// </summary>
        /// <value>(Optional) Unit of measure.</value>
        [JsonPropertyName("unitOfMeasure")]
        public string? UnitOfMeasure { get { return this.UnitOfMeasureOption.Value; } set { this.UnitOfMeasureOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CostOption { get; private set; }

        /// <summary>
        /// (Optional) Cost per item (used in purchases).
        /// </summary>
        /// <value>(Optional) Cost per item (used in purchases).</value>
        [JsonPropertyName("cost")]
        public double? Cost { get { return this.CostOption.Value; } set { this.CostOption = new(value); } }

        /// <summary>
        /// Used to track the state of Rate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> RateOption { get; private set; }

        /// <summary>
        /// (Optional) Price per item (used in sales).
        /// </summary>
        /// <value>(Optional) Price per item (used in sales).</value>
        [JsonPropertyName("rate")]
        public double? Rate { get { return this.RateOption.Value; } set { this.RateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; private set; }

        /// <summary>
        /// (Optional) Total amount for the line.
        /// </summary>
        /// <value>(Optional) Total amount for the line.</value>
        [JsonPropertyName("amount")]
        public double? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomerIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the customer or job.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the customer or job.</value>
        [JsonPropertyName("customerId")]
        public string? CustomerId { get { return this.CustomerIdOption.Value; } set { this.CustomerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClassId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClassIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the class.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the class.</value>
        [JsonPropertyName("classId")]
        public string? ClassId { get { return this.ClassIdOption.Value; } set { this.ClassIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesTaxCodeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesTaxCodeIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the sales tax code.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the sales tax code.</value>
        [JsonPropertyName("salesTaxCodeId")]
        public string? SalesTaxCodeId { get { return this.SalesTaxCodeIdOption.Value; } set { this.SalesTaxCodeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of BillableStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BillableStatusOption { get; private set; }

        /// <summary>
        /// (Optional) Billable status (Billable, NotBillable, HasBeenBilled).
        /// </summary>
        /// <value>(Optional) Billable status (Billable, NotBillable, HasBeenBilled).</value>
        [JsonPropertyName("billableStatus")]
        public string? BillableStatus { get { return this.BillableStatusOption.Value; } set { this.BillableStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of InventorySiteId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InventorySiteIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the inventory site.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the inventory site.</value>
        [JsonPropertyName("inventorySiteId")]
        public string? InventorySiteId { get { return this.InventorySiteIdOption.Value; } set { this.InventorySiteIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InventorySiteLocationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InventorySiteLocationIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the inventory site location.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the inventory site location.</value>
        [JsonPropertyName("inventorySiteLocationId")]
        public string? InventorySiteLocationId { get { return this.InventorySiteLocationIdOption.Value; } set { this.InventorySiteLocationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SerialNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SerialNumberOption { get; private set; }

        /// <summary>
        /// (Optional) Serial number for the item.
        /// </summary>
        /// <value>(Optional) Serial number for the item.</value>
        [JsonPropertyName("serialNumber")]
        public string? SerialNumber { get { return this.SerialNumberOption.Value; } set { this.SerialNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of LotNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LotNumberOption { get; private set; }

        /// <summary>
        /// (Optional) Lot number for the item.
        /// </summary>
        /// <value>(Optional) Lot number for the item.</value>
        [JsonPropertyName("lotNumber")]
        public string? LotNumber { get { return this.LotNumberOption.Value; } set { this.LotNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpirationDateForSerialLotNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExpirationDateForSerialLotNumberOption { get; private set; }

        /// <summary>
        /// (Optional) Expiration date for serial/lot number (v16.0).
        /// </summary>
        /// <value>(Optional) Expiration date for serial/lot number (v16.0).</value>
        [JsonPropertyName("expirationDateForSerialLotNumber")]
        public string? ExpirationDateForSerialLotNumber { get { return this.ExpirationDateForSerialLotNumberOption.Value; } set { this.ExpirationDateForSerialLotNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of OverrideItemAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OverrideItemAccountIdOption { get; private set; }

        /// <summary>
        /// (Optional) Overrides the default income/expense account associated with the item.
        /// </summary>
        /// <value>(Optional) Overrides the default income/expense account associated with the item.</value>
        [JsonPropertyName("overrideItemAccountId")]
        public string? OverrideItemAccountId { get { return this.OverrideItemAccountIdOption.Value; } set { this.OverrideItemAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of LinkToTransaction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LinkToTransactionLineRequest?> LinkToTransactionOption { get; private set; }

        /// <summary>
        /// Gets or Sets LinkToTransaction
        /// </summary>
        [JsonPropertyName("linkToTransaction")]
        public LinkToTransactionLineRequest? LinkToTransaction { get { return this.LinkToTransactionOption.Value; } set { this.LinkToTransactionOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesRepresentativeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesRepresentativeIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesRepresentativeId
        /// </summary>
        [JsonPropertyName("salesRepresentativeId")]
        public string? SalesRepresentativeId { get { return this.SalesRepresentativeIdOption.Value; } set { this.SalesRepresentativeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DataExtRequest>?> CustomFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [JsonPropertyName("customFields")]
        public List<DataExtRequest>? CustomFields { get { return this.CustomFieldsOption.Value; } set { this.CustomFieldsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateItemLineRequest {\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitOfMeasure: ").Append(UnitOfMeasure).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  ClassId: ").Append(ClassId).Append("\n");
            sb.Append("  SalesTaxCodeId: ").Append(SalesTaxCodeId).Append("\n");
            sb.Append("  BillableStatus: ").Append(BillableStatus).Append("\n");
            sb.Append("  InventorySiteId: ").Append(InventorySiteId).Append("\n");
            sb.Append("  InventorySiteLocationId: ").Append(InventorySiteLocationId).Append("\n");
            sb.Append("  SerialNumber: ").Append(SerialNumber).Append("\n");
            sb.Append("  LotNumber: ").Append(LotNumber).Append("\n");
            sb.Append("  ExpirationDateForSerialLotNumber: ").Append(ExpirationDateForSerialLotNumber).Append("\n");
            sb.Append("  OverrideItemAccountId: ").Append(OverrideItemAccountId).Append("\n");
            sb.Append("  LinkToTransaction: ").Append(LinkToTransaction).Append("\n");
            sb.Append("  SalesRepresentativeId: ").Append(SalesRepresentativeId).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateItemLineRequest" />
    /// </summary>
    public class CreateItemLineRequestJsonConverter : JsonConverter<CreateItemLineRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateItemLineRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateItemLineRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> itemId = default;
            Option<string?> description = default;
            Option<double?> quantity = default;
            Option<string?> unitOfMeasure = default;
            Option<double?> cost = default;
            Option<double?> rate = default;
            Option<double?> amount = default;
            Option<string?> customerId = default;
            Option<string?> classId = default;
            Option<string?> salesTaxCodeId = default;
            Option<string?> billableStatus = default;
            Option<string?> inventorySiteId = default;
            Option<string?> inventorySiteLocationId = default;
            Option<string?> serialNumber = default;
            Option<string?> lotNumber = default;
            Option<string?> expirationDateForSerialLotNumber = default;
            Option<string?> overrideItemAccountId = default;
            Option<LinkToTransactionLineRequest?> linkToTransaction = default;
            Option<string?> salesRepresentativeId = default;
            Option<List<DataExtRequest>?> customFields = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "itemId":
                            itemId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "quantity":
                            quantity = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "unitOfMeasure":
                            unitOfMeasure = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "cost":
                            cost = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "rate":
                            rate = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "amount":
                            amount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "customerId":
                            customerId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "classId":
                            classId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "salesTaxCodeId":
                            salesTaxCodeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "billableStatus":
                            billableStatus = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "inventorySiteId":
                            inventorySiteId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "inventorySiteLocationId":
                            inventorySiteLocationId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "serialNumber":
                            serialNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lotNumber":
                            lotNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "expirationDateForSerialLotNumber":
                            expirationDateForSerialLotNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "overrideItemAccountId":
                            overrideItemAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "linkToTransaction":
                            linkToTransaction = new Option<LinkToTransactionLineRequest?>(JsonSerializer.Deserialize<LinkToTransactionLineRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "salesRepresentativeId":
                            salesRepresentativeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "customFields":
                            customFields = new Option<List<DataExtRequest>?>(JsonSerializer.Deserialize<List<DataExtRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (customFields.IsSet && customFields.Value == null)
                throw new ArgumentNullException(nameof(customFields), "Property is not nullable for class CreateItemLineRequest.");

            return new CreateItemLineRequest(itemId, description, quantity, unitOfMeasure, cost, rate, amount, customerId, classId, salesTaxCodeId, billableStatus, inventorySiteId, inventorySiteLocationId, serialNumber, lotNumber, expirationDateForSerialLotNumber, overrideItemAccountId, linkToTransaction, salesRepresentativeId, customFields);
        }

        /// <summary>
        /// Serializes a <see cref="CreateItemLineRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createItemLineRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateItemLineRequest createItemLineRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createItemLineRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateItemLineRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createItemLineRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateItemLineRequest createItemLineRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createItemLineRequest.CustomFieldsOption.IsSet && createItemLineRequest.CustomFields == null)
                throw new ArgumentNullException(nameof(createItemLineRequest.CustomFields), "Property is required for class CreateItemLineRequest.");

            if (createItemLineRequest.ItemIdOption.IsSet)
                if (createItemLineRequest.ItemIdOption.Value != null)
                    writer.WriteString("itemId", createItemLineRequest.ItemId);
                else
                    writer.WriteNull("itemId");

            if (createItemLineRequest.DescriptionOption.IsSet)
                if (createItemLineRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", createItemLineRequest.Description);
                else
                    writer.WriteNull("description");

            if (createItemLineRequest.QuantityOption.IsSet)
                if (createItemLineRequest.QuantityOption.Value != null)
                    writer.WriteNumber("quantity", createItemLineRequest.QuantityOption.Value!.Value);
                else
                    writer.WriteNull("quantity");

            if (createItemLineRequest.UnitOfMeasureOption.IsSet)
                if (createItemLineRequest.UnitOfMeasureOption.Value != null)
                    writer.WriteString("unitOfMeasure", createItemLineRequest.UnitOfMeasure);
                else
                    writer.WriteNull("unitOfMeasure");

            if (createItemLineRequest.CostOption.IsSet)
                if (createItemLineRequest.CostOption.Value != null)
                    writer.WriteNumber("cost", createItemLineRequest.CostOption.Value!.Value);
                else
                    writer.WriteNull("cost");

            if (createItemLineRequest.RateOption.IsSet)
                if (createItemLineRequest.RateOption.Value != null)
                    writer.WriteNumber("rate", createItemLineRequest.RateOption.Value!.Value);
                else
                    writer.WriteNull("rate");

            if (createItemLineRequest.AmountOption.IsSet)
                if (createItemLineRequest.AmountOption.Value != null)
                    writer.WriteNumber("amount", createItemLineRequest.AmountOption.Value!.Value);
                else
                    writer.WriteNull("amount");

            if (createItemLineRequest.CustomerIdOption.IsSet)
                if (createItemLineRequest.CustomerIdOption.Value != null)
                    writer.WriteString("customerId", createItemLineRequest.CustomerId);
                else
                    writer.WriteNull("customerId");

            if (createItemLineRequest.ClassIdOption.IsSet)
                if (createItemLineRequest.ClassIdOption.Value != null)
                    writer.WriteString("classId", createItemLineRequest.ClassId);
                else
                    writer.WriteNull("classId");

            if (createItemLineRequest.SalesTaxCodeIdOption.IsSet)
                if (createItemLineRequest.SalesTaxCodeIdOption.Value != null)
                    writer.WriteString("salesTaxCodeId", createItemLineRequest.SalesTaxCodeId);
                else
                    writer.WriteNull("salesTaxCodeId");

            if (createItemLineRequest.BillableStatusOption.IsSet)
                if (createItemLineRequest.BillableStatusOption.Value != null)
                    writer.WriteString("billableStatus", createItemLineRequest.BillableStatus);
                else
                    writer.WriteNull("billableStatus");

            if (createItemLineRequest.InventorySiteIdOption.IsSet)
                if (createItemLineRequest.InventorySiteIdOption.Value != null)
                    writer.WriteString("inventorySiteId", createItemLineRequest.InventorySiteId);
                else
                    writer.WriteNull("inventorySiteId");

            if (createItemLineRequest.InventorySiteLocationIdOption.IsSet)
                if (createItemLineRequest.InventorySiteLocationIdOption.Value != null)
                    writer.WriteString("inventorySiteLocationId", createItemLineRequest.InventorySiteLocationId);
                else
                    writer.WriteNull("inventorySiteLocationId");

            if (createItemLineRequest.SerialNumberOption.IsSet)
                if (createItemLineRequest.SerialNumberOption.Value != null)
                    writer.WriteString("serialNumber", createItemLineRequest.SerialNumber);
                else
                    writer.WriteNull("serialNumber");

            if (createItemLineRequest.LotNumberOption.IsSet)
                if (createItemLineRequest.LotNumberOption.Value != null)
                    writer.WriteString("lotNumber", createItemLineRequest.LotNumber);
                else
                    writer.WriteNull("lotNumber");

            if (createItemLineRequest.ExpirationDateForSerialLotNumberOption.IsSet)
                if (createItemLineRequest.ExpirationDateForSerialLotNumberOption.Value != null)
                    writer.WriteString("expirationDateForSerialLotNumber", createItemLineRequest.ExpirationDateForSerialLotNumber);
                else
                    writer.WriteNull("expirationDateForSerialLotNumber");

            if (createItemLineRequest.OverrideItemAccountIdOption.IsSet)
                if (createItemLineRequest.OverrideItemAccountIdOption.Value != null)
                    writer.WriteString("overrideItemAccountId", createItemLineRequest.OverrideItemAccountId);
                else
                    writer.WriteNull("overrideItemAccountId");

            if (createItemLineRequest.LinkToTransactionOption.IsSet)
                if (createItemLineRequest.LinkToTransactionOption.Value != null)
                {
                    writer.WritePropertyName("linkToTransaction");
                    JsonSerializer.Serialize(writer, createItemLineRequest.LinkToTransaction, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("linkToTransaction");
            if (createItemLineRequest.SalesRepresentativeIdOption.IsSet)
                if (createItemLineRequest.SalesRepresentativeIdOption.Value != null)
                    writer.WriteString("salesRepresentativeId", createItemLineRequest.SalesRepresentativeId);
                else
                    writer.WriteNull("salesRepresentativeId");

            if (createItemLineRequest.CustomFieldsOption.IsSet)
            {
                writer.WritePropertyName("customFields");
                JsonSerializer.Serialize(writer, createItemLineRequest.CustomFields, jsonSerializerOptions);
            }
        }
    }
}
