// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// A reusable request DTO for adding an AR Refund Credit Card transaction.  Adds a credit card refund transaction that is linked to one or more QuickBooks credit memo transactions.  Based on the ARRefundCreditCardAdd QBXML type.
    /// </summary>
    public partial class CreateArRefundCreditCardRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateArRefundCreditCardRequest" /> class.
        /// </summary>
        /// <param name="customerId">(Required) The ListID or FullName of the customer receiving the refund.</param>
        /// <param name="refundAppliedToTransactions">refundAppliedToTransactions</param>
        /// <param name="refundFromAccountId">(Optional) The ListID or FullName of the account the refund is coming from. In an ARRefundCreditCardAdd, the account which is the source of funds for the credit card refund. Normally this is Undeposited Funds. However, you can specify another account if you wish. If you specify nothing here, Undeposited Funds is used by default.</param>
        /// <param name="receivablesAccountId">receivablesAccountId</param>
        /// <param name="transactionDate">transactionDate</param>
        /// <param name="refNumber">(Optional) The reference number for the refund.</param>
        /// <param name="address">(Optional) Address details for the refund.</param>
        /// <param name="paymentMethodId">(Optional) The ListID or FullName of the payment method.</param>
        /// <param name="memo">(Optional) A memo for the transaction.</param>
        /// <param name="creditCardTransaction">creditCardTransaction</param>
        /// <param name="exchangeRate">(Optional) The exchange rate for the transaction.</param>
        /// <param name="externalId">externalId</param>
        [JsonConstructor]
        public CreateArRefundCreditCardRequest(string customerId, List<RefundAppliedToTransactionRequest> refundAppliedToTransactions, Option<string?> refundFromAccountId = default, Option<string?> receivablesAccountId = default, Option<DateOnly?> transactionDate = default, Option<string?> refNumber = default, Option<AddressRequest?> address = default, Option<string?> paymentMethodId = default, Option<string?> memo = default, Option<CreditCardTransactionInfo?> creditCardTransaction = default, Option<float?> exchangeRate = default, Option<string?> externalId = default)
        {
            CustomerId = customerId;
            RefundAppliedToTransactions = refundAppliedToTransactions;
            RefundFromAccountIdOption = refundFromAccountId;
            ReceivablesAccountIdOption = receivablesAccountId;
            TransactionDateOption = transactionDate;
            RefNumberOption = refNumber;
            AddressOption = address;
            PaymentMethodIdOption = paymentMethodId;
            MemoOption = memo;
            CreditCardTransactionOption = creditCardTransaction;
            ExchangeRateOption = exchangeRate;
            ExternalIdOption = externalId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// (Required) The ListID or FullName of the customer receiving the refund.
        /// </summary>
        /// <value>(Required) The ListID or FullName of the customer receiving the refund.</value>
        [JsonPropertyName("customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets RefundAppliedToTransactions
        /// </summary>
        [JsonPropertyName("refundAppliedToTransactions")]
        public List<RefundAppliedToTransactionRequest> RefundAppliedToTransactions { get; set; }

        /// <summary>
        /// Used to track the state of RefundFromAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefundFromAccountIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the account the refund is coming from. In an ARRefundCreditCardAdd, the account which is the source of funds for the credit card refund. Normally this is Undeposited Funds. However, you can specify another account if you wish. If you specify nothing here, Undeposited Funds is used by default.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the account the refund is coming from. In an ARRefundCreditCardAdd, the account which is the source of funds for the credit card refund. Normally this is Undeposited Funds. However, you can specify another account if you wish. If you specify nothing here, Undeposited Funds is used by default.</value>
        [JsonPropertyName("refundFromAccountId")]
        public string? RefundFromAccountId { get { return this.RefundFromAccountIdOption.Value; } set { this.RefundFromAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReceivablesAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReceivablesAccountIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReceivablesAccountId
        /// </summary>
        [JsonPropertyName("receivablesAccountId")]
        public string? ReceivablesAccountId { get { return this.ReceivablesAccountIdOption.Value; } set { this.ReceivablesAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [JsonPropertyName("transactionDate")]
        public DateOnly? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// (Optional) The reference number for the refund.
        /// </summary>
        /// <value>(Optional) The reference number for the refund.</value>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AddressRequest?> AddressOption { get; private set; }

        /// <summary>
        /// (Optional) Address details for the refund.
        /// </summary>
        /// <value>(Optional) Address details for the refund.</value>
        [JsonPropertyName("address")]
        public AddressRequest? Address { get { return this.AddressOption.Value; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentMethodId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaymentMethodIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the payment method.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the payment method.</value>
        [JsonPropertyName("paymentMethodId")]
        public string? PaymentMethodId { get { return this.PaymentMethodIdOption.Value; } set { this.PaymentMethodIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Memo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MemoOption { get; private set; }

        /// <summary>
        /// (Optional) A memo for the transaction.
        /// </summary>
        /// <value>(Optional) A memo for the transaction.</value>
        [JsonPropertyName("memo")]
        public string? Memo { get { return this.MemoOption.Value; } set { this.MemoOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreditCardTransaction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CreditCardTransactionInfo?> CreditCardTransactionOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreditCardTransaction
        /// </summary>
        [JsonPropertyName("creditCardTransaction")]
        public CreditCardTransactionInfo? CreditCardTransaction { get { return this.CreditCardTransactionOption.Value; } set { this.CreditCardTransactionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> ExchangeRateOption { get; private set; }

        /// <summary>
        /// (Optional) The exchange rate for the transaction.
        /// </summary>
        /// <value>(Optional) The exchange rate for the transaction.</value>
        [JsonPropertyName("exchangeRate")]
        public float? ExchangeRate { get { return this.ExchangeRateOption.Value; } set { this.ExchangeRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateArRefundCreditCardRequest {\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  RefundAppliedToTransactions: ").Append(RefundAppliedToTransactions).Append("\n");
            sb.Append("  RefundFromAccountId: ").Append(RefundFromAccountId).Append("\n");
            sb.Append("  ReceivablesAccountId: ").Append(ReceivablesAccountId).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  PaymentMethodId: ").Append(PaymentMethodId).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  CreditCardTransaction: ").Append(CreditCardTransaction).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RefNumber (string) maxLength
            if (this.RefNumber != null && this.RefNumber.Length > 11)
            {
                yield return new ValidationResult("Invalid value for RefNumber, length must be less than 11.", new [] { "RefNumber" });
            }

            // Memo (string) maxLength
            if (this.Memo != null && this.Memo.Length > 4095)
            {
                yield return new ValidationResult("Invalid value for Memo, length must be less than 4095.", new [] { "Memo" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateArRefundCreditCardRequest" />
    /// </summary>
    public class CreateArRefundCreditCardRequestJsonConverter : JsonConverter<CreateArRefundCreditCardRequest>
    {
        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="CreateArRefundCreditCardRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateArRefundCreditCardRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> customerId = default;
            Option<List<RefundAppliedToTransactionRequest>?> refundAppliedToTransactions = default;
            Option<string?> refundFromAccountId = default;
            Option<string?> receivablesAccountId = default;
            Option<DateOnly?> transactionDate = default;
            Option<string?> refNumber = default;
            Option<AddressRequest?> address = default;
            Option<string?> paymentMethodId = default;
            Option<string?> memo = default;
            Option<CreditCardTransactionInfo?> creditCardTransaction = default;
            Option<float?> exchangeRate = default;
            Option<string?> externalId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "customerId":
                            customerId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "refundAppliedToTransactions":
                            refundAppliedToTransactions = new Option<List<RefundAppliedToTransactionRequest>?>(JsonSerializer.Deserialize<List<RefundAppliedToTransactionRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "refundFromAccountId":
                            refundFromAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "receivablesAccountId":
                            receivablesAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "address":
                            address = new Option<AddressRequest?>(JsonSerializer.Deserialize<AddressRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "paymentMethodId":
                            paymentMethodId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "memo":
                            memo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "creditCardTransaction":
                            creditCardTransaction = new Option<CreditCardTransactionInfo?>(JsonSerializer.Deserialize<CreditCardTransactionInfo>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "exchangeRate":
                            exchangeRate = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!customerId.IsSet)
                throw new ArgumentException("Property is required for class CreateArRefundCreditCardRequest.", nameof(customerId));

            if (!refundAppliedToTransactions.IsSet)
                throw new ArgumentException("Property is required for class CreateArRefundCreditCardRequest.", nameof(refundAppliedToTransactions));

            if (customerId.IsSet && customerId.Value == null)
                throw new ArgumentNullException(nameof(customerId), "Property is not nullable for class CreateArRefundCreditCardRequest.");

            if (refundAppliedToTransactions.IsSet && refundAppliedToTransactions.Value == null)
                throw new ArgumentNullException(nameof(refundAppliedToTransactions), "Property is not nullable for class CreateArRefundCreditCardRequest.");

            return new CreateArRefundCreditCardRequest(customerId.Value!, refundAppliedToTransactions.Value!, refundFromAccountId, receivablesAccountId, transactionDate, refNumber, address, paymentMethodId, memo, creditCardTransaction, exchangeRate, externalId);
        }

        /// <summary>
        /// Serializes a <see cref="CreateArRefundCreditCardRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createArRefundCreditCardRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateArRefundCreditCardRequest createArRefundCreditCardRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createArRefundCreditCardRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateArRefundCreditCardRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createArRefundCreditCardRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateArRefundCreditCardRequest createArRefundCreditCardRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createArRefundCreditCardRequest.CustomerId == null)
                throw new ArgumentNullException(nameof(createArRefundCreditCardRequest.CustomerId), "Property is required for class CreateArRefundCreditCardRequest.");

            if (createArRefundCreditCardRequest.RefundAppliedToTransactions == null)
                throw new ArgumentNullException(nameof(createArRefundCreditCardRequest.RefundAppliedToTransactions), "Property is required for class CreateArRefundCreditCardRequest.");

            writer.WriteString("customerId", createArRefundCreditCardRequest.CustomerId);

            writer.WritePropertyName("refundAppliedToTransactions");
            JsonSerializer.Serialize(writer, createArRefundCreditCardRequest.RefundAppliedToTransactions, jsonSerializerOptions);
            if (createArRefundCreditCardRequest.RefundFromAccountIdOption.IsSet)
                if (createArRefundCreditCardRequest.RefundFromAccountIdOption.Value != null)
                    writer.WriteString("refundFromAccountId", createArRefundCreditCardRequest.RefundFromAccountId);
                else
                    writer.WriteNull("refundFromAccountId");

            if (createArRefundCreditCardRequest.ReceivablesAccountIdOption.IsSet)
                if (createArRefundCreditCardRequest.ReceivablesAccountIdOption.Value != null)
                    writer.WriteString("receivablesAccountId", createArRefundCreditCardRequest.ReceivablesAccountId);
                else
                    writer.WriteNull("receivablesAccountId");

            if (createArRefundCreditCardRequest.TransactionDateOption.IsSet)
                if (createArRefundCreditCardRequest.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", createArRefundCreditCardRequest.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (createArRefundCreditCardRequest.RefNumberOption.IsSet)
                if (createArRefundCreditCardRequest.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", createArRefundCreditCardRequest.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (createArRefundCreditCardRequest.AddressOption.IsSet)
                if (createArRefundCreditCardRequest.AddressOption.Value != null)
                {
                    writer.WritePropertyName("address");
                    JsonSerializer.Serialize(writer, createArRefundCreditCardRequest.Address, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("address");
            if (createArRefundCreditCardRequest.PaymentMethodIdOption.IsSet)
                if (createArRefundCreditCardRequest.PaymentMethodIdOption.Value != null)
                    writer.WriteString("paymentMethodId", createArRefundCreditCardRequest.PaymentMethodId);
                else
                    writer.WriteNull("paymentMethodId");

            if (createArRefundCreditCardRequest.MemoOption.IsSet)
                if (createArRefundCreditCardRequest.MemoOption.Value != null)
                    writer.WriteString("memo", createArRefundCreditCardRequest.Memo);
                else
                    writer.WriteNull("memo");

            if (createArRefundCreditCardRequest.CreditCardTransactionOption.IsSet)
                if (createArRefundCreditCardRequest.CreditCardTransactionOption.Value != null)
                {
                    writer.WritePropertyName("creditCardTransaction");
                    JsonSerializer.Serialize(writer, createArRefundCreditCardRequest.CreditCardTransaction, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("creditCardTransaction");
            if (createArRefundCreditCardRequest.ExchangeRateOption.IsSet)
                if (createArRefundCreditCardRequest.ExchangeRateOption.Value != null)
                    writer.WriteNumber("exchangeRate", createArRefundCreditCardRequest.ExchangeRateOption.Value!.Value);
                else
                    writer.WriteNull("exchangeRate");

            if (createArRefundCreditCardRequest.ExternalIdOption.IsSet)
                if (createArRefundCreditCardRequest.ExternalIdOption.Value != null)
                    writer.WriteString("externalId", createArRefundCreditCardRequest.ExternalId);
                else
                    writer.WriteNull("externalId");
        }
    }
}
