// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// EmergencyContact
    /// </summary>
    public partial class EmergencyContact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmergencyContact" /> class.
        /// </summary>
        /// <param name="primaryContact">primaryContact</param>
        /// <param name="secondaryContact">secondaryContact</param>
        [JsonConstructor]
        public EmergencyContact(Option<AdditionalContact?> primaryContact = default, Option<AdditionalContact?> secondaryContact = default)
        {
            PrimaryContactOption = primaryContact;
            SecondaryContactOption = secondaryContact;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PrimaryContact
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AdditionalContact?> PrimaryContactOption { get; private set; }

        /// <summary>
        /// Gets or Sets PrimaryContact
        /// </summary>
        [JsonPropertyName("primaryContact")]
        public AdditionalContact? PrimaryContact { get { return this.PrimaryContactOption.Value; } set { this.PrimaryContactOption = new(value); } }

        /// <summary>
        /// Used to track the state of SecondaryContact
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AdditionalContact?> SecondaryContactOption { get; private set; }

        /// <summary>
        /// Gets or Sets SecondaryContact
        /// </summary>
        [JsonPropertyName("secondaryContact")]
        public AdditionalContact? SecondaryContact { get { return this.SecondaryContactOption.Value; } set { this.SecondaryContactOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmergencyContact {\n");
            sb.Append("  PrimaryContact: ").Append(PrimaryContact).Append("\n");
            sb.Append("  SecondaryContact: ").Append(SecondaryContact).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EmergencyContact" />
    /// </summary>
    public class EmergencyContactJsonConverter : JsonConverter<EmergencyContact>
    {
        /// <summary>
        /// Deserializes json to <see cref="EmergencyContact" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EmergencyContact Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<AdditionalContact?> primaryContact = default;
            Option<AdditionalContact?> secondaryContact = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "primaryContact":
                            primaryContact = new Option<AdditionalContact?>(JsonSerializer.Deserialize<AdditionalContact>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "secondaryContact":
                            secondaryContact = new Option<AdditionalContact?>(JsonSerializer.Deserialize<AdditionalContact>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EmergencyContact(primaryContact, secondaryContact);
        }

        /// <summary>
        /// Serializes a <see cref="EmergencyContact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emergencyContact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EmergencyContact emergencyContact, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, emergencyContact, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EmergencyContact" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="emergencyContact"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, EmergencyContact emergencyContact, JsonSerializerOptions jsonSerializerOptions)
        {
            if (emergencyContact.PrimaryContactOption.IsSet)
                if (emergencyContact.PrimaryContactOption.Value != null)
                {
                    writer.WritePropertyName("primaryContact");
                    JsonSerializer.Serialize(writer, emergencyContact.PrimaryContact, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("primaryContact");
            if (emergencyContact.SecondaryContactOption.IsSet)
                if (emergencyContact.SecondaryContactOption.Value != null)
                {
                    writer.WritePropertyName("secondaryContact");
                    JsonSerializer.Serialize(writer, emergencyContact.SecondaryContact, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("secondaryContact");
        }
    }
}
