// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// ItemOtherChargeSalesOrPurchaseDetailsRequest
    /// </summary>
    public partial class ItemOtherChargeSalesOrPurchaseDetailsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemOtherChargeSalesOrPurchaseDetailsRequest" /> class.
        /// </summary>
        /// <param name="description">description</param>
        /// <param name="price">price</param>
        /// <param name="pricePercentage">pricePercentage</param>
        /// <param name="postingAccountId">postingAccountId</param>
        [JsonConstructor]
        public ItemOtherChargeSalesOrPurchaseDetailsRequest(Option<string?> description = default, Option<double?> price = default, Option<double?> pricePercentage = default, Option<string?> postingAccountId = default)
        {
            DescriptionOption = description;
            PriceOption = price;
            PricePercentageOption = pricePercentage;
            PostingAccountIdOption = postingAccountId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Price
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PriceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [JsonPropertyName("price")]
        public double? Price { get { return this.PriceOption.Value; } set { this.PriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of PricePercentage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PricePercentageOption { get; private set; }

        /// <summary>
        /// Gets or Sets PricePercentage
        /// </summary>
        [JsonPropertyName("pricePercentage")]
        public double? PricePercentage { get { return this.PricePercentageOption.Value; } set { this.PricePercentageOption = new(value); } }

        /// <summary>
        /// Used to track the state of PostingAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PostingAccountIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PostingAccountId
        /// </summary>
        [JsonPropertyName("postingAccountId")]
        public string? PostingAccountId { get { return this.PostingAccountIdOption.Value; } set { this.PostingAccountIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ItemOtherChargeSalesOrPurchaseDetailsRequest {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  PricePercentage: ").Append(PricePercentage).Append("\n");
            sb.Append("  PostingAccountId: ").Append(PostingAccountId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ItemOtherChargeSalesOrPurchaseDetailsRequest" />
    /// </summary>
    public class ItemOtherChargeSalesOrPurchaseDetailsRequestJsonConverter : JsonConverter<ItemOtherChargeSalesOrPurchaseDetailsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ItemOtherChargeSalesOrPurchaseDetailsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ItemOtherChargeSalesOrPurchaseDetailsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> description = default;
            Option<double?> price = default;
            Option<double?> pricePercentage = default;
            Option<string?> postingAccountId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "price":
                            price = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "pricePercentage":
                            pricePercentage = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "postingAccountId":
                            postingAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ItemOtherChargeSalesOrPurchaseDetailsRequest(description, price, pricePercentage, postingAccountId);
        }

        /// <summary>
        /// Serializes a <see cref="ItemOtherChargeSalesOrPurchaseDetailsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="itemOtherChargeSalesOrPurchaseDetailsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ItemOtherChargeSalesOrPurchaseDetailsRequest itemOtherChargeSalesOrPurchaseDetailsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, itemOtherChargeSalesOrPurchaseDetailsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ItemOtherChargeSalesOrPurchaseDetailsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="itemOtherChargeSalesOrPurchaseDetailsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ItemOtherChargeSalesOrPurchaseDetailsRequest itemOtherChargeSalesOrPurchaseDetailsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (itemOtherChargeSalesOrPurchaseDetailsRequest.DescriptionOption.IsSet)
                if (itemOtherChargeSalesOrPurchaseDetailsRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", itemOtherChargeSalesOrPurchaseDetailsRequest.Description);
                else
                    writer.WriteNull("description");

            if (itemOtherChargeSalesOrPurchaseDetailsRequest.PriceOption.IsSet)
                if (itemOtherChargeSalesOrPurchaseDetailsRequest.PriceOption.Value != null)
                    writer.WriteNumber("price", itemOtherChargeSalesOrPurchaseDetailsRequest.PriceOption.Value!.Value);
                else
                    writer.WriteNull("price");

            if (itemOtherChargeSalesOrPurchaseDetailsRequest.PricePercentageOption.IsSet)
                if (itemOtherChargeSalesOrPurchaseDetailsRequest.PricePercentageOption.Value != null)
                    writer.WriteNumber("pricePercentage", itemOtherChargeSalesOrPurchaseDetailsRequest.PricePercentageOption.Value!.Value);
                else
                    writer.WriteNull("pricePercentage");

            if (itemOtherChargeSalesOrPurchaseDetailsRequest.PostingAccountIdOption.IsSet)
                if (itemOtherChargeSalesOrPurchaseDetailsRequest.PostingAccountIdOption.Value != null)
                    writer.WriteString("postingAccountId", itemOtherChargeSalesOrPurchaseDetailsRequest.PostingAccountId);
                else
                    writer.WriteNull("postingAccountId");
        }
    }
}
