// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Specific object type for the Item.  Matches the XML return tag name (e.g. ItemServiceRet -&amp;gt; Service).
    /// </summary>
    /// <value>Specific object type for the Item.  Matches the XML return tag name (e.g. ItemServiceRet -&amp;gt; Service).</value>
    public enum ItemItemGroupItemType
    {
        /// <summary>
        /// Enum Group for value: Group
        /// </summary>
        Group = 1
    }

    /// <summary>
    /// Converts <see cref="ItemItemGroupItemType"/> to and from the JSON value
    /// </summary>
    public static class ItemItemGroupItemTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ItemItemGroupItemType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ItemItemGroupItemType FromString(string value)
        {
            if (value.Equals("Group"))
                return ItemItemGroupItemType.Group;

            throw new NotImplementedException($"Could not convert value to type ItemItemGroupItemType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ItemItemGroupItemType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ItemItemGroupItemType? FromStringOrDefault(string value)
        {
            if (value.Equals("Group"))
                return ItemItemGroupItemType.Group;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ItemItemGroupItemType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ItemItemGroupItemType value)
        {
            if (value == ItemItemGroupItemType.Group)
                return "Group";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ItemItemGroupItemType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ItemItemGroupItemTypeJsonConverter : JsonConverter<ItemItemGroupItemType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ItemItemGroupItemType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ItemItemGroupItemType? result = rawValue == null
                ? null
                : ItemItemGroupItemTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ItemItemGroupItemType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="itemItemGroupItemType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ItemItemGroupItemType itemItemGroupItemType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ItemItemGroupItemTypeValueConverter.ToJsonValue(itemItemGroupItemType).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ItemItemGroupItemType"/>
    /// </summary>
    public class ItemItemGroupItemTypeNullableJsonConverter : JsonConverter<ItemItemGroupItemType?>
    {
        /// <summary>
        /// Returns a ItemItemGroupItemType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ItemItemGroupItemType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ItemItemGroupItemType? result = rawValue == null
                ? null
                : ItemItemGroupItemTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ItemItemGroupItemType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="itemItemGroupItemType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ItemItemGroupItemType? itemItemGroupItemType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(itemItemGroupItemType.HasValue ? ItemItemGroupItemTypeValueConverter.ToJsonValue(itemItemGroupItemType.Value).ToString() : "null");
        }
    }
}
