// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Defines NullableCashFlowClassification
    /// </summary>
    public enum NullableCashFlowClassification
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        None = 1,

        /// <summary>
        /// Enum Operating for value: Operating
        /// </summary>
        Operating = 2,

        /// <summary>
        /// Enum Investing for value: Investing
        /// </summary>
        Investing = 3,

        /// <summary>
        /// Enum Financing for value: Financing
        /// </summary>
        Financing = 4,

        /// <summary>
        /// Enum NotApplicable for value: NotApplicable
        /// </summary>
        NotApplicable = 5
    }

    /// <summary>
    /// Converts <see cref="NullableCashFlowClassification"/> to and from the JSON value
    /// </summary>
    public static class NullableCashFlowClassificationValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="NullableCashFlowClassification"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullableCashFlowClassification FromString(string value)
        {
            if (value.Equals("None"))
                return NullableCashFlowClassification.None;

            if (value.Equals("Operating"))
                return NullableCashFlowClassification.Operating;

            if (value.Equals("Investing"))
                return NullableCashFlowClassification.Investing;

            if (value.Equals("Financing"))
                return NullableCashFlowClassification.Financing;

            if (value.Equals("NotApplicable"))
                return NullableCashFlowClassification.NotApplicable;

            throw new NotImplementedException($"Could not convert value to type NullableCashFlowClassification: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="NullableCashFlowClassification"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullableCashFlowClassification? FromStringOrDefault(string value)
        {
            if (value.Equals("None"))
                return NullableCashFlowClassification.None;

            if (value.Equals("Operating"))
                return NullableCashFlowClassification.Operating;

            if (value.Equals("Investing"))
                return NullableCashFlowClassification.Investing;

            if (value.Equals("Financing"))
                return NullableCashFlowClassification.Financing;

            if (value.Equals("NotApplicable"))
                return NullableCashFlowClassification.NotApplicable;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NullableCashFlowClassification"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(NullableCashFlowClassification value)
        {
            if (value == NullableCashFlowClassification.None)
                return "None";

            if (value == NullableCashFlowClassification.Operating)
                return "Operating";

            if (value == NullableCashFlowClassification.Investing)
                return "Investing";

            if (value == NullableCashFlowClassification.Financing)
                return "Financing";

            if (value == NullableCashFlowClassification.NotApplicable)
                return "NotApplicable";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NullableCashFlowClassification"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class NullableCashFlowClassificationJsonConverter : JsonConverter<NullableCashFlowClassification>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NullableCashFlowClassification Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NullableCashFlowClassification? result = rawValue == null
                ? null
                : NullableCashFlowClassificationValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NullableCashFlowClassification to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nullableCashFlowClassification"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NullableCashFlowClassification nullableCashFlowClassification, JsonSerializerOptions options)
        {
            writer.WriteStringValue(NullableCashFlowClassificationValueConverter.ToJsonValue(nullableCashFlowClassification).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NullableCashFlowClassification"/>
    /// </summary>
    public class NullableCashFlowClassificationNullableJsonConverter : JsonConverter<NullableCashFlowClassification?>
    {
        /// <summary>
        /// Returns a NullableCashFlowClassification from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NullableCashFlowClassification? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NullableCashFlowClassification? result = rawValue == null
                ? null
                : NullableCashFlowClassificationValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NullableCashFlowClassification to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nullableCashFlowClassification"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NullableCashFlowClassification? nullableCashFlowClassification, JsonSerializerOptions options)
        {
            writer.WriteStringValue(nullableCashFlowClassification.HasValue ? NullableCashFlowClassificationValueConverter.ToJsonValue(nullableCashFlowClassification.Value).ToString() : "null");
        }
    }
}
