// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Represents a generic transaction returned from a TransactionQuery.  This is often used when the specific type (Check, Invoice, etc.) is not known.
    /// </summary>
    public partial class Transaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Transaction" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="objectType">objectType</param>
        /// <param name="transactionDate">transactionDate</param>
        /// <param name="currency">currency</param>
        /// <param name="exchangeRate">exchangeRate</param>
        /// <param name="refNumber">refNumber</param>
        /// <param name="memo">memo</param>
        /// <param name="transactionType">transactionType</param>
        /// <param name="transactionLineId">transactionLineId</param>
        /// <param name="entity">The entity associated with this transaction (Customer, Vendor, Employee, etc.)</param>
        /// <param name="amount">amount</param>
        /// <param name="account">account</param>
        /// <param name="amountInHomeCurrency">amountInHomeCurrency</param>
        /// <param name="hasValidLineItems">hasValidLineItems</param>
        /// <param name="externalId">externalId</param>
        /// <param name="linkedTransactions">linkedTransactions</param>
        /// <param name="expenseLines">expenseLines</param>
        /// <param name="itemLines">itemLines</param>
        /// <param name="itemGroupLines">itemGroupLines</param>
        /// <param name="customFields">customFields</param>
        [JsonConstructor]
        public Transaction(string id, DateTimeOffset createdAt, DateTimeOffset updatedAt, string revisionNumber, Option<string?> objectType = default, Option<DateOnly?> transactionDate = default, Option<QbdRef?> currency = default, Option<double?> exchangeRate = default, Option<string?> refNumber = default, Option<string?> memo = default, Option<string?> transactionType = default, Option<string?> transactionLineId = default, Option<QbdRef?> entity = default, Option<double?> amount = default, Option<QbdRef?> account = default, Option<string?> amountInHomeCurrency = default, Option<bool?> hasValidLineItems = default, Option<string?> externalId = default, Option<List<LinkedTransaction>?> linkedTransactions = default, Option<List<ExpenseLine>?> expenseLines = default, Option<List<ItemLine>?> itemLines = default, Option<List<ItemGroupLine>?> itemGroupLines = default, Option<List<QbdDataExt>?> customFields = default)
        {
            Id = id;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            RevisionNumber = revisionNumber;
            ObjectTypeOption = objectType;
            TransactionDateOption = transactionDate;
            CurrencyOption = currency;
            ExchangeRateOption = exchangeRate;
            RefNumberOption = refNumber;
            MemoOption = memo;
            TransactionTypeOption = transactionType;
            TransactionLineIdOption = transactionLineId;
            EntityOption = entity;
            AmountOption = amount;
            AccountOption = account;
            AmountInHomeCurrencyOption = amountInHomeCurrency;
            HasValidLineItemsOption = hasValidLineItems;
            ExternalIdOption = externalId;
            LinkedTransactionsOption = linkedTransactions;
            ExpenseLinesOption = expenseLines;
            ItemLinesOption = itemLines;
            ItemGroupLinesOption = itemGroupLines;
            CustomFieldsOption = customFields;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of ObjectType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ObjectTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ObjectType
        /// </summary>
        [JsonPropertyName("objectType")]
        public string? ObjectType { get { return this.ObjectTypeOption.Value; } set { this.ObjectTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [JsonPropertyName("transactionDate")]
        public DateOnly? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Currency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QbdRef?> CurrencyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public QbdRef? Currency { get { return this.CurrencyOption.Value; } set { this.CurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ExchangeRateOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExchangeRate
        /// </summary>
        [JsonPropertyName("exchangeRate")]
        public double? ExchangeRate { get { return this.ExchangeRateOption.Value; } set { this.ExchangeRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets RefNumber
        /// </summary>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of Memo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MemoOption { get; private set; }

        /// <summary>
        /// Gets or Sets Memo
        /// </summary>
        [JsonPropertyName("memo")]
        public string? Memo { get { return this.MemoOption.Value; } set { this.MemoOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionType
        /// </summary>
        [JsonPropertyName("transactionType")]
        public string? TransactionType { get { return this.TransactionTypeOption.Value; } set { this.TransactionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionLineId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionLineIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionLineId
        /// </summary>
        [JsonPropertyName("transactionLineId")]
        public string? TransactionLineId { get { return this.TransactionLineIdOption.Value; } set { this.TransactionLineIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Entity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QbdRef?> EntityOption { get; private set; }

        /// <summary>
        /// The entity associated with this transaction (Customer, Vendor, Employee, etc.)
        /// </summary>
        /// <value>The entity associated with this transaction (Customer, Vendor, Employee, etc.)</value>
        [JsonPropertyName("entity")]
        public QbdRef? Entity { get { return this.EntityOption.Value; } set { this.EntityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public double? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Account
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<QbdRef?> AccountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [JsonPropertyName("account")]
        public QbdRef? Account { get { return this.AccountOption.Value; } set { this.AccountOption = new(value); } }

        /// <summary>
        /// Used to track the state of AmountInHomeCurrency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AmountInHomeCurrencyOption { get; private set; }

        /// <summary>
        /// Gets or Sets AmountInHomeCurrency
        /// </summary>
        [JsonPropertyName("amountInHomeCurrency")]
        public string? AmountInHomeCurrency { get { return this.AmountInHomeCurrencyOption.Value; } set { this.AmountInHomeCurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of HasValidLineItems
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasValidLineItemsOption { get; private set; }

        /// <summary>
        /// Gets or Sets HasValidLineItems
        /// </summary>
        [JsonPropertyName("hasValidLineItems")]
        public bool? HasValidLineItems { get { return this.HasValidLineItemsOption.Value; } set { this.HasValidLineItemsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExternalIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get { return this.ExternalIdOption.Value; } set { this.ExternalIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of LinkedTransactions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LinkedTransaction>?> LinkedTransactionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets LinkedTransactions
        /// </summary>
        [JsonPropertyName("linkedTransactions")]
        public List<LinkedTransaction>? LinkedTransactions { get { return this.LinkedTransactionsOption.Value; } set { this.LinkedTransactionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpenseLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ExpenseLine>?> ExpenseLinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpenseLines
        /// </summary>
        [JsonPropertyName("expenseLines")]
        public List<ExpenseLine>? ExpenseLines { get { return this.ExpenseLinesOption.Value; } set { this.ExpenseLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ItemLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ItemLine>?> ItemLinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ItemLines
        /// </summary>
        [JsonPropertyName("itemLines")]
        public List<ItemLine>? ItemLines { get { return this.ItemLinesOption.Value; } set { this.ItemLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ItemGroupLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ItemGroupLine>?> ItemGroupLinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ItemGroupLines
        /// </summary>
        [JsonPropertyName("itemGroupLines")]
        public List<ItemGroupLine>? ItemGroupLines { get { return this.ItemGroupLinesOption.Value; } set { this.ItemGroupLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<QbdDataExt>?> CustomFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [JsonPropertyName("customFields")]
        public List<QbdDataExt>? CustomFields { get { return this.CustomFieldsOption.Value; } set { this.CustomFieldsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Transaction {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  ObjectType: ").Append(ObjectType).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  TransactionLineId: ").Append(TransactionLineId).Append("\n");
            sb.Append("  Entity: ").Append(Entity).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  AmountInHomeCurrency: ").Append(AmountInHomeCurrency).Append("\n");
            sb.Append("  HasValidLineItems: ").Append(HasValidLineItems).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  LinkedTransactions: ").Append(LinkedTransactions).Append("\n");
            sb.Append("  ExpenseLines: ").Append(ExpenseLines).Append("\n");
            sb.Append("  ItemLines: ").Append(ItemLines).Append("\n");
            sb.Append("  ItemGroupLines: ").Append(ItemGroupLines).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Transaction" />
    /// </summary>
    public class TransactionJsonConverter : JsonConverter<Transaction>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="Transaction" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Transaction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<DateTimeOffset?> updatedAt = default;
            Option<string?> revisionNumber = default;
            Option<string?> objectType = default;
            Option<DateOnly?> transactionDate = default;
            Option<QbdRef?> currency = default;
            Option<double?> exchangeRate = default;
            Option<string?> refNumber = default;
            Option<string?> memo = default;
            Option<string?> transactionType = default;
            Option<string?> transactionLineId = default;
            Option<QbdRef?> entity = default;
            Option<double?> amount = default;
            Option<QbdRef?> account = default;
            Option<string?> amountInHomeCurrency = default;
            Option<bool?> hasValidLineItems = default;
            Option<string?> externalId = default;
            Option<List<LinkedTransaction>?> linkedTransactions = default;
            Option<List<ExpenseLine>?> expenseLines = default;
            Option<List<ItemLine>?> itemLines = default;
            Option<List<ItemGroupLine>?> itemGroupLines = default;
            Option<List<QbdDataExt>?> customFields = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "createdAt":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            updatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "objectType":
                            objectType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "currency":
                            currency = new Option<QbdRef?>(JsonSerializer.Deserialize<QbdRef>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "exchangeRate":
                            exchangeRate = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "memo":
                            memo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionType":
                            transactionType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionLineId":
                            transactionLineId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "entity":
                            entity = new Option<QbdRef?>(JsonSerializer.Deserialize<QbdRef>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "amount":
                            amount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "account":
                            account = new Option<QbdRef?>(JsonSerializer.Deserialize<QbdRef>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "amountInHomeCurrency":
                            amountInHomeCurrency = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "hasValidLineItems":
                            hasValidLineItems = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "linkedTransactions":
                            linkedTransactions = new Option<List<LinkedTransaction>?>(JsonSerializer.Deserialize<List<LinkedTransaction>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "expenseLines":
                            expenseLines = new Option<List<ExpenseLine>?>(JsonSerializer.Deserialize<List<ExpenseLine>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "itemLines":
                            itemLines = new Option<List<ItemLine>?>(JsonSerializer.Deserialize<List<ItemLine>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "itemGroupLines":
                            itemGroupLines = new Option<List<ItemGroupLine>?>(JsonSerializer.Deserialize<List<ItemGroupLine>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "customFields":
                            customFields = new Option<List<QbdDataExt>?>(JsonSerializer.Deserialize<List<QbdDataExt>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(id));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(updatedAt));

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class Transaction.", nameof(revisionNumber));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Transaction.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Transaction.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class Transaction.");

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class Transaction.");

            if (objectType.IsSet && objectType.Value == null)
                throw new ArgumentNullException(nameof(objectType), "Property is not nullable for class Transaction.");

            if (hasValidLineItems.IsSet && hasValidLineItems.Value == null)
                throw new ArgumentNullException(nameof(hasValidLineItems), "Property is not nullable for class Transaction.");

            if (linkedTransactions.IsSet && linkedTransactions.Value == null)
                throw new ArgumentNullException(nameof(linkedTransactions), "Property is not nullable for class Transaction.");

            if (expenseLines.IsSet && expenseLines.Value == null)
                throw new ArgumentNullException(nameof(expenseLines), "Property is not nullable for class Transaction.");

            if (itemLines.IsSet && itemLines.Value == null)
                throw new ArgumentNullException(nameof(itemLines), "Property is not nullable for class Transaction.");

            if (itemGroupLines.IsSet && itemGroupLines.Value == null)
                throw new ArgumentNullException(nameof(itemGroupLines), "Property is not nullable for class Transaction.");

            if (customFields.IsSet && customFields.Value == null)
                throw new ArgumentNullException(nameof(customFields), "Property is not nullable for class Transaction.");

            return new Transaction(id.Value!, createdAt.Value!.Value!, updatedAt.Value!.Value!, revisionNumber.Value!, objectType, transactionDate, currency, exchangeRate, refNumber, memo, transactionType, transactionLineId, entity, amount, account, amountInHomeCurrency, hasValidLineItems, externalId, linkedTransactions, expenseLines, itemLines, itemGroupLines, customFields);
        }

        /// <summary>
        /// Serializes a <see cref="Transaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Transaction transaction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, transaction, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Transaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Transaction transaction, JsonSerializerOptions jsonSerializerOptions)
        {
            if (transaction.Id == null)
                throw new ArgumentNullException(nameof(transaction.Id), "Property is required for class Transaction.");

            if (transaction.RevisionNumber == null)
                throw new ArgumentNullException(nameof(transaction.RevisionNumber), "Property is required for class Transaction.");

            if (transaction.ObjectTypeOption.IsSet && transaction.ObjectType == null)
                throw new ArgumentNullException(nameof(transaction.ObjectType), "Property is required for class Transaction.");

            if (transaction.LinkedTransactionsOption.IsSet && transaction.LinkedTransactions == null)
                throw new ArgumentNullException(nameof(transaction.LinkedTransactions), "Property is required for class Transaction.");

            if (transaction.ExpenseLinesOption.IsSet && transaction.ExpenseLines == null)
                throw new ArgumentNullException(nameof(transaction.ExpenseLines), "Property is required for class Transaction.");

            if (transaction.ItemLinesOption.IsSet && transaction.ItemLines == null)
                throw new ArgumentNullException(nameof(transaction.ItemLines), "Property is required for class Transaction.");

            if (transaction.ItemGroupLinesOption.IsSet && transaction.ItemGroupLines == null)
                throw new ArgumentNullException(nameof(transaction.ItemGroupLines), "Property is required for class Transaction.");

            if (transaction.CustomFieldsOption.IsSet && transaction.CustomFields == null)
                throw new ArgumentNullException(nameof(transaction.CustomFields), "Property is required for class Transaction.");

            writer.WriteString("id", transaction.Id);

            writer.WriteString("createdAt", transaction.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("updatedAt", transaction.UpdatedAt.ToString(UpdatedAtFormat));

            writer.WriteString("revisionNumber", transaction.RevisionNumber);

            if (transaction.ObjectTypeOption.IsSet)
                writer.WriteString("objectType", transaction.ObjectType);

            if (transaction.TransactionDateOption.IsSet)
                if (transaction.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", transaction.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (transaction.CurrencyOption.IsSet)
                if (transaction.CurrencyOption.Value != null)
                {
                    writer.WritePropertyName("currency");
                    JsonSerializer.Serialize(writer, transaction.Currency, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("currency");
            if (transaction.ExchangeRateOption.IsSet)
                if (transaction.ExchangeRateOption.Value != null)
                    writer.WriteNumber("exchangeRate", transaction.ExchangeRateOption.Value!.Value);
                else
                    writer.WriteNull("exchangeRate");

            if (transaction.RefNumberOption.IsSet)
                if (transaction.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", transaction.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (transaction.MemoOption.IsSet)
                if (transaction.MemoOption.Value != null)
                    writer.WriteString("memo", transaction.Memo);
                else
                    writer.WriteNull("memo");

            if (transaction.TransactionTypeOption.IsSet)
                if (transaction.TransactionTypeOption.Value != null)
                    writer.WriteString("transactionType", transaction.TransactionType);
                else
                    writer.WriteNull("transactionType");

            if (transaction.TransactionLineIdOption.IsSet)
                if (transaction.TransactionLineIdOption.Value != null)
                    writer.WriteString("transactionLineId", transaction.TransactionLineId);
                else
                    writer.WriteNull("transactionLineId");

            if (transaction.EntityOption.IsSet)
                if (transaction.EntityOption.Value != null)
                {
                    writer.WritePropertyName("entity");
                    JsonSerializer.Serialize(writer, transaction.Entity, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("entity");
            if (transaction.AmountOption.IsSet)
                if (transaction.AmountOption.Value != null)
                    writer.WriteNumber("amount", transaction.AmountOption.Value!.Value);
                else
                    writer.WriteNull("amount");

            if (transaction.AccountOption.IsSet)
                if (transaction.AccountOption.Value != null)
                {
                    writer.WritePropertyName("account");
                    JsonSerializer.Serialize(writer, transaction.Account, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("account");
            if (transaction.AmountInHomeCurrencyOption.IsSet)
                if (transaction.AmountInHomeCurrencyOption.Value != null)
                    writer.WriteString("amountInHomeCurrency", transaction.AmountInHomeCurrency);
                else
                    writer.WriteNull("amountInHomeCurrency");

            if (transaction.HasValidLineItemsOption.IsSet)
                writer.WriteBoolean("hasValidLineItems", transaction.HasValidLineItemsOption.Value!.Value);

            if (transaction.ExternalIdOption.IsSet)
                if (transaction.ExternalIdOption.Value != null)
                    writer.WriteString("externalId", transaction.ExternalId);
                else
                    writer.WriteNull("externalId");

            if (transaction.LinkedTransactionsOption.IsSet)
            {
                writer.WritePropertyName("linkedTransactions");
                JsonSerializer.Serialize(writer, transaction.LinkedTransactions, jsonSerializerOptions);
            }
            if (transaction.ExpenseLinesOption.IsSet)
            {
                writer.WritePropertyName("expenseLines");
                JsonSerializer.Serialize(writer, transaction.ExpenseLines, jsonSerializerOptions);
            }
            if (transaction.ItemLinesOption.IsSet)
            {
                writer.WritePropertyName("itemLines");
                JsonSerializer.Serialize(writer, transaction.ItemLines, jsonSerializerOptions);
            }
            if (transaction.ItemGroupLinesOption.IsSet)
            {
                writer.WritePropertyName("itemGroupLines");
                JsonSerializer.Serialize(writer, transaction.ItemGroupLines, jsonSerializerOptions);
            }
            if (transaction.CustomFieldsOption.IsSet)
            {
                writer.WritePropertyName("customFields");
                JsonSerializer.Serialize(writer, transaction.CustomFields, jsonSerializerOptions);
            }
        }
    }
}
