// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// A reusable request DTO for modifying an existing Statement Charge.  Based on the ChargeMod QBXML type.
    /// </summary>
    public partial class UpdateChargeRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateChargeRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="customerId">(Optional) The ListID or FullName of the customer.</param>
        /// <param name="transactionDate">transactionDate</param>
        /// <param name="refNumber">(Optional) The reference number (e.g., Invoice #).</param>
        /// <param name="itemId">(Optional) The ListID or FullName of the item.</param>
        /// <param name="inventorySiteId">(Optional) The ListID or FullName of the inventory site.</param>
        /// <param name="inventorySiteLocationId">(Optional) The ListID or FullName of the inventory site location.</param>
        /// <param name="quantity">(Optional) Quantity of the item.</param>
        /// <param name="unitOfMeasure">(Optional) Unit of measure.</param>
        /// <param name="overrideUomSetId">(Optional) The ListID or FullName of the override unit of measure set.</param>
        /// <param name="rate">(Optional) The rate or price per unit.</param>
        /// <param name="optionForPriceRuleConflict">(Optional) Strategy for resolving price rule conflicts (Zero, BasePrice).</param>
        /// <param name="amount">(Optional) The total amount of the charge.</param>
        /// <param name="description">(Optional) Description of the charge.</param>
        /// <param name="receivablesAccountId">receivablesAccountId</param>
        /// <param name="classId">(Optional) The ListID or FullName of the class.</param>
        /// <param name="billedDate">(Optional) The date the charge was billed.</param>
        /// <param name="dueDate">(Optional) The due date for the charge.</param>
        /// <param name="overrideItemAccountId">(Optional) The ListID or FullName of the override item account.</param>
        [JsonConstructor]
        public UpdateChargeRequest(string revisionNumber, Option<string?> customerId = default, Option<DateOnly?> transactionDate = default, Option<string?> refNumber = default, Option<string?> itemId = default, Option<string?> inventorySiteId = default, Option<string?> inventorySiteLocationId = default, Option<double?> quantity = default, Option<string?> unitOfMeasure = default, Option<string?> overrideUomSetId = default, Option<double?> rate = default, Option<string?> optionForPriceRuleConflict = default, Option<double?> amount = default, Option<string?> description = default, Option<string?> receivablesAccountId = default, Option<string?> classId = default, Option<DateOnly?> billedDate = default, Option<DateOnly?> dueDate = default, Option<string?> overrideItemAccountId = default)
        {
            RevisionNumber = revisionNumber;
            CustomerIdOption = customerId;
            TransactionDateOption = transactionDate;
            RefNumberOption = refNumber;
            ItemIdOption = itemId;
            InventorySiteIdOption = inventorySiteId;
            InventorySiteLocationIdOption = inventorySiteLocationId;
            QuantityOption = quantity;
            UnitOfMeasureOption = unitOfMeasure;
            OverrideUomSetIdOption = overrideUomSetId;
            RateOption = rate;
            OptionForPriceRuleConflictOption = optionForPriceRuleConflict;
            AmountOption = amount;
            DescriptionOption = description;
            ReceivablesAccountIdOption = receivablesAccountId;
            ClassIdOption = classId;
            BilledDateOption = billedDate;
            DueDateOption = dueDate;
            OverrideItemAccountIdOption = overrideItemAccountId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of CustomerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomerIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the customer.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the customer.</value>
        [JsonPropertyName("customerId")]
        public string? CustomerId { get { return this.CustomerIdOption.Value; } set { this.CustomerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [JsonPropertyName("transactionDate")]
        public DateOnly? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// (Optional) The reference number (e.g., Invoice #).
        /// </summary>
        /// <value>(Optional) The reference number (e.g., Invoice #).</value>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of ItemId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ItemIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the item.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the item.</value>
        [JsonPropertyName("itemId")]
        public string? ItemId { get { return this.ItemIdOption.Value; } set { this.ItemIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InventorySiteId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InventorySiteIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the inventory site.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the inventory site.</value>
        [JsonPropertyName("inventorySiteId")]
        public string? InventorySiteId { get { return this.InventorySiteIdOption.Value; } set { this.InventorySiteIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InventorySiteLocationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InventorySiteLocationIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the inventory site location.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the inventory site location.</value>
        [JsonPropertyName("inventorySiteLocationId")]
        public string? InventorySiteLocationId { get { return this.InventorySiteLocationIdOption.Value; } set { this.InventorySiteLocationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> QuantityOption { get; private set; }

        /// <summary>
        /// (Optional) Quantity of the item.
        /// </summary>
        /// <value>(Optional) Quantity of the item.</value>
        [JsonPropertyName("quantity")]
        public double? Quantity { get { return this.QuantityOption.Value; } set { this.QuantityOption = new(value); } }

        /// <summary>
        /// Used to track the state of UnitOfMeasure
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UnitOfMeasureOption { get; private set; }

        /// <summary>
        /// (Optional) Unit of measure.
        /// </summary>
        /// <value>(Optional) Unit of measure.</value>
        [JsonPropertyName("unitOfMeasure")]
        public string? UnitOfMeasure { get { return this.UnitOfMeasureOption.Value; } set { this.UnitOfMeasureOption = new(value); } }

        /// <summary>
        /// Used to track the state of OverrideUomSetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OverrideUomSetIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the override unit of measure set.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the override unit of measure set.</value>
        [JsonPropertyName("overrideUomSetId")]
        public string? OverrideUomSetId { get { return this.OverrideUomSetIdOption.Value; } set { this.OverrideUomSetIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Rate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> RateOption { get; private set; }

        /// <summary>
        /// (Optional) The rate or price per unit.
        /// </summary>
        /// <value>(Optional) The rate or price per unit.</value>
        [JsonPropertyName("rate")]
        public double? Rate { get { return this.RateOption.Value; } set { this.RateOption = new(value); } }

        /// <summary>
        /// Used to track the state of OptionForPriceRuleConflict
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OptionForPriceRuleConflictOption { get; private set; }

        /// <summary>
        /// (Optional) Strategy for resolving price rule conflicts (Zero, BasePrice).
        /// </summary>
        /// <value>(Optional) Strategy for resolving price rule conflicts (Zero, BasePrice).</value>
        [JsonPropertyName("optionForPriceRuleConflict")]
        public string? OptionForPriceRuleConflict { get { return this.OptionForPriceRuleConflictOption.Value; } set { this.OptionForPriceRuleConflictOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; private set; }

        /// <summary>
        /// (Optional) The total amount of the charge.
        /// </summary>
        /// <value>(Optional) The total amount of the charge.</value>
        [JsonPropertyName("amount")]
        public double? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// (Optional) Description of the charge.
        /// </summary>
        /// <value>(Optional) Description of the charge.</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReceivablesAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReceivablesAccountIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReceivablesAccountId
        /// </summary>
        [JsonPropertyName("receivablesAccountId")]
        public string? ReceivablesAccountId { get { return this.ReceivablesAccountIdOption.Value; } set { this.ReceivablesAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClassId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClassIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the class.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the class.</value>
        [JsonPropertyName("classId")]
        public string? ClassId { get { return this.ClassIdOption.Value; } set { this.ClassIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of BilledDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> BilledDateOption { get; private set; }

        /// <summary>
        /// (Optional) The date the charge was billed.
        /// </summary>
        /// <value>(Optional) The date the charge was billed.</value>
        [JsonPropertyName("billedDate")]
        public DateOnly? BilledDate { get { return this.BilledDateOption.Value; } set { this.BilledDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of DueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> DueDateOption { get; private set; }

        /// <summary>
        /// (Optional) The due date for the charge.
        /// </summary>
        /// <value>(Optional) The due date for the charge.</value>
        [JsonPropertyName("dueDate")]
        public DateOnly? DueDate { get { return this.DueDateOption.Value; } set { this.DueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of OverrideItemAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OverrideItemAccountIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID or FullName of the override item account.
        /// </summary>
        /// <value>(Optional) The ListID or FullName of the override item account.</value>
        [JsonPropertyName("overrideItemAccountId")]
        public string? OverrideItemAccountId { get { return this.OverrideItemAccountIdOption.Value; } set { this.OverrideItemAccountIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateChargeRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("  InventorySiteId: ").Append(InventorySiteId).Append("\n");
            sb.Append("  InventorySiteLocationId: ").Append(InventorySiteLocationId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitOfMeasure: ").Append(UnitOfMeasure).Append("\n");
            sb.Append("  OverrideUomSetId: ").Append(OverrideUomSetId).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  OptionForPriceRuleConflict: ").Append(OptionForPriceRuleConflict).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ReceivablesAccountId: ").Append(ReceivablesAccountId).Append("\n");
            sb.Append("  ClassId: ").Append(ClassId).Append("\n");
            sb.Append("  BilledDate: ").Append(BilledDate).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  OverrideItemAccountId: ").Append(OverrideItemAccountId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RefNumber (string) maxLength
            if (this.RefNumber != null && this.RefNumber.Length > 11)
            {
                yield return new ValidationResult("Invalid value for RefNumber, length must be less than 11.", new [] { "RefNumber" });
            }

            // Quantity (double) minimum
            if (this.QuantityOption.IsSet && this.QuantityOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than 0.", new [] { "Quantity" });
            }

            // UnitOfMeasure (string) maxLength
            if (this.UnitOfMeasure != null && this.UnitOfMeasure.Length > 31)
            {
                yield return new ValidationResult("Invalid value for UnitOfMeasure, length must be less than 31.", new [] { "UnitOfMeasure" });
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 4095)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 4095.", new [] { "Description" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateChargeRequest" />
    /// </summary>
    public class UpdateChargeRequestJsonConverter : JsonConverter<UpdateChargeRequest>
    {
        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize BilledDate
        /// </summary>
        public static string BilledDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize DueDate
        /// </summary>
        public static string DueDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="UpdateChargeRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateChargeRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> customerId = default;
            Option<DateOnly?> transactionDate = default;
            Option<string?> refNumber = default;
            Option<string?> itemId = default;
            Option<string?> inventorySiteId = default;
            Option<string?> inventorySiteLocationId = default;
            Option<double?> quantity = default;
            Option<string?> unitOfMeasure = default;
            Option<string?> overrideUomSetId = default;
            Option<double?> rate = default;
            Option<string?> optionForPriceRuleConflict = default;
            Option<double?> amount = default;
            Option<string?> description = default;
            Option<string?> receivablesAccountId = default;
            Option<string?> classId = default;
            Option<DateOnly?> billedDate = default;
            Option<DateOnly?> dueDate = default;
            Option<string?> overrideItemAccountId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "customerId":
                            customerId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "itemId":
                            itemId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "inventorySiteId":
                            inventorySiteId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "inventorySiteLocationId":
                            inventorySiteLocationId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "quantity":
                            quantity = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "unitOfMeasure":
                            unitOfMeasure = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "overrideUomSetId":
                            overrideUomSetId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "rate":
                            rate = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "optionForPriceRuleConflict":
                            optionForPriceRuleConflict = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "amount":
                            amount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "receivablesAccountId":
                            receivablesAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "classId":
                            classId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "billedDate":
                            billedDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "dueDate":
                            dueDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "overrideItemAccountId":
                            overrideItemAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateChargeRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateChargeRequest.");

            return new UpdateChargeRequest(revisionNumber.Value!, customerId, transactionDate, refNumber, itemId, inventorySiteId, inventorySiteLocationId, quantity, unitOfMeasure, overrideUomSetId, rate, optionForPriceRuleConflict, amount, description, receivablesAccountId, classId, billedDate, dueDate, overrideItemAccountId);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateChargeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateChargeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateChargeRequest updateChargeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateChargeRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateChargeRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateChargeRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateChargeRequest updateChargeRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateChargeRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateChargeRequest.RevisionNumber), "Property is required for class UpdateChargeRequest.");

            writer.WriteString("revisionNumber", updateChargeRequest.RevisionNumber);

            if (updateChargeRequest.CustomerIdOption.IsSet)
                if (updateChargeRequest.CustomerIdOption.Value != null)
                    writer.WriteString("customerId", updateChargeRequest.CustomerId);
                else
                    writer.WriteNull("customerId");

            if (updateChargeRequest.TransactionDateOption.IsSet)
                if (updateChargeRequest.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", updateChargeRequest.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (updateChargeRequest.RefNumberOption.IsSet)
                if (updateChargeRequest.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", updateChargeRequest.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (updateChargeRequest.ItemIdOption.IsSet)
                if (updateChargeRequest.ItemIdOption.Value != null)
                    writer.WriteString("itemId", updateChargeRequest.ItemId);
                else
                    writer.WriteNull("itemId");

            if (updateChargeRequest.InventorySiteIdOption.IsSet)
                if (updateChargeRequest.InventorySiteIdOption.Value != null)
                    writer.WriteString("inventorySiteId", updateChargeRequest.InventorySiteId);
                else
                    writer.WriteNull("inventorySiteId");

            if (updateChargeRequest.InventorySiteLocationIdOption.IsSet)
                if (updateChargeRequest.InventorySiteLocationIdOption.Value != null)
                    writer.WriteString("inventorySiteLocationId", updateChargeRequest.InventorySiteLocationId);
                else
                    writer.WriteNull("inventorySiteLocationId");

            if (updateChargeRequest.QuantityOption.IsSet)
                if (updateChargeRequest.QuantityOption.Value != null)
                    writer.WriteNumber("quantity", updateChargeRequest.QuantityOption.Value!.Value);
                else
                    writer.WriteNull("quantity");

            if (updateChargeRequest.UnitOfMeasureOption.IsSet)
                if (updateChargeRequest.UnitOfMeasureOption.Value != null)
                    writer.WriteString("unitOfMeasure", updateChargeRequest.UnitOfMeasure);
                else
                    writer.WriteNull("unitOfMeasure");

            if (updateChargeRequest.OverrideUomSetIdOption.IsSet)
                if (updateChargeRequest.OverrideUomSetIdOption.Value != null)
                    writer.WriteString("overrideUomSetId", updateChargeRequest.OverrideUomSetId);
                else
                    writer.WriteNull("overrideUomSetId");

            if (updateChargeRequest.RateOption.IsSet)
                if (updateChargeRequest.RateOption.Value != null)
                    writer.WriteNumber("rate", updateChargeRequest.RateOption.Value!.Value);
                else
                    writer.WriteNull("rate");

            if (updateChargeRequest.OptionForPriceRuleConflictOption.IsSet)
                if (updateChargeRequest.OptionForPriceRuleConflictOption.Value != null)
                    writer.WriteString("optionForPriceRuleConflict", updateChargeRequest.OptionForPriceRuleConflict);
                else
                    writer.WriteNull("optionForPriceRuleConflict");

            if (updateChargeRequest.AmountOption.IsSet)
                if (updateChargeRequest.AmountOption.Value != null)
                    writer.WriteNumber("amount", updateChargeRequest.AmountOption.Value!.Value);
                else
                    writer.WriteNull("amount");

            if (updateChargeRequest.DescriptionOption.IsSet)
                if (updateChargeRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", updateChargeRequest.Description);
                else
                    writer.WriteNull("description");

            if (updateChargeRequest.ReceivablesAccountIdOption.IsSet)
                if (updateChargeRequest.ReceivablesAccountIdOption.Value != null)
                    writer.WriteString("receivablesAccountId", updateChargeRequest.ReceivablesAccountId);
                else
                    writer.WriteNull("receivablesAccountId");

            if (updateChargeRequest.ClassIdOption.IsSet)
                if (updateChargeRequest.ClassIdOption.Value != null)
                    writer.WriteString("classId", updateChargeRequest.ClassId);
                else
                    writer.WriteNull("classId");

            if (updateChargeRequest.BilledDateOption.IsSet)
                if (updateChargeRequest.BilledDateOption.Value != null)
                    writer.WriteString("billedDate", updateChargeRequest.BilledDateOption.Value!.Value.ToString(BilledDateFormat));
                else
                    writer.WriteNull("billedDate");

            if (updateChargeRequest.DueDateOption.IsSet)
                if (updateChargeRequest.DueDateOption.Value != null)
                    writer.WriteString("dueDate", updateChargeRequest.DueDateOption.Value!.Value.ToString(DueDateFormat));
                else
                    writer.WriteNull("dueDate");

            if (updateChargeRequest.OverrideItemAccountIdOption.IsSet)
                if (updateChargeRequest.OverrideItemAccountIdOption.Value != null)
                    writer.WriteString("overrideItemAccountId", updateChargeRequest.OverrideItemAccountId);
                else
                    writer.WriteNull("overrideItemAccountId");
        }
    }
}
