// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Request model for updating an ItemNonInventory.
    /// </summary>
    public partial class UpdateItemNonInventoryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateItemNonInventoryRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="name">name</param>
        /// <param name="barcode">barcode</param>
        /// <param name="isActive">isActive</param>
        /// <param name="classId">classId</param>
        /// <param name="parentId">parentId</param>
        /// <param name="sku">sku</param>
        /// <param name="unitOfMeasureSetId">unitOfMeasureSetId</param>
        /// <param name="isTaxIncluded">isTaxIncluded</param>
        /// <param name="salesTaxCodeId">salesTaxCodeId</param>
        /// <param name="salesOrPurchaseDetails">salesOrPurchaseDetails</param>
        /// <param name="salesAndPurchaseDetails">salesAndPurchaseDetails</param>
        [JsonConstructor]
        public UpdateItemNonInventoryRequest(string revisionNumber, Option<string?> name = default, Option<BarCodeRequest?> barcode = default, Option<bool?> isActive = default, Option<string?> classId = default, Option<string?> parentId = default, Option<string?> sku = default, Option<string?> unitOfMeasureSetId = default, Option<bool?> isTaxIncluded = default, Option<string?> salesTaxCodeId = default, Option<ItemNonInventorySalesOrPurchaseDetailsRequest?> salesOrPurchaseDetails = default, Option<ItemNonInventorySalesAndPurchaseDetailsRequest?> salesAndPurchaseDetails = default)
        {
            RevisionNumber = revisionNumber;
            NameOption = name;
            BarcodeOption = barcode;
            IsActiveOption = isActive;
            ClassIdOption = classId;
            ParentIdOption = parentId;
            SkuOption = sku;
            UnitOfMeasureSetIdOption = unitOfMeasureSetId;
            IsTaxIncludedOption = isTaxIncluded;
            SalesTaxCodeIdOption = salesTaxCodeId;
            SalesOrPurchaseDetailsOption = salesOrPurchaseDetails;
            SalesAndPurchaseDetailsOption = salesAndPurchaseDetails;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Barcode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BarCodeRequest?> BarcodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Barcode
        /// </summary>
        [JsonPropertyName("barcode")]
        public BarCodeRequest? Barcode { get { return this.BarcodeOption.Value; } set { this.BarcodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClassId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClassIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ClassId
        /// </summary>
        [JsonPropertyName("classId")]
        public string? ClassId { get { return this.ClassIdOption.Value; } set { this.ClassIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ParentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [JsonPropertyName("parentId")]
        public string? ParentId { get { return this.ParentIdOption.Value; } set { this.ParentIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sku
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SkuOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sku
        /// </summary>
        [JsonPropertyName("sku")]
        public string? Sku { get { return this.SkuOption.Value; } set { this.SkuOption = new(value); } }

        /// <summary>
        /// Used to track the state of UnitOfMeasureSetId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UnitOfMeasureSetIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UnitOfMeasureSetId
        /// </summary>
        [JsonPropertyName("unitOfMeasureSetId")]
        public string? UnitOfMeasureSetId { get { return this.UnitOfMeasureSetIdOption.Value; } set { this.UnitOfMeasureSetIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsTaxIncluded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsTaxIncludedOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsTaxIncluded
        /// </summary>
        [JsonPropertyName("isTaxIncluded")]
        public bool? IsTaxIncluded { get { return this.IsTaxIncludedOption.Value; } set { this.IsTaxIncludedOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesTaxCodeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesTaxCodeIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesTaxCodeId
        /// </summary>
        [JsonPropertyName("salesTaxCodeId")]
        public string? SalesTaxCodeId { get { return this.SalesTaxCodeIdOption.Value; } set { this.SalesTaxCodeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesOrPurchaseDetails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ItemNonInventorySalesOrPurchaseDetailsRequest?> SalesOrPurchaseDetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesOrPurchaseDetails
        /// </summary>
        [JsonPropertyName("salesOrPurchaseDetails")]
        public ItemNonInventorySalesOrPurchaseDetailsRequest? SalesOrPurchaseDetails { get { return this.SalesOrPurchaseDetailsOption.Value; } set { this.SalesOrPurchaseDetailsOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesAndPurchaseDetails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ItemNonInventorySalesAndPurchaseDetailsRequest?> SalesAndPurchaseDetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesAndPurchaseDetails
        /// </summary>
        [JsonPropertyName("salesAndPurchaseDetails")]
        public ItemNonInventorySalesAndPurchaseDetailsRequest? SalesAndPurchaseDetails { get { return this.SalesAndPurchaseDetailsOption.Value; } set { this.SalesAndPurchaseDetailsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateItemNonInventoryRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Barcode: ").Append(Barcode).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ClassId: ").Append(ClassId).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  UnitOfMeasureSetId: ").Append(UnitOfMeasureSetId).Append("\n");
            sb.Append("  IsTaxIncluded: ").Append(IsTaxIncluded).Append("\n");
            sb.Append("  SalesTaxCodeId: ").Append(SalesTaxCodeId).Append("\n");
            sb.Append("  SalesOrPurchaseDetails: ").Append(SalesOrPurchaseDetails).Append("\n");
            sb.Append("  SalesAndPurchaseDetails: ").Append(SalesAndPurchaseDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 31)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 31.", new [] { "Name" });
            }

            // ParentId (string) maxLength
            if (this.ParentId != null && this.ParentId.Length > 159)
            {
                yield return new ValidationResult("Invalid value for ParentId, length must be less than 159.", new [] { "ParentId" });
            }

            // Sku (string) maxLength
            if (this.Sku != null && this.Sku.Length > 31)
            {
                yield return new ValidationResult("Invalid value for Sku, length must be less than 31.", new [] { "Sku" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateItemNonInventoryRequest" />
    /// </summary>
    public class UpdateItemNonInventoryRequestJsonConverter : JsonConverter<UpdateItemNonInventoryRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateItemNonInventoryRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateItemNonInventoryRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> name = default;
            Option<BarCodeRequest?> barcode = default;
            Option<bool?> isActive = default;
            Option<string?> classId = default;
            Option<string?> parentId = default;
            Option<string?> sku = default;
            Option<string?> unitOfMeasureSetId = default;
            Option<bool?> isTaxIncluded = default;
            Option<string?> salesTaxCodeId = default;
            Option<ItemNonInventorySalesOrPurchaseDetailsRequest?> salesOrPurchaseDetails = default;
            Option<ItemNonInventorySalesAndPurchaseDetailsRequest?> salesAndPurchaseDetails = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "barcode":
                            barcode = new Option<BarCodeRequest?>(JsonSerializer.Deserialize<BarCodeRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "classId":
                            classId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "parentId":
                            parentId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sku":
                            sku = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "unitOfMeasureSetId":
                            unitOfMeasureSetId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isTaxIncluded":
                            isTaxIncluded = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "salesTaxCodeId":
                            salesTaxCodeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "salesOrPurchaseDetails":
                            salesOrPurchaseDetails = new Option<ItemNonInventorySalesOrPurchaseDetailsRequest?>(JsonSerializer.Deserialize<ItemNonInventorySalesOrPurchaseDetailsRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "salesAndPurchaseDetails":
                            salesAndPurchaseDetails = new Option<ItemNonInventorySalesAndPurchaseDetailsRequest?>(JsonSerializer.Deserialize<ItemNonInventorySalesAndPurchaseDetailsRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateItemNonInventoryRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateItemNonInventoryRequest.");

            return new UpdateItemNonInventoryRequest(revisionNumber.Value!, name, barcode, isActive, classId, parentId, sku, unitOfMeasureSetId, isTaxIncluded, salesTaxCodeId, salesOrPurchaseDetails, salesAndPurchaseDetails);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateItemNonInventoryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateItemNonInventoryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateItemNonInventoryRequest updateItemNonInventoryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateItemNonInventoryRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateItemNonInventoryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateItemNonInventoryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateItemNonInventoryRequest updateItemNonInventoryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateItemNonInventoryRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateItemNonInventoryRequest.RevisionNumber), "Property is required for class UpdateItemNonInventoryRequest.");

            writer.WriteString("revisionNumber", updateItemNonInventoryRequest.RevisionNumber);

            if (updateItemNonInventoryRequest.NameOption.IsSet)
                if (updateItemNonInventoryRequest.NameOption.Value != null)
                    writer.WriteString("name", updateItemNonInventoryRequest.Name);
                else
                    writer.WriteNull("name");

            if (updateItemNonInventoryRequest.BarcodeOption.IsSet)
                if (updateItemNonInventoryRequest.BarcodeOption.Value != null)
                {
                    writer.WritePropertyName("barcode");
                    JsonSerializer.Serialize(writer, updateItemNonInventoryRequest.Barcode, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("barcode");
            if (updateItemNonInventoryRequest.IsActiveOption.IsSet)
                if (updateItemNonInventoryRequest.IsActiveOption.Value != null)
                    writer.WriteBoolean("isActive", updateItemNonInventoryRequest.IsActiveOption.Value!.Value);
                else
                    writer.WriteNull("isActive");

            if (updateItemNonInventoryRequest.ClassIdOption.IsSet)
                if (updateItemNonInventoryRequest.ClassIdOption.Value != null)
                    writer.WriteString("classId", updateItemNonInventoryRequest.ClassId);
                else
                    writer.WriteNull("classId");

            if (updateItemNonInventoryRequest.ParentIdOption.IsSet)
                if (updateItemNonInventoryRequest.ParentIdOption.Value != null)
                    writer.WriteString("parentId", updateItemNonInventoryRequest.ParentId);
                else
                    writer.WriteNull("parentId");

            if (updateItemNonInventoryRequest.SkuOption.IsSet)
                if (updateItemNonInventoryRequest.SkuOption.Value != null)
                    writer.WriteString("sku", updateItemNonInventoryRequest.Sku);
                else
                    writer.WriteNull("sku");

            if (updateItemNonInventoryRequest.UnitOfMeasureSetIdOption.IsSet)
                if (updateItemNonInventoryRequest.UnitOfMeasureSetIdOption.Value != null)
                    writer.WriteString("unitOfMeasureSetId", updateItemNonInventoryRequest.UnitOfMeasureSetId);
                else
                    writer.WriteNull("unitOfMeasureSetId");

            if (updateItemNonInventoryRequest.IsTaxIncludedOption.IsSet)
                if (updateItemNonInventoryRequest.IsTaxIncludedOption.Value != null)
                    writer.WriteBoolean("isTaxIncluded", updateItemNonInventoryRequest.IsTaxIncludedOption.Value!.Value);
                else
                    writer.WriteNull("isTaxIncluded");

            if (updateItemNonInventoryRequest.SalesTaxCodeIdOption.IsSet)
                if (updateItemNonInventoryRequest.SalesTaxCodeIdOption.Value != null)
                    writer.WriteString("salesTaxCodeId", updateItemNonInventoryRequest.SalesTaxCodeId);
                else
                    writer.WriteNull("salesTaxCodeId");

            if (updateItemNonInventoryRequest.SalesOrPurchaseDetailsOption.IsSet)
                if (updateItemNonInventoryRequest.SalesOrPurchaseDetailsOption.Value != null)
                {
                    writer.WritePropertyName("salesOrPurchaseDetails");
                    JsonSerializer.Serialize(writer, updateItemNonInventoryRequest.SalesOrPurchaseDetails, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("salesOrPurchaseDetails");
            if (updateItemNonInventoryRequest.SalesAndPurchaseDetailsOption.IsSet)
                if (updateItemNonInventoryRequest.SalesAndPurchaseDetailsOption.Value != null)
                {
                    writer.WritePropertyName("salesAndPurchaseDetails");
                    JsonSerializer.Serialize(writer, updateItemNonInventoryRequest.SalesAndPurchaseDetails, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("salesAndPurchaseDetails");
        }
    }
}
