// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Request model for updating an existing Check transaction used to pay bills.
    /// </summary>
    public partial class UpdateCheckBillPaymentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCheckBillPaymentRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="payeeId">payeeId</param>
        /// <param name="transactionDate">transactionDate</param>
        /// <param name="memo">(Optional) A memo for the check. Max length: 4095 characters.</param>
        /// <param name="refNumber">(Optional) The reference number (e.g., Check #). Max length: 11 characters.</param>
        /// <param name="bankAccountId">(Optional) The ListID of the bank account. Max length: 159 characters.</param>
        /// <param name="payablesAccountId">(Optional) The ListID of the Accounts Payable account. Max length: 159 characters.</param>
        /// <param name="amount">(Optional) The total amount of the check.</param>
        /// <param name="currencyId">(Optional) The ListID of the currency. Max length: 64 characters.</param>
        /// <param name="exchangeRate">(Optional) The currency exchange rate.</param>
        /// <param name="amountInHomeCurrency">(Optional) The amount in the home currency.</param>
        /// <param name="isQueuedForPrint">isQueuedForPrint</param>
        /// <param name="appliedToTransactions">appliedToTransactions</param>
        [JsonConstructor]
        public UpdateCheckBillPaymentRequest(string revisionNumber, Option<string?> payeeId = default, Option<DateOnly?> transactionDate = default, Option<string?> memo = default, Option<string?> refNumber = default, Option<string?> bankAccountId = default, Option<string?> payablesAccountId = default, Option<double?> amount = default, Option<string?> currencyId = default, Option<double?> exchangeRate = default, Option<double?> amountInHomeCurrency = default, Option<bool?> isQueuedForPrint = default, Option<List<AppliedToTransactionRequest>?> appliedToTransactions = default)
        {
            RevisionNumber = revisionNumber;
            PayeeIdOption = payeeId;
            TransactionDateOption = transactionDate;
            MemoOption = memo;
            RefNumberOption = refNumber;
            BankAccountIdOption = bankAccountId;
            PayablesAccountIdOption = payablesAccountId;
            AmountOption = amount;
            CurrencyIdOption = currencyId;
            ExchangeRateOption = exchangeRate;
            AmountInHomeCurrencyOption = amountInHomeCurrency;
            IsQueuedForPrintOption = isQueuedForPrint;
            AppliedToTransactionsOption = appliedToTransactions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of PayeeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PayeeIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PayeeId
        /// </summary>
        [JsonPropertyName("payeeId")]
        public string? PayeeId { get { return this.PayeeIdOption.Value; } set { this.PayeeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [JsonPropertyName("transactionDate")]
        public DateOnly? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Memo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MemoOption { get; private set; }

        /// <summary>
        /// (Optional) A memo for the check. Max length: 4095 characters.
        /// </summary>
        /// <value>(Optional) A memo for the check. Max length: 4095 characters.</value>
        [JsonPropertyName("memo")]
        public string? Memo { get { return this.MemoOption.Value; } set { this.MemoOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// (Optional) The reference number (e.g., Check #). Max length: 11 characters.
        /// </summary>
        /// <value>(Optional) The reference number (e.g., Check #). Max length: 11 characters.</value>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of BankAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BankAccountIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID of the bank account. Max length: 159 characters.
        /// </summary>
        /// <value>(Optional) The ListID of the bank account. Max length: 159 characters.</value>
        [JsonPropertyName("bankAccountId")]
        public string? BankAccountId { get { return this.BankAccountIdOption.Value; } set { this.BankAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of PayablesAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PayablesAccountIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID of the Accounts Payable account. Max length: 159 characters.
        /// </summary>
        /// <value>(Optional) The ListID of the Accounts Payable account. Max length: 159 characters.</value>
        [JsonPropertyName("payablesAccountId")]
        public string? PayablesAccountId { get { return this.PayablesAccountIdOption.Value; } set { this.PayablesAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; private set; }

        /// <summary>
        /// (Optional) The total amount of the check.
        /// </summary>
        /// <value>(Optional) The total amount of the check.</value>
        [JsonPropertyName("amount")]
        public double? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of CurrencyId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CurrencyIdOption { get; private set; }

        /// <summary>
        /// (Optional) The ListID of the currency. Max length: 64 characters.
        /// </summary>
        /// <value>(Optional) The ListID of the currency. Max length: 64 characters.</value>
        [JsonPropertyName("currencyId")]
        public string? CurrencyId { get { return this.CurrencyIdOption.Value; } set { this.CurrencyIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ExchangeRateOption { get; private set; }

        /// <summary>
        /// (Optional) The currency exchange rate.
        /// </summary>
        /// <value>(Optional) The currency exchange rate.</value>
        [JsonPropertyName("exchangeRate")]
        public double? ExchangeRate { get { return this.ExchangeRateOption.Value; } set { this.ExchangeRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of AmountInHomeCurrency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountInHomeCurrencyOption { get; private set; }

        /// <summary>
        /// (Optional) The amount in the home currency.
        /// </summary>
        /// <value>(Optional) The amount in the home currency.</value>
        [JsonPropertyName("amountInHomeCurrency")]
        public double? AmountInHomeCurrency { get { return this.AmountInHomeCurrencyOption.Value; } set { this.AmountInHomeCurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsQueuedForPrint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsQueuedForPrintOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsQueuedForPrint
        /// </summary>
        [JsonPropertyName("isQueuedForPrint")]
        public bool? IsQueuedForPrint { get { return this.IsQueuedForPrintOption.Value; } set { this.IsQueuedForPrintOption = new(value); } }

        /// <summary>
        /// Used to track the state of AppliedToTransactions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<AppliedToTransactionRequest>?> AppliedToTransactionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AppliedToTransactions
        /// </summary>
        [JsonPropertyName("appliedToTransactions")]
        public List<AppliedToTransactionRequest>? AppliedToTransactions { get { return this.AppliedToTransactionsOption.Value; } set { this.AppliedToTransactionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCheckBillPaymentRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  PayeeId: ").Append(PayeeId).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  BankAccountId: ").Append(BankAccountId).Append("\n");
            sb.Append("  PayablesAccountId: ").Append(PayablesAccountId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  CurrencyId: ").Append(CurrencyId).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  AmountInHomeCurrency: ").Append(AmountInHomeCurrency).Append("\n");
            sb.Append("  IsQueuedForPrint: ").Append(IsQueuedForPrint).Append("\n");
            sb.Append("  AppliedToTransactions: ").Append(AppliedToTransactions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PayeeId (string) maxLength
            if (this.PayeeId != null && this.PayeeId.Length > 209)
            {
                yield return new ValidationResult("Invalid value for PayeeId, length must be less than 209.", new [] { "PayeeId" });
            }

            // Memo (string) maxLength
            if (this.Memo != null && this.Memo.Length > 4095)
            {
                yield return new ValidationResult("Invalid value for Memo, length must be less than 4095.", new [] { "Memo" });
            }

            // RefNumber (string) maxLength
            if (this.RefNumber != null && this.RefNumber.Length > 11)
            {
                yield return new ValidationResult("Invalid value for RefNumber, length must be less than 11.", new [] { "RefNumber" });
            }

            // BankAccountId (string) maxLength
            if (this.BankAccountId != null && this.BankAccountId.Length > 159)
            {
                yield return new ValidationResult("Invalid value for BankAccountId, length must be less than 159.", new [] { "BankAccountId" });
            }

            // PayablesAccountId (string) maxLength
            if (this.PayablesAccountId != null && this.PayablesAccountId.Length > 159)
            {
                yield return new ValidationResult("Invalid value for PayablesAccountId, length must be less than 159.", new [] { "PayablesAccountId" });
            }

            // Amount (double) minimum
            if (this.AmountOption.IsSet && this.AmountOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            // CurrencyId (string) maxLength
            if (this.CurrencyId != null && this.CurrencyId.Length > 64)
            {
                yield return new ValidationResult("Invalid value for CurrencyId, length must be less than 64.", new [] { "CurrencyId" });
            }

            // ExchangeRate (double) minimum
            if (this.ExchangeRateOption.IsSet && this.ExchangeRateOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for ExchangeRate, must be a value greater than 0.", new [] { "ExchangeRate" });
            }

            // AmountInHomeCurrency (double) minimum
            if (this.AmountInHomeCurrencyOption.IsSet && this.AmountInHomeCurrencyOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for AmountInHomeCurrency, must be a value greater than or equal to 0.", new [] { "AmountInHomeCurrency" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateCheckBillPaymentRequest" />
    /// </summary>
    public class UpdateCheckBillPaymentRequestJsonConverter : JsonConverter<UpdateCheckBillPaymentRequest>
    {
        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="UpdateCheckBillPaymentRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateCheckBillPaymentRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> payeeId = default;
            Option<DateOnly?> transactionDate = default;
            Option<string?> memo = default;
            Option<string?> refNumber = default;
            Option<string?> bankAccountId = default;
            Option<string?> payablesAccountId = default;
            Option<double?> amount = default;
            Option<string?> currencyId = default;
            Option<double?> exchangeRate = default;
            Option<double?> amountInHomeCurrency = default;
            Option<bool?> isQueuedForPrint = default;
            Option<List<AppliedToTransactionRequest>?> appliedToTransactions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "payeeId":
                            payeeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "memo":
                            memo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "bankAccountId":
                            bankAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "payablesAccountId":
                            payablesAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "amount":
                            amount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "currencyId":
                            currencyId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exchangeRate":
                            exchangeRate = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "amountInHomeCurrency":
                            amountInHomeCurrency = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "isQueuedForPrint":
                            isQueuedForPrint = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "appliedToTransactions":
                            appliedToTransactions = new Option<List<AppliedToTransactionRequest>?>(JsonSerializer.Deserialize<List<AppliedToTransactionRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateCheckBillPaymentRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateCheckBillPaymentRequest.");

            if (appliedToTransactions.IsSet && appliedToTransactions.Value == null)
                throw new ArgumentNullException(nameof(appliedToTransactions), "Property is not nullable for class UpdateCheckBillPaymentRequest.");

            return new UpdateCheckBillPaymentRequest(revisionNumber.Value!, payeeId, transactionDate, memo, refNumber, bankAccountId, payablesAccountId, amount, currencyId, exchangeRate, amountInHomeCurrency, isQueuedForPrint, appliedToTransactions);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateCheckBillPaymentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCheckBillPaymentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateCheckBillPaymentRequest updateCheckBillPaymentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateCheckBillPaymentRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateCheckBillPaymentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCheckBillPaymentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateCheckBillPaymentRequest updateCheckBillPaymentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateCheckBillPaymentRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateCheckBillPaymentRequest.RevisionNumber), "Property is required for class UpdateCheckBillPaymentRequest.");

            if (updateCheckBillPaymentRequest.AppliedToTransactionsOption.IsSet && updateCheckBillPaymentRequest.AppliedToTransactions == null)
                throw new ArgumentNullException(nameof(updateCheckBillPaymentRequest.AppliedToTransactions), "Property is required for class UpdateCheckBillPaymentRequest.");

            writer.WriteString("revisionNumber", updateCheckBillPaymentRequest.RevisionNumber);

            if (updateCheckBillPaymentRequest.PayeeIdOption.IsSet)
                if (updateCheckBillPaymentRequest.PayeeIdOption.Value != null)
                    writer.WriteString("payeeId", updateCheckBillPaymentRequest.PayeeId);
                else
                    writer.WriteNull("payeeId");

            if (updateCheckBillPaymentRequest.TransactionDateOption.IsSet)
                if (updateCheckBillPaymentRequest.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", updateCheckBillPaymentRequest.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (updateCheckBillPaymentRequest.MemoOption.IsSet)
                if (updateCheckBillPaymentRequest.MemoOption.Value != null)
                    writer.WriteString("memo", updateCheckBillPaymentRequest.Memo);
                else
                    writer.WriteNull("memo");

            if (updateCheckBillPaymentRequest.RefNumberOption.IsSet)
                if (updateCheckBillPaymentRequest.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", updateCheckBillPaymentRequest.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (updateCheckBillPaymentRequest.BankAccountIdOption.IsSet)
                if (updateCheckBillPaymentRequest.BankAccountIdOption.Value != null)
                    writer.WriteString("bankAccountId", updateCheckBillPaymentRequest.BankAccountId);
                else
                    writer.WriteNull("bankAccountId");

            if (updateCheckBillPaymentRequest.PayablesAccountIdOption.IsSet)
                if (updateCheckBillPaymentRequest.PayablesAccountIdOption.Value != null)
                    writer.WriteString("payablesAccountId", updateCheckBillPaymentRequest.PayablesAccountId);
                else
                    writer.WriteNull("payablesAccountId");

            if (updateCheckBillPaymentRequest.AmountOption.IsSet)
                if (updateCheckBillPaymentRequest.AmountOption.Value != null)
                    writer.WriteNumber("amount", updateCheckBillPaymentRequest.AmountOption.Value!.Value);
                else
                    writer.WriteNull("amount");

            if (updateCheckBillPaymentRequest.CurrencyIdOption.IsSet)
                if (updateCheckBillPaymentRequest.CurrencyIdOption.Value != null)
                    writer.WriteString("currencyId", updateCheckBillPaymentRequest.CurrencyId);
                else
                    writer.WriteNull("currencyId");

            if (updateCheckBillPaymentRequest.ExchangeRateOption.IsSet)
                if (updateCheckBillPaymentRequest.ExchangeRateOption.Value != null)
                    writer.WriteNumber("exchangeRate", updateCheckBillPaymentRequest.ExchangeRateOption.Value!.Value);
                else
                    writer.WriteNull("exchangeRate");

            if (updateCheckBillPaymentRequest.AmountInHomeCurrencyOption.IsSet)
                if (updateCheckBillPaymentRequest.AmountInHomeCurrencyOption.Value != null)
                    writer.WriteNumber("amountInHomeCurrency", updateCheckBillPaymentRequest.AmountInHomeCurrencyOption.Value!.Value);
                else
                    writer.WriteNull("amountInHomeCurrency");

            if (updateCheckBillPaymentRequest.IsQueuedForPrintOption.IsSet)
                if (updateCheckBillPaymentRequest.IsQueuedForPrintOption.Value != null)
                    writer.WriteBoolean("isQueuedForPrint", updateCheckBillPaymentRequest.IsQueuedForPrintOption.Value!.Value);
                else
                    writer.WriteNull("isQueuedForPrint");

            if (updateCheckBillPaymentRequest.AppliedToTransactionsOption.IsSet)
            {
                writer.WritePropertyName("appliedToTransactions");
                JsonSerializer.Serialize(writer, updateCheckBillPaymentRequest.AppliedToTransactions, jsonSerializerOptions);
            }
        }
    }
}
