// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Request model for updating an existing invoice.  Matches InvoiceModRq in QBXML.
    /// </summary>
    public partial class UpdateInvoiceRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateInvoiceRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="customerId">Customer ListID (optional for updates).</param>
        /// <param name="classId">Class ListID.</param>
        /// <param name="receivablesAccountId">receivablesAccountId</param>
        /// <param name="templateId">Template ListID.</param>
        /// <param name="transactionDate">transactionDate</param>
        /// <param name="refNumber">Reference number for the invoice.</param>
        /// <param name="billingAddress">billingAddress</param>
        /// <param name="shippingAddress">shippingAddress</param>
        /// <param name="isPending">isPending</param>
        /// <param name="purchaseOrderNumber">purchaseOrderNumber</param>
        /// <param name="termsId">Terms ListID.</param>
        /// <param name="dueDate">Due date for the invoice.</param>
        /// <param name="salesRepresentativeId">salesRepresentativeId</param>
        /// <param name="shipmentOrigin">shipmentOrigin</param>
        /// <param name="shippingDate">shippingDate</param>
        /// <param name="shippingMethodId">shippingMethodId</param>
        /// <param name="salesTaxItemId">salesTaxItemId</param>
        /// <param name="memo">Memo/description for the invoice.</param>
        /// <param name="otherCustomField">otherCustomField</param>
        /// <param name="customerMessageId">customerMessageId</param>
        /// <param name="isQueuedForPrint">isQueuedForPrint</param>
        /// <param name="isQueuedForEmail">isQueuedForEmail</param>
        /// <param name="isTaxIncluded">isTaxIncluded</param>
        /// <param name="salesTaxCodeId">salesTaxCodeId</param>
        /// <param name="exchangeRate">exchangeRate</param>
        /// <param name="applyCredits">applyCredits</param>
        /// <param name="lines">lines</param>
        /// <param name="lineGroups">lineGroups</param>
        [JsonConstructor]
        public UpdateInvoiceRequest(string revisionNumber, Option<string?> customerId = default, Option<string?> classId = default, Option<string?> receivablesAccountId = default, Option<string?> templateId = default, Option<DateOnly?> transactionDate = default, Option<string?> refNumber = default, Option<AddressRequest?> billingAddress = default, Option<AddressRequest?> shippingAddress = default, Option<bool?> isPending = default, Option<string?> purchaseOrderNumber = default, Option<string?> termsId = default, Option<DateOnly?> dueDate = default, Option<string?> salesRepresentativeId = default, Option<string?> shipmentOrigin = default, Option<DateOnly?> shippingDate = default, Option<string?> shippingMethodId = default, Option<string?> salesTaxItemId = default, Option<string?> memo = default, Option<string?> otherCustomField = default, Option<string?> customerMessageId = default, Option<bool?> isQueuedForPrint = default, Option<bool?> isQueuedForEmail = default, Option<bool?> isTaxIncluded = default, Option<string?> salesTaxCodeId = default, Option<float?> exchangeRate = default, Option<List<CreateSetCreditRequest>?> applyCredits = default, Option<List<UpdateItemLineRequest>?> lines = default, Option<List<UpdateItemGroupLineRequest>?> lineGroups = default)
        {
            RevisionNumber = revisionNumber;
            CustomerIdOption = customerId;
            ClassIdOption = classId;
            ReceivablesAccountIdOption = receivablesAccountId;
            TemplateIdOption = templateId;
            TransactionDateOption = transactionDate;
            RefNumberOption = refNumber;
            BillingAddressOption = billingAddress;
            ShippingAddressOption = shippingAddress;
            IsPendingOption = isPending;
            PurchaseOrderNumberOption = purchaseOrderNumber;
            TermsIdOption = termsId;
            DueDateOption = dueDate;
            SalesRepresentativeIdOption = salesRepresentativeId;
            ShipmentOriginOption = shipmentOrigin;
            ShippingDateOption = shippingDate;
            ShippingMethodIdOption = shippingMethodId;
            SalesTaxItemIdOption = salesTaxItemId;
            MemoOption = memo;
            OtherCustomFieldOption = otherCustomField;
            CustomerMessageIdOption = customerMessageId;
            IsQueuedForPrintOption = isQueuedForPrint;
            IsQueuedForEmailOption = isQueuedForEmail;
            IsTaxIncludedOption = isTaxIncluded;
            SalesTaxCodeIdOption = salesTaxCodeId;
            ExchangeRateOption = exchangeRate;
            ApplyCreditsOption = applyCredits;
            LinesOption = lines;
            LineGroupsOption = lineGroups;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of CustomerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomerIdOption { get; private set; }

        /// <summary>
        /// Customer ListID (optional for updates).
        /// </summary>
        /// <value>Customer ListID (optional for updates).</value>
        [JsonPropertyName("customerId")]
        public string? CustomerId { get { return this.CustomerIdOption.Value; } set { this.CustomerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClassId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ClassIdOption { get; private set; }

        /// <summary>
        /// Class ListID.
        /// </summary>
        /// <value>Class ListID.</value>
        [JsonPropertyName("classId")]
        public string? ClassId { get { return this.ClassIdOption.Value; } set { this.ClassIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReceivablesAccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ReceivablesAccountIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReceivablesAccountId
        /// </summary>
        [JsonPropertyName("receivablesAccountId")]
        public string? ReceivablesAccountId { get { return this.ReceivablesAccountIdOption.Value; } set { this.ReceivablesAccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TemplateIdOption { get; private set; }

        /// <summary>
        /// Template ListID.
        /// </summary>
        /// <value>Template ListID.</value>
        [JsonPropertyName("templateId")]
        public string? TemplateId { get { return this.TemplateIdOption.Value; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TransactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionDate
        /// </summary>
        [JsonPropertyName("transactionDate")]
        public DateOnly? TransactionDate { get { return this.TransactionDateOption.Value; } set { this.TransactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// Reference number for the invoice.
        /// </summary>
        /// <value>Reference number for the invoice.</value>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of BillingAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AddressRequest?> BillingAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets BillingAddress
        /// </summary>
        [JsonPropertyName("billingAddress")]
        public AddressRequest? BillingAddress { get { return this.BillingAddressOption.Value; } set { this.BillingAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShippingAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AddressRequest?> ShippingAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShippingAddress
        /// </summary>
        [JsonPropertyName("shippingAddress")]
        public AddressRequest? ShippingAddress { get { return this.ShippingAddressOption.Value; } set { this.ShippingAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsPending
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsPendingOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsPending
        /// </summary>
        [JsonPropertyName("isPending")]
        public bool? IsPending { get { return this.IsPendingOption.Value; } set { this.IsPendingOption = new(value); } }

        /// <summary>
        /// Used to track the state of PurchaseOrderNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PurchaseOrderNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets PurchaseOrderNumber
        /// </summary>
        [JsonPropertyName("purchaseOrderNumber")]
        public string? PurchaseOrderNumber { get { return this.PurchaseOrderNumberOption.Value; } set { this.PurchaseOrderNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of TermsId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TermsIdOption { get; private set; }

        /// <summary>
        /// Terms ListID.
        /// </summary>
        /// <value>Terms ListID.</value>
        [JsonPropertyName("termsId")]
        public string? TermsId { get { return this.TermsIdOption.Value; } set { this.TermsIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of DueDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> DueDateOption { get; private set; }

        /// <summary>
        /// Due date for the invoice.
        /// </summary>
        /// <value>Due date for the invoice.</value>
        [JsonPropertyName("dueDate")]
        public DateOnly? DueDate { get { return this.DueDateOption.Value; } set { this.DueDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesRepresentativeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesRepresentativeIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesRepresentativeId
        /// </summary>
        [JsonPropertyName("salesRepresentativeId")]
        public string? SalesRepresentativeId { get { return this.SalesRepresentativeIdOption.Value; } set { this.SalesRepresentativeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShipmentOrigin
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ShipmentOriginOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShipmentOrigin
        /// </summary>
        [JsonPropertyName("shipmentOrigin")]
        public string? ShipmentOrigin { get { return this.ShipmentOriginOption.Value; } set { this.ShipmentOriginOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShippingDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> ShippingDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShippingDate
        /// </summary>
        [JsonPropertyName("shippingDate")]
        public DateOnly? ShippingDate { get { return this.ShippingDateOption.Value; } set { this.ShippingDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShippingMethodId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ShippingMethodIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ShippingMethodId
        /// </summary>
        [JsonPropertyName("shippingMethodId")]
        public string? ShippingMethodId { get { return this.ShippingMethodIdOption.Value; } set { this.ShippingMethodIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesTaxItemId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesTaxItemIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesTaxItemId
        /// </summary>
        [JsonPropertyName("salesTaxItemId")]
        public string? SalesTaxItemId { get { return this.SalesTaxItemIdOption.Value; } set { this.SalesTaxItemIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Memo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MemoOption { get; private set; }

        /// <summary>
        /// Memo/description for the invoice.
        /// </summary>
        /// <value>Memo/description for the invoice.</value>
        [JsonPropertyName("memo")]
        public string? Memo { get { return this.MemoOption.Value; } set { this.MemoOption = new(value); } }

        /// <summary>
        /// Used to track the state of OtherCustomField
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OtherCustomFieldOption { get; private set; }

        /// <summary>
        /// Gets or Sets OtherCustomField
        /// </summary>
        [JsonPropertyName("otherCustomField")]
        public string? OtherCustomField { get { return this.OtherCustomFieldOption.Value; } set { this.OtherCustomFieldOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomerMessageId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CustomerMessageIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomerMessageId
        /// </summary>
        [JsonPropertyName("customerMessageId")]
        public string? CustomerMessageId { get { return this.CustomerMessageIdOption.Value; } set { this.CustomerMessageIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsQueuedForPrint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsQueuedForPrintOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsQueuedForPrint
        /// </summary>
        [JsonPropertyName("isQueuedForPrint")]
        public bool? IsQueuedForPrint { get { return this.IsQueuedForPrintOption.Value; } set { this.IsQueuedForPrintOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsQueuedForEmail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsQueuedForEmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsQueuedForEmail
        /// </summary>
        [JsonPropertyName("isQueuedForEmail")]
        public bool? IsQueuedForEmail { get { return this.IsQueuedForEmailOption.Value; } set { this.IsQueuedForEmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsTaxIncluded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsTaxIncludedOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsTaxIncluded
        /// </summary>
        [JsonPropertyName("isTaxIncluded")]
        public bool? IsTaxIncluded { get { return this.IsTaxIncludedOption.Value; } set { this.IsTaxIncludedOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesTaxCodeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesTaxCodeIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SalesTaxCodeId
        /// </summary>
        [JsonPropertyName("salesTaxCodeId")]
        public string? SalesTaxCodeId { get { return this.SalesTaxCodeIdOption.Value; } set { this.SalesTaxCodeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> ExchangeRateOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExchangeRate
        /// </summary>
        [JsonPropertyName("exchangeRate")]
        public float? ExchangeRate { get { return this.ExchangeRateOption.Value; } set { this.ExchangeRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApplyCredits
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateSetCreditRequest>?> ApplyCreditsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplyCredits
        /// </summary>
        [JsonPropertyName("applyCredits")]
        public List<CreateSetCreditRequest>? ApplyCredits { get { return this.ApplyCreditsOption.Value; } set { this.ApplyCreditsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Lines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UpdateItemLineRequest>?> LinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Lines
        /// </summary>
        [JsonPropertyName("lines")]
        public List<UpdateItemLineRequest>? Lines { get { return this.LinesOption.Value; } set { this.LinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of LineGroups
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UpdateItemGroupLineRequest>?> LineGroupsOption { get; private set; }

        /// <summary>
        /// Gets or Sets LineGroups
        /// </summary>
        [JsonPropertyName("lineGroups")]
        public List<UpdateItemGroupLineRequest>? LineGroups { get { return this.LineGroupsOption.Value; } set { this.LineGroupsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateInvoiceRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  ClassId: ").Append(ClassId).Append("\n");
            sb.Append("  ReceivablesAccountId: ").Append(ReceivablesAccountId).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  TransactionDate: ").Append(TransactionDate).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  BillingAddress: ").Append(BillingAddress).Append("\n");
            sb.Append("  ShippingAddress: ").Append(ShippingAddress).Append("\n");
            sb.Append("  IsPending: ").Append(IsPending).Append("\n");
            sb.Append("  PurchaseOrderNumber: ").Append(PurchaseOrderNumber).Append("\n");
            sb.Append("  TermsId: ").Append(TermsId).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  SalesRepresentativeId: ").Append(SalesRepresentativeId).Append("\n");
            sb.Append("  ShipmentOrigin: ").Append(ShipmentOrigin).Append("\n");
            sb.Append("  ShippingDate: ").Append(ShippingDate).Append("\n");
            sb.Append("  ShippingMethodId: ").Append(ShippingMethodId).Append("\n");
            sb.Append("  SalesTaxItemId: ").Append(SalesTaxItemId).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  OtherCustomField: ").Append(OtherCustomField).Append("\n");
            sb.Append("  CustomerMessageId: ").Append(CustomerMessageId).Append("\n");
            sb.Append("  IsQueuedForPrint: ").Append(IsQueuedForPrint).Append("\n");
            sb.Append("  IsQueuedForEmail: ").Append(IsQueuedForEmail).Append("\n");
            sb.Append("  IsTaxIncluded: ").Append(IsTaxIncluded).Append("\n");
            sb.Append("  SalesTaxCodeId: ").Append(SalesTaxCodeId).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  ApplyCredits: ").Append(ApplyCredits).Append("\n");
            sb.Append("  Lines: ").Append(Lines).Append("\n");
            sb.Append("  LineGroups: ").Append(LineGroups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RefNumber (string) maxLength
            if (this.RefNumber != null && this.RefNumber.Length > 11)
            {
                yield return new ValidationResult("Invalid value for RefNumber, length must be less than 11.", new [] { "RefNumber" });
            }

            // PurchaseOrderNumber (string) maxLength
            if (this.PurchaseOrderNumber != null && this.PurchaseOrderNumber.Length > 25)
            {
                yield return new ValidationResult("Invalid value for PurchaseOrderNumber, length must be less than 25.", new [] { "PurchaseOrderNumber" });
            }

            // ShipmentOrigin (string) maxLength
            if (this.ShipmentOrigin != null && this.ShipmentOrigin.Length > 13)
            {
                yield return new ValidationResult("Invalid value for ShipmentOrigin, length must be less than 13.", new [] { "ShipmentOrigin" });
            }

            // Memo (string) maxLength
            if (this.Memo != null && this.Memo.Length > 4095)
            {
                yield return new ValidationResult("Invalid value for Memo, length must be less than 4095.", new [] { "Memo" });
            }

            // OtherCustomField (string) maxLength
            if (this.OtherCustomField != null && this.OtherCustomField.Length > 29)
            {
                yield return new ValidationResult("Invalid value for OtherCustomField, length must be less than 29.", new [] { "OtherCustomField" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateInvoiceRequest" />
    /// </summary>
    public class UpdateInvoiceRequestJsonConverter : JsonConverter<UpdateInvoiceRequest>
    {
        /// <summary>
        /// The format to use to serialize TransactionDate
        /// </summary>
        public static string TransactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize DueDate
        /// </summary>
        public static string DueDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// The format to use to serialize ShippingDate
        /// </summary>
        public static string ShippingDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="UpdateInvoiceRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateInvoiceRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> customerId = default;
            Option<string?> classId = default;
            Option<string?> receivablesAccountId = default;
            Option<string?> templateId = default;
            Option<DateOnly?> transactionDate = default;
            Option<string?> refNumber = default;
            Option<AddressRequest?> billingAddress = default;
            Option<AddressRequest?> shippingAddress = default;
            Option<bool?> isPending = default;
            Option<string?> purchaseOrderNumber = default;
            Option<string?> termsId = default;
            Option<DateOnly?> dueDate = default;
            Option<string?> salesRepresentativeId = default;
            Option<string?> shipmentOrigin = default;
            Option<DateOnly?> shippingDate = default;
            Option<string?> shippingMethodId = default;
            Option<string?> salesTaxItemId = default;
            Option<string?> memo = default;
            Option<string?> otherCustomField = default;
            Option<string?> customerMessageId = default;
            Option<bool?> isQueuedForPrint = default;
            Option<bool?> isQueuedForEmail = default;
            Option<bool?> isTaxIncluded = default;
            Option<string?> salesTaxCodeId = default;
            Option<float?> exchangeRate = default;
            Option<List<CreateSetCreditRequest>?> applyCredits = default;
            Option<List<UpdateItemLineRequest>?> lines = default;
            Option<List<UpdateItemGroupLineRequest>?> lineGroups = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "customerId":
                            customerId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "classId":
                            classId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "receivablesAccountId":
                            receivablesAccountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "templateId":
                            templateId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transactionDate":
                            transactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "billingAddress":
                            billingAddress = new Option<AddressRequest?>(JsonSerializer.Deserialize<AddressRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "shippingAddress":
                            shippingAddress = new Option<AddressRequest?>(JsonSerializer.Deserialize<AddressRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "isPending":
                            isPending = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "purchaseOrderNumber":
                            purchaseOrderNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "termsId":
                            termsId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "dueDate":
                            dueDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "salesRepresentativeId":
                            salesRepresentativeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "shipmentOrigin":
                            shipmentOrigin = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "shippingDate":
                            shippingDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "shippingMethodId":
                            shippingMethodId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "salesTaxItemId":
                            salesTaxItemId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "memo":
                            memo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "otherCustomField":
                            otherCustomField = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "customerMessageId":
                            customerMessageId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isQueuedForPrint":
                            isQueuedForPrint = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isQueuedForEmail":
                            isQueuedForEmail = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "isTaxIncluded":
                            isTaxIncluded = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "salesTaxCodeId":
                            salesTaxCodeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exchangeRate":
                            exchangeRate = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "applyCredits":
                            applyCredits = new Option<List<CreateSetCreditRequest>?>(JsonSerializer.Deserialize<List<CreateSetCreditRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "lines":
                            lines = new Option<List<UpdateItemLineRequest>?>(JsonSerializer.Deserialize<List<UpdateItemLineRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "lineGroups":
                            lineGroups = new Option<List<UpdateItemGroupLineRequest>?>(JsonSerializer.Deserialize<List<UpdateItemGroupLineRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateInvoiceRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateInvoiceRequest.");

            if (applyCredits.IsSet && applyCredits.Value == null)
                throw new ArgumentNullException(nameof(applyCredits), "Property is not nullable for class UpdateInvoiceRequest.");

            if (lines.IsSet && lines.Value == null)
                throw new ArgumentNullException(nameof(lines), "Property is not nullable for class UpdateInvoiceRequest.");

            if (lineGroups.IsSet && lineGroups.Value == null)
                throw new ArgumentNullException(nameof(lineGroups), "Property is not nullable for class UpdateInvoiceRequest.");

            return new UpdateInvoiceRequest(revisionNumber.Value!, customerId, classId, receivablesAccountId, templateId, transactionDate, refNumber, billingAddress, shippingAddress, isPending, purchaseOrderNumber, termsId, dueDate, salesRepresentativeId, shipmentOrigin, shippingDate, shippingMethodId, salesTaxItemId, memo, otherCustomField, customerMessageId, isQueuedForPrint, isQueuedForEmail, isTaxIncluded, salesTaxCodeId, exchangeRate, applyCredits, lines, lineGroups);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateInvoiceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateInvoiceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateInvoiceRequest updateInvoiceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateInvoiceRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateInvoiceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateInvoiceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateInvoiceRequest updateInvoiceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateInvoiceRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateInvoiceRequest.RevisionNumber), "Property is required for class UpdateInvoiceRequest.");

            if (updateInvoiceRequest.ApplyCreditsOption.IsSet && updateInvoiceRequest.ApplyCredits == null)
                throw new ArgumentNullException(nameof(updateInvoiceRequest.ApplyCredits), "Property is required for class UpdateInvoiceRequest.");

            if (updateInvoiceRequest.LinesOption.IsSet && updateInvoiceRequest.Lines == null)
                throw new ArgumentNullException(nameof(updateInvoiceRequest.Lines), "Property is required for class UpdateInvoiceRequest.");

            if (updateInvoiceRequest.LineGroupsOption.IsSet && updateInvoiceRequest.LineGroups == null)
                throw new ArgumentNullException(nameof(updateInvoiceRequest.LineGroups), "Property is required for class UpdateInvoiceRequest.");

            writer.WriteString("revisionNumber", updateInvoiceRequest.RevisionNumber);

            if (updateInvoiceRequest.CustomerIdOption.IsSet)
                if (updateInvoiceRequest.CustomerIdOption.Value != null)
                    writer.WriteString("customerId", updateInvoiceRequest.CustomerId);
                else
                    writer.WriteNull("customerId");

            if (updateInvoiceRequest.ClassIdOption.IsSet)
                if (updateInvoiceRequest.ClassIdOption.Value != null)
                    writer.WriteString("classId", updateInvoiceRequest.ClassId);
                else
                    writer.WriteNull("classId");

            if (updateInvoiceRequest.ReceivablesAccountIdOption.IsSet)
                if (updateInvoiceRequest.ReceivablesAccountIdOption.Value != null)
                    writer.WriteString("receivablesAccountId", updateInvoiceRequest.ReceivablesAccountId);
                else
                    writer.WriteNull("receivablesAccountId");

            if (updateInvoiceRequest.TemplateIdOption.IsSet)
                if (updateInvoiceRequest.TemplateIdOption.Value != null)
                    writer.WriteString("templateId", updateInvoiceRequest.TemplateId);
                else
                    writer.WriteNull("templateId");

            if (updateInvoiceRequest.TransactionDateOption.IsSet)
                if (updateInvoiceRequest.TransactionDateOption.Value != null)
                    writer.WriteString("transactionDate", updateInvoiceRequest.TransactionDateOption.Value!.Value.ToString(TransactionDateFormat));
                else
                    writer.WriteNull("transactionDate");

            if (updateInvoiceRequest.RefNumberOption.IsSet)
                if (updateInvoiceRequest.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", updateInvoiceRequest.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (updateInvoiceRequest.BillingAddressOption.IsSet)
                if (updateInvoiceRequest.BillingAddressOption.Value != null)
                {
                    writer.WritePropertyName("billingAddress");
                    JsonSerializer.Serialize(writer, updateInvoiceRequest.BillingAddress, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("billingAddress");
            if (updateInvoiceRequest.ShippingAddressOption.IsSet)
                if (updateInvoiceRequest.ShippingAddressOption.Value != null)
                {
                    writer.WritePropertyName("shippingAddress");
                    JsonSerializer.Serialize(writer, updateInvoiceRequest.ShippingAddress, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("shippingAddress");
            if (updateInvoiceRequest.IsPendingOption.IsSet)
                if (updateInvoiceRequest.IsPendingOption.Value != null)
                    writer.WriteBoolean("isPending", updateInvoiceRequest.IsPendingOption.Value!.Value);
                else
                    writer.WriteNull("isPending");

            if (updateInvoiceRequest.PurchaseOrderNumberOption.IsSet)
                if (updateInvoiceRequest.PurchaseOrderNumberOption.Value != null)
                    writer.WriteString("purchaseOrderNumber", updateInvoiceRequest.PurchaseOrderNumber);
                else
                    writer.WriteNull("purchaseOrderNumber");

            if (updateInvoiceRequest.TermsIdOption.IsSet)
                if (updateInvoiceRequest.TermsIdOption.Value != null)
                    writer.WriteString("termsId", updateInvoiceRequest.TermsId);
                else
                    writer.WriteNull("termsId");

            if (updateInvoiceRequest.DueDateOption.IsSet)
                if (updateInvoiceRequest.DueDateOption.Value != null)
                    writer.WriteString("dueDate", updateInvoiceRequest.DueDateOption.Value!.Value.ToString(DueDateFormat));
                else
                    writer.WriteNull("dueDate");

            if (updateInvoiceRequest.SalesRepresentativeIdOption.IsSet)
                if (updateInvoiceRequest.SalesRepresentativeIdOption.Value != null)
                    writer.WriteString("salesRepresentativeId", updateInvoiceRequest.SalesRepresentativeId);
                else
                    writer.WriteNull("salesRepresentativeId");

            if (updateInvoiceRequest.ShipmentOriginOption.IsSet)
                if (updateInvoiceRequest.ShipmentOriginOption.Value != null)
                    writer.WriteString("shipmentOrigin", updateInvoiceRequest.ShipmentOrigin);
                else
                    writer.WriteNull("shipmentOrigin");

            if (updateInvoiceRequest.ShippingDateOption.IsSet)
                if (updateInvoiceRequest.ShippingDateOption.Value != null)
                    writer.WriteString("shippingDate", updateInvoiceRequest.ShippingDateOption.Value!.Value.ToString(ShippingDateFormat));
                else
                    writer.WriteNull("shippingDate");

            if (updateInvoiceRequest.ShippingMethodIdOption.IsSet)
                if (updateInvoiceRequest.ShippingMethodIdOption.Value != null)
                    writer.WriteString("shippingMethodId", updateInvoiceRequest.ShippingMethodId);
                else
                    writer.WriteNull("shippingMethodId");

            if (updateInvoiceRequest.SalesTaxItemIdOption.IsSet)
                if (updateInvoiceRequest.SalesTaxItemIdOption.Value != null)
                    writer.WriteString("salesTaxItemId", updateInvoiceRequest.SalesTaxItemId);
                else
                    writer.WriteNull("salesTaxItemId");

            if (updateInvoiceRequest.MemoOption.IsSet)
                if (updateInvoiceRequest.MemoOption.Value != null)
                    writer.WriteString("memo", updateInvoiceRequest.Memo);
                else
                    writer.WriteNull("memo");

            if (updateInvoiceRequest.OtherCustomFieldOption.IsSet)
                if (updateInvoiceRequest.OtherCustomFieldOption.Value != null)
                    writer.WriteString("otherCustomField", updateInvoiceRequest.OtherCustomField);
                else
                    writer.WriteNull("otherCustomField");

            if (updateInvoiceRequest.CustomerMessageIdOption.IsSet)
                if (updateInvoiceRequest.CustomerMessageIdOption.Value != null)
                    writer.WriteString("customerMessageId", updateInvoiceRequest.CustomerMessageId);
                else
                    writer.WriteNull("customerMessageId");

            if (updateInvoiceRequest.IsQueuedForPrintOption.IsSet)
                if (updateInvoiceRequest.IsQueuedForPrintOption.Value != null)
                    writer.WriteBoolean("isQueuedForPrint", updateInvoiceRequest.IsQueuedForPrintOption.Value!.Value);
                else
                    writer.WriteNull("isQueuedForPrint");

            if (updateInvoiceRequest.IsQueuedForEmailOption.IsSet)
                if (updateInvoiceRequest.IsQueuedForEmailOption.Value != null)
                    writer.WriteBoolean("isQueuedForEmail", updateInvoiceRequest.IsQueuedForEmailOption.Value!.Value);
                else
                    writer.WriteNull("isQueuedForEmail");

            if (updateInvoiceRequest.IsTaxIncludedOption.IsSet)
                if (updateInvoiceRequest.IsTaxIncludedOption.Value != null)
                    writer.WriteBoolean("isTaxIncluded", updateInvoiceRequest.IsTaxIncludedOption.Value!.Value);
                else
                    writer.WriteNull("isTaxIncluded");

            if (updateInvoiceRequest.SalesTaxCodeIdOption.IsSet)
                if (updateInvoiceRequest.SalesTaxCodeIdOption.Value != null)
                    writer.WriteString("salesTaxCodeId", updateInvoiceRequest.SalesTaxCodeId);
                else
                    writer.WriteNull("salesTaxCodeId");

            if (updateInvoiceRequest.ExchangeRateOption.IsSet)
                if (updateInvoiceRequest.ExchangeRateOption.Value != null)
                    writer.WriteNumber("exchangeRate", updateInvoiceRequest.ExchangeRateOption.Value!.Value);
                else
                    writer.WriteNull("exchangeRate");

            if (updateInvoiceRequest.ApplyCreditsOption.IsSet)
            {
                writer.WritePropertyName("applyCredits");
                JsonSerializer.Serialize(writer, updateInvoiceRequest.ApplyCredits, jsonSerializerOptions);
            }
            if (updateInvoiceRequest.LinesOption.IsSet)
            {
                writer.WritePropertyName("lines");
                JsonSerializer.Serialize(writer, updateInvoiceRequest.Lines, jsonSerializerOptions);
            }
            if (updateInvoiceRequest.LineGroupsOption.IsSet)
            {
                writer.WritePropertyName("lineGroups");
                JsonSerializer.Serialize(writer, updateInvoiceRequest.LineGroups, jsonSerializerOptions);
            }
        }
    }
}
