// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// A request model for modifying an existing Currency.  Corresponds to the CurrencyMod QBXML message.
    /// </summary>
    public partial class UpdateCurrencyRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCurrencyRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="name">(Optional) The new name of the currency. Cannot be changed for built-in QuickBooks currencies. (Max 64 characters)</param>
        /// <param name="isActive">(Optional) If false, this Currency will be made inactive.</param>
        /// <param name="currencyCode">(Optional) The three-letter currency code (e.g., USD, EUR). Values are normalized to trimmed uppercase. Cannot be changed for built-in QuickBooks currencies. (Max 3 characters)</param>
        /// <param name="currencyFormat">(Optional) Specifies the formatting rules for the currency.</param>
        [JsonConstructor]
        public UpdateCurrencyRequest(string revisionNumber, Option<string?> name = default, Option<bool?> isActive = default, Option<string?> currencyCode = default, Option<CurrencyFormatRequest?> currencyFormat = default)
        {
            RevisionNumber = revisionNumber;
            NameOption = name;
            IsActiveOption = isActive;
            CurrencyCodeOption = currencyCode;
            CurrencyFormatOption = currencyFormat;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// (Optional) The new name of the currency. Cannot be changed for built-in QuickBooks currencies. (Max 64 characters)
        /// </summary>
        /// <value>(Optional) The new name of the currency. Cannot be changed for built-in QuickBooks currencies. (Max 64 characters)</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// (Optional) If false, this Currency will be made inactive.
        /// </summary>
        /// <value>(Optional) If false, this Currency will be made inactive.</value>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption.Value; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of CurrencyCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CurrencyCodeOption { get; private set; }

        /// <summary>
        /// (Optional) The three-letter currency code (e.g., USD, EUR). Values are normalized to trimmed uppercase. Cannot be changed for built-in QuickBooks currencies. (Max 3 characters)
        /// </summary>
        /// <value>(Optional) The three-letter currency code (e.g., USD, EUR). Values are normalized to trimmed uppercase. Cannot be changed for built-in QuickBooks currencies. (Max 3 characters)</value>
        [JsonPropertyName("currencyCode")]
        public string? CurrencyCode { get { return this.CurrencyCodeOption.Value; } set { this.CurrencyCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of CurrencyFormat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CurrencyFormatRequest?> CurrencyFormatOption { get; private set; }

        /// <summary>
        /// (Optional) Specifies the formatting rules for the currency.
        /// </summary>
        /// <value>(Optional) Specifies the formatting rules for the currency.</value>
        [JsonPropertyName("currencyFormat")]
        public CurrencyFormatRequest? CurrencyFormat { get { return this.CurrencyFormatOption.Value; } set { this.CurrencyFormatOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCurrencyRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  CurrencyFormat: ").Append(CurrencyFormat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateCurrencyRequest" />
    /// </summary>
    public class UpdateCurrencyRequestJsonConverter : JsonConverter<UpdateCurrencyRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateCurrencyRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateCurrencyRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> name = default;
            Option<bool?> isActive = default;
            Option<string?> currencyCode = default;
            Option<CurrencyFormatRequest?> currencyFormat = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "currencyCode":
                            currencyCode = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "currencyFormat":
                            currencyFormat = new Option<CurrencyFormatRequest?>(JsonSerializer.Deserialize<CurrencyFormatRequest>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateCurrencyRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateCurrencyRequest.");

            return new UpdateCurrencyRequest(revisionNumber.Value!, name, isActive, currencyCode, currencyFormat);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateCurrencyRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCurrencyRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateCurrencyRequest updateCurrencyRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateCurrencyRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateCurrencyRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCurrencyRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateCurrencyRequest updateCurrencyRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateCurrencyRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateCurrencyRequest.RevisionNumber), "Property is required for class UpdateCurrencyRequest.");

            writer.WriteString("revisionNumber", updateCurrencyRequest.RevisionNumber);

            if (updateCurrencyRequest.NameOption.IsSet)
                if (updateCurrencyRequest.NameOption.Value != null)
                    writer.WriteString("name", updateCurrencyRequest.Name);
                else
                    writer.WriteNull("name");

            if (updateCurrencyRequest.IsActiveOption.IsSet)
                if (updateCurrencyRequest.IsActiveOption.Value != null)
                    writer.WriteBoolean("isActive", updateCurrencyRequest.IsActiveOption.Value!.Value);
                else
                    writer.WriteNull("isActive");

            if (updateCurrencyRequest.CurrencyCodeOption.IsSet)
                if (updateCurrencyRequest.CurrencyCodeOption.Value != null)
                    writer.WriteString("currencyCode", updateCurrencyRequest.CurrencyCode);
                else
                    writer.WriteNull("currencyCode");

            if (updateCurrencyRequest.CurrencyFormatOption.IsSet)
                if (updateCurrencyRequest.CurrencyFormatOption.Value != null)
                {
                    writer.WritePropertyName("currencyFormat");
                    JsonSerializer.Serialize(writer, updateCurrencyRequest.CurrencyFormat, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("currencyFormat");
        }
    }
}
