// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Request model for updating an existing check payment
    /// </summary>
    public partial class UpdateCheckRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCheckRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="refNumber">Check number</param>
        /// <param name="traansactionDate">traansactionDate</param>
        /// <param name="accountId">Bank account</param>
        /// <param name="payeeId">Vendor/payee</param>
        /// <param name="memo">Memo/description</param>
        /// <param name="isQueuedForPrint">isQueuedForPrint</param>
        /// <param name="address">Payee address</param>
        /// <param name="isTaxIncluded">If true, the amount includes sales tax.</param>
        /// <param name="salesTaxCodeId">The ListID or FullName of the sales tax code.</param>
        /// <param name="exchangeRate">Exchange rate</param>
        /// <param name="applyToTransactions">applyToTransactions</param>
        /// <param name="clearExpenseLines">Clear existing expense lines</param>
        /// <param name="expenseLines">expenseLines</param>
        /// <param name="clearItemLines">Clear existing item lines</param>
        /// <param name="itemLines">itemLines</param>
        /// <param name="itemGroupLines">itemGroupLines</param>
        [JsonConstructor]
        public UpdateCheckRequest(string revisionNumber, Option<string?> refNumber = default, Option<DateOnly?> traansactionDate = default, Option<string?> accountId = default, Option<string?> payeeId = default, Option<string?> memo = default, Option<bool?> isQueuedForPrint = default, Option<Address?> address = default, Option<bool?> isTaxIncluded = default, Option<string?> salesTaxCodeId = default, Option<double?> exchangeRate = default, Option<List<ApplyCheckToTransactionRequest>?> applyToTransactions = default, Option<bool?> clearExpenseLines = default, Option<List<UpdateExpenseLineRequest>?> expenseLines = default, Option<bool?> clearItemLines = default, Option<List<UpdateItemLineRequest>?> itemLines = default, Option<List<UpdateItemGroupLineRequest>?> itemGroupLines = default)
        {
            RevisionNumber = revisionNumber;
            RefNumberOption = refNumber;
            TraansactionDateOption = traansactionDate;
            AccountIdOption = accountId;
            PayeeIdOption = payeeId;
            MemoOption = memo;
            IsQueuedForPrintOption = isQueuedForPrint;
            AddressOption = address;
            IsTaxIncludedOption = isTaxIncluded;
            SalesTaxCodeIdOption = salesTaxCodeId;
            ExchangeRateOption = exchangeRate;
            ApplyToTransactionsOption = applyToTransactions;
            ClearExpenseLinesOption = clearExpenseLines;
            ExpenseLinesOption = expenseLines;
            ClearItemLinesOption = clearItemLines;
            ItemLinesOption = itemLines;
            ItemGroupLinesOption = itemGroupLines;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of RefNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RefNumberOption { get; private set; }

        /// <summary>
        /// Check number
        /// </summary>
        /// <value>Check number</value>
        [JsonPropertyName("refNumber")]
        public string? RefNumber { get { return this.RefNumberOption.Value; } set { this.RefNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of TraansactionDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateOnly?> TraansactionDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets TraansactionDate
        /// </summary>
        [JsonPropertyName("traansactionDate")]
        public DateOnly? TraansactionDate { get { return this.TraansactionDateOption.Value; } set { this.TraansactionDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccountId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountIdOption { get; private set; }

        /// <summary>
        /// Bank account
        /// </summary>
        /// <value>Bank account</value>
        [JsonPropertyName("accountId")]
        public string? AccountId { get { return this.AccountIdOption.Value; } set { this.AccountIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of PayeeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PayeeIdOption { get; private set; }

        /// <summary>
        /// Vendor/payee
        /// </summary>
        /// <value>Vendor/payee</value>
        [JsonPropertyName("payeeId")]
        public string? PayeeId { get { return this.PayeeIdOption.Value; } set { this.PayeeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Memo
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MemoOption { get; private set; }

        /// <summary>
        /// Memo/description
        /// </summary>
        /// <value>Memo/description</value>
        [JsonPropertyName("memo")]
        public string? Memo { get { return this.MemoOption.Value; } set { this.MemoOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsQueuedForPrint
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsQueuedForPrintOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsQueuedForPrint
        /// </summary>
        [JsonPropertyName("isQueuedForPrint")]
        public bool? IsQueuedForPrint { get { return this.IsQueuedForPrintOption.Value; } set { this.IsQueuedForPrintOption = new(value); } }

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Address?> AddressOption { get; private set; }

        /// <summary>
        /// Payee address
        /// </summary>
        /// <value>Payee address</value>
        [JsonPropertyName("address")]
        public Address? Address { get { return this.AddressOption.Value; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsTaxIncluded
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsTaxIncludedOption { get; private set; }

        /// <summary>
        /// If true, the amount includes sales tax.
        /// </summary>
        /// <value>If true, the amount includes sales tax.</value>
        [JsonPropertyName("isTaxIncluded")]
        public bool? IsTaxIncluded { get { return this.IsTaxIncludedOption.Value; } set { this.IsTaxIncludedOption = new(value); } }

        /// <summary>
        /// Used to track the state of SalesTaxCodeId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalesTaxCodeIdOption { get; private set; }

        /// <summary>
        /// The ListID or FullName of the sales tax code.
        /// </summary>
        /// <value>The ListID or FullName of the sales tax code.</value>
        [JsonPropertyName("salesTaxCodeId")]
        public string? SalesTaxCodeId { get { return this.SalesTaxCodeIdOption.Value; } set { this.SalesTaxCodeIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeRate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ExchangeRateOption { get; private set; }

        /// <summary>
        /// Exchange rate
        /// </summary>
        /// <value>Exchange rate</value>
        [JsonPropertyName("exchangeRate")]
        public double? ExchangeRate { get { return this.ExchangeRateOption.Value; } set { this.ExchangeRateOption = new(value); } }

        /// <summary>
        /// Used to track the state of ApplyToTransactions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ApplyCheckToTransactionRequest>?> ApplyToTransactionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ApplyToTransactions
        /// </summary>
        [JsonPropertyName("applyToTransactions")]
        public List<ApplyCheckToTransactionRequest>? ApplyToTransactions { get { return this.ApplyToTransactionsOption.Value; } set { this.ApplyToTransactionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClearExpenseLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ClearExpenseLinesOption { get; private set; }

        /// <summary>
        /// Clear existing expense lines
        /// </summary>
        /// <value>Clear existing expense lines</value>
        [JsonPropertyName("clearExpenseLines")]
        public bool? ClearExpenseLines { get { return this.ClearExpenseLinesOption.Value; } set { this.ClearExpenseLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpenseLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UpdateExpenseLineRequest>?> ExpenseLinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpenseLines
        /// </summary>
        [JsonPropertyName("expenseLines")]
        public List<UpdateExpenseLineRequest>? ExpenseLines { get { return this.ExpenseLinesOption.Value; } set { this.ExpenseLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ClearItemLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ClearItemLinesOption { get; private set; }

        /// <summary>
        /// Clear existing item lines
        /// </summary>
        /// <value>Clear existing item lines</value>
        [JsonPropertyName("clearItemLines")]
        public bool? ClearItemLines { get { return this.ClearItemLinesOption.Value; } set { this.ClearItemLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ItemLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UpdateItemLineRequest>?> ItemLinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ItemLines
        /// </summary>
        [JsonPropertyName("itemLines")]
        public List<UpdateItemLineRequest>? ItemLines { get { return this.ItemLinesOption.Value; } set { this.ItemLinesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ItemGroupLines
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UpdateItemGroupLineRequest>?> ItemGroupLinesOption { get; private set; }

        /// <summary>
        /// Gets or Sets ItemGroupLines
        /// </summary>
        [JsonPropertyName("itemGroupLines")]
        public List<UpdateItemGroupLineRequest>? ItemGroupLines { get { return this.ItemGroupLinesOption.Value; } set { this.ItemGroupLinesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCheckRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  RefNumber: ").Append(RefNumber).Append("\n");
            sb.Append("  TraansactionDate: ").Append(TraansactionDate).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  PayeeId: ").Append(PayeeId).Append("\n");
            sb.Append("  Memo: ").Append(Memo).Append("\n");
            sb.Append("  IsQueuedForPrint: ").Append(IsQueuedForPrint).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  IsTaxIncluded: ").Append(IsTaxIncluded).Append("\n");
            sb.Append("  SalesTaxCodeId: ").Append(SalesTaxCodeId).Append("\n");
            sb.Append("  ExchangeRate: ").Append(ExchangeRate).Append("\n");
            sb.Append("  ApplyToTransactions: ").Append(ApplyToTransactions).Append("\n");
            sb.Append("  ClearExpenseLines: ").Append(ClearExpenseLines).Append("\n");
            sb.Append("  ExpenseLines: ").Append(ExpenseLines).Append("\n");
            sb.Append("  ClearItemLines: ").Append(ClearItemLines).Append("\n");
            sb.Append("  ItemLines: ").Append(ItemLines).Append("\n");
            sb.Append("  ItemGroupLines: ").Append(ItemGroupLines).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RefNumber (string) maxLength
            if (this.RefNumber != null && this.RefNumber.Length > 20)
            {
                yield return new ValidationResult("Invalid value for RefNumber, length must be less than 20.", new [] { "RefNumber" });
            }

            // Memo (string) maxLength
            if (this.Memo != null && this.Memo.Length > 4095)
            {
                yield return new ValidationResult("Invalid value for Memo, length must be less than 4095.", new [] { "Memo" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateCheckRequest" />
    /// </summary>
    public class UpdateCheckRequestJsonConverter : JsonConverter<UpdateCheckRequest>
    {
        /// <summary>
        /// The format to use to serialize TraansactionDate
        /// </summary>
        public static string TraansactionDateFormat { get; set; } = "yyyy'-'MM'-'dd";

        /// <summary>
        /// Deserializes json to <see cref="UpdateCheckRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateCheckRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> refNumber = default;
            Option<DateOnly?> traansactionDate = default;
            Option<string?> accountId = default;
            Option<string?> payeeId = default;
            Option<string?> memo = default;
            Option<bool?> isQueuedForPrint = default;
            Option<Address?> address = default;
            Option<bool?> isTaxIncluded = default;
            Option<string?> salesTaxCodeId = default;
            Option<double?> exchangeRate = default;
            Option<List<ApplyCheckToTransactionRequest>?> applyToTransactions = default;
            Option<bool?> clearExpenseLines = default;
            Option<List<UpdateExpenseLineRequest>?> expenseLines = default;
            Option<bool?> clearItemLines = default;
            Option<List<UpdateItemLineRequest>?> itemLines = default;
            Option<List<UpdateItemGroupLineRequest>?> itemGroupLines = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "refNumber":
                            refNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "traansactionDate":
                            traansactionDate = new Option<DateOnly?>(JsonSerializer.Deserialize<DateOnly?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "accountId":
                            accountId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "payeeId":
                            payeeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "memo":
                            memo = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isQueuedForPrint":
                            isQueuedForPrint = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "address":
                            address = new Option<Address?>(JsonSerializer.Deserialize<Address>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "isTaxIncluded":
                            isTaxIncluded = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "salesTaxCodeId":
                            salesTaxCodeId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exchangeRate":
                            exchangeRate = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "applyToTransactions":
                            applyToTransactions = new Option<List<ApplyCheckToTransactionRequest>?>(JsonSerializer.Deserialize<List<ApplyCheckToTransactionRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "clearExpenseLines":
                            clearExpenseLines = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "expenseLines":
                            expenseLines = new Option<List<UpdateExpenseLineRequest>?>(JsonSerializer.Deserialize<List<UpdateExpenseLineRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "clearItemLines":
                            clearItemLines = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "itemLines":
                            itemLines = new Option<List<UpdateItemLineRequest>?>(JsonSerializer.Deserialize<List<UpdateItemLineRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "itemGroupLines":
                            itemGroupLines = new Option<List<UpdateItemGroupLineRequest>?>(JsonSerializer.Deserialize<List<UpdateItemGroupLineRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateCheckRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateCheckRequest.");

            if (applyToTransactions.IsSet && applyToTransactions.Value == null)
                throw new ArgumentNullException(nameof(applyToTransactions), "Property is not nullable for class UpdateCheckRequest.");

            if (expenseLines.IsSet && expenseLines.Value == null)
                throw new ArgumentNullException(nameof(expenseLines), "Property is not nullable for class UpdateCheckRequest.");

            if (itemLines.IsSet && itemLines.Value == null)
                throw new ArgumentNullException(nameof(itemLines), "Property is not nullable for class UpdateCheckRequest.");

            if (itemGroupLines.IsSet && itemGroupLines.Value == null)
                throw new ArgumentNullException(nameof(itemGroupLines), "Property is not nullable for class UpdateCheckRequest.");

            return new UpdateCheckRequest(revisionNumber.Value!, refNumber, traansactionDate, accountId, payeeId, memo, isQueuedForPrint, address, isTaxIncluded, salesTaxCodeId, exchangeRate, applyToTransactions, clearExpenseLines, expenseLines, clearItemLines, itemLines, itemGroupLines);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateCheckRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCheckRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateCheckRequest updateCheckRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateCheckRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateCheckRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCheckRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateCheckRequest updateCheckRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateCheckRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateCheckRequest.RevisionNumber), "Property is required for class UpdateCheckRequest.");

            if (updateCheckRequest.ApplyToTransactionsOption.IsSet && updateCheckRequest.ApplyToTransactions == null)
                throw new ArgumentNullException(nameof(updateCheckRequest.ApplyToTransactions), "Property is required for class UpdateCheckRequest.");

            if (updateCheckRequest.ExpenseLinesOption.IsSet && updateCheckRequest.ExpenseLines == null)
                throw new ArgumentNullException(nameof(updateCheckRequest.ExpenseLines), "Property is required for class UpdateCheckRequest.");

            if (updateCheckRequest.ItemLinesOption.IsSet && updateCheckRequest.ItemLines == null)
                throw new ArgumentNullException(nameof(updateCheckRequest.ItemLines), "Property is required for class UpdateCheckRequest.");

            if (updateCheckRequest.ItemGroupLinesOption.IsSet && updateCheckRequest.ItemGroupLines == null)
                throw new ArgumentNullException(nameof(updateCheckRequest.ItemGroupLines), "Property is required for class UpdateCheckRequest.");

            writer.WriteString("revisionNumber", updateCheckRequest.RevisionNumber);

            if (updateCheckRequest.RefNumberOption.IsSet)
                if (updateCheckRequest.RefNumberOption.Value != null)
                    writer.WriteString("refNumber", updateCheckRequest.RefNumber);
                else
                    writer.WriteNull("refNumber");

            if (updateCheckRequest.TraansactionDateOption.IsSet)
                if (updateCheckRequest.TraansactionDateOption.Value != null)
                    writer.WriteString("traansactionDate", updateCheckRequest.TraansactionDateOption.Value!.Value.ToString(TraansactionDateFormat));
                else
                    writer.WriteNull("traansactionDate");

            if (updateCheckRequest.AccountIdOption.IsSet)
                if (updateCheckRequest.AccountIdOption.Value != null)
                    writer.WriteString("accountId", updateCheckRequest.AccountId);
                else
                    writer.WriteNull("accountId");

            if (updateCheckRequest.PayeeIdOption.IsSet)
                if (updateCheckRequest.PayeeIdOption.Value != null)
                    writer.WriteString("payeeId", updateCheckRequest.PayeeId);
                else
                    writer.WriteNull("payeeId");

            if (updateCheckRequest.MemoOption.IsSet)
                if (updateCheckRequest.MemoOption.Value != null)
                    writer.WriteString("memo", updateCheckRequest.Memo);
                else
                    writer.WriteNull("memo");

            if (updateCheckRequest.IsQueuedForPrintOption.IsSet)
                if (updateCheckRequest.IsQueuedForPrintOption.Value != null)
                    writer.WriteBoolean("isQueuedForPrint", updateCheckRequest.IsQueuedForPrintOption.Value!.Value);
                else
                    writer.WriteNull("isQueuedForPrint");

            if (updateCheckRequest.AddressOption.IsSet)
                if (updateCheckRequest.AddressOption.Value != null)
                {
                    writer.WritePropertyName("address");
                    JsonSerializer.Serialize(writer, updateCheckRequest.Address, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("address");
            if (updateCheckRequest.IsTaxIncludedOption.IsSet)
                if (updateCheckRequest.IsTaxIncludedOption.Value != null)
                    writer.WriteBoolean("isTaxIncluded", updateCheckRequest.IsTaxIncludedOption.Value!.Value);
                else
                    writer.WriteNull("isTaxIncluded");

            if (updateCheckRequest.SalesTaxCodeIdOption.IsSet)
                if (updateCheckRequest.SalesTaxCodeIdOption.Value != null)
                    writer.WriteString("salesTaxCodeId", updateCheckRequest.SalesTaxCodeId);
                else
                    writer.WriteNull("salesTaxCodeId");

            if (updateCheckRequest.ExchangeRateOption.IsSet)
                if (updateCheckRequest.ExchangeRateOption.Value != null)
                    writer.WriteNumber("exchangeRate", updateCheckRequest.ExchangeRateOption.Value!.Value);
                else
                    writer.WriteNull("exchangeRate");

            if (updateCheckRequest.ApplyToTransactionsOption.IsSet)
            {
                writer.WritePropertyName("applyToTransactions");
                JsonSerializer.Serialize(writer, updateCheckRequest.ApplyToTransactions, jsonSerializerOptions);
            }
            if (updateCheckRequest.ClearExpenseLinesOption.IsSet)
                if (updateCheckRequest.ClearExpenseLinesOption.Value != null)
                    writer.WriteBoolean("clearExpenseLines", updateCheckRequest.ClearExpenseLinesOption.Value!.Value);
                else
                    writer.WriteNull("clearExpenseLines");

            if (updateCheckRequest.ExpenseLinesOption.IsSet)
            {
                writer.WritePropertyName("expenseLines");
                JsonSerializer.Serialize(writer, updateCheckRequest.ExpenseLines, jsonSerializerOptions);
            }
            if (updateCheckRequest.ClearItemLinesOption.IsSet)
                if (updateCheckRequest.ClearItemLinesOption.Value != null)
                    writer.WriteBoolean("clearItemLines", updateCheckRequest.ClearItemLinesOption.Value!.Value);
                else
                    writer.WriteNull("clearItemLines");

            if (updateCheckRequest.ItemLinesOption.IsSet)
            {
                writer.WritePropertyName("itemLines");
                JsonSerializer.Serialize(writer, updateCheckRequest.ItemLines, jsonSerializerOptions);
            }
            if (updateCheckRequest.ItemGroupLinesOption.IsSet)
            {
                writer.WritePropertyName("itemGroupLines");
                JsonSerializer.Serialize(writer, updateCheckRequest.ItemGroupLines, jsonSerializerOptions);
            }
        }
    }
}
