// <auto-generated>
/*
 * nXus API Reference
 *
 * Production-ready stable API. Includes fully tested endpoints for Vendors, Customers, Accounts, Employees, Bills, Checks, and core list & Transaction entities. Use this version for production applications.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Nxus.Qbd.Json;

namespace Nxus.Qbd.Models
{
    /// <summary>
    /// Request for updating an existing OtherName.  Implements IUpdateRequest for the abstraction pattern.
    /// </summary>
    public partial class UpdateOtherNameRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateOtherNameRequest" /> class.
        /// </summary>
        /// <param name="revisionNumber">revisionNumber</param>
        /// <param name="name">name</param>
        /// <param name="companyName">companyName</param>
        /// <param name="salutation">salutation</param>
        /// <param name="firstName">firstName</param>
        /// <param name="middleName">middleName</param>
        /// <param name="lastName">lastName</param>
        /// <param name="address">address</param>
        /// <param name="addressBlock">addressBlock</param>
        /// <param name="phone">phone</param>
        /// <param name="alternatePhone">alternatePhone</param>
        /// <param name="fax">fax</param>
        /// <param name="email">email</param>
        /// <param name="contact">contact</param>
        /// <param name="alternateContact">alternateContact</param>
        /// <param name="accountNumber">accountNumber</param>
        /// <param name="notes">notes</param>
        /// <param name="customFields">customFields</param>
        [JsonConstructor]
        public UpdateOtherNameRequest(string revisionNumber, Option<string?> name = default, Option<string?> companyName = default, Option<string?> salutation = default, Option<string?> firstName = default, Option<string?> middleName = default, Option<string?> lastName = default, Option<Address?> address = default, Option<AddressBlock?> addressBlock = default, Option<string?> phone = default, Option<string?> alternatePhone = default, Option<string?> fax = default, Option<string?> email = default, Option<string?> contact = default, Option<string?> alternateContact = default, Option<string?> accountNumber = default, Option<string?> notes = default, Option<List<DataExtRequest>?> customFields = default)
        {
            RevisionNumber = revisionNumber;
            NameOption = name;
            CompanyNameOption = companyName;
            SalutationOption = salutation;
            FirstNameOption = firstName;
            MiddleNameOption = middleName;
            LastNameOption = lastName;
            AddressOption = address;
            AddressBlockOption = addressBlock;
            PhoneOption = phone;
            AlternatePhoneOption = alternatePhone;
            FaxOption = fax;
            EmailOption = email;
            ContactOption = contact;
            AlternateContactOption = alternateContact;
            AccountNumberOption = accountNumber;
            NotesOption = notes;
            CustomFieldsOption = customFields;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RevisionNumber
        /// </summary>
        [JsonPropertyName("revisionNumber")]
        public string RevisionNumber { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompanyName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [JsonPropertyName("companyName")]
        public string? CompanyName { get { return this.CompanyNameOption.Value; } set { this.CompanyNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Salutation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SalutationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Salutation
        /// </summary>
        [JsonPropertyName("salutation")]
        public string? Salutation { get { return this.SalutationOption.Value; } set { this.SalutationOption = new(value); } }

        /// <summary>
        /// Used to track the state of FirstName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FirstNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [JsonPropertyName("firstName")]
        public string? FirstName { get { return this.FirstNameOption.Value; } set { this.FirstNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of MiddleName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MiddleNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets MiddleName
        /// </summary>
        [JsonPropertyName("middleName")]
        public string? MiddleName { get { return this.MiddleNameOption.Value; } set { this.MiddleNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [JsonPropertyName("lastName")]
        public string? LastName { get { return this.LastNameOption.Value; } set { this.LastNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Address
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Address?> AddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public Address? Address { get { return this.AddressOption.Value; } set { this.AddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of AddressBlock
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AddressBlock?> AddressBlockOption { get; private set; }

        /// <summary>
        /// Gets or Sets AddressBlock
        /// </summary>
        [JsonPropertyName("addressBlock")]
        public AddressBlock? AddressBlock { get { return this.AddressBlockOption.Value; } set { this.AddressBlockOption = new(value); } }

        /// <summary>
        /// Used to track the state of Phone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [JsonPropertyName("phone")]
        public string? Phone { get { return this.PhoneOption.Value; } set { this.PhoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlternatePhone
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AlternatePhoneOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlternatePhone
        /// </summary>
        [JsonPropertyName("alternatePhone")]
        public string? AlternatePhone { get { return this.AlternatePhoneOption.Value; } set { this.AlternatePhoneOption = new(value); } }

        /// <summary>
        /// Used to track the state of Fax
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FaxOption { get; private set; }

        /// <summary>
        /// Gets or Sets Fax
        /// </summary>
        [JsonPropertyName("fax")]
        public string? Fax { get { return this.FaxOption.Value; } set { this.FaxOption = new(value); } }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Used to track the state of Contact
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactOption { get; private set; }

        /// <summary>
        /// Gets or Sets Contact
        /// </summary>
        [JsonPropertyName("contact")]
        public string? Contact { get { return this.ContactOption.Value; } set { this.ContactOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlternateContact
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AlternateContactOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlternateContact
        /// </summary>
        [JsonPropertyName("alternateContact")]
        public string? AlternateContact { get { return this.AlternateContactOption.Value; } set { this.AlternateContactOption = new(value); } }

        /// <summary>
        /// Used to track the state of AccountNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccountNumber
        /// </summary>
        [JsonPropertyName("accountNumber")]
        public string? AccountNumber { get { return this.AccountNumberOption.Value; } set { this.AccountNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of Notes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NotesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [JsonPropertyName("notes")]
        public string? Notes { get { return this.NotesOption.Value; } set { this.NotesOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<DataExtRequest>?> CustomFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [JsonPropertyName("customFields")]
        public List<DataExtRequest>? CustomFields { get { return this.CustomFieldsOption.Value; } set { this.CustomFieldsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateOtherNameRequest {\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  Salutation: ").Append(Salutation).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  MiddleName: ").Append(MiddleName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  AddressBlock: ").Append(AddressBlock).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  AlternatePhone: ").Append(AlternatePhone).Append("\n");
            sb.Append("  Fax: ").Append(Fax).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Contact: ").Append(Contact).Append("\n");
            sb.Append("  AlternateContact: ").Append(AlternateContact).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateOtherNameRequest" />
    /// </summary>
    public class UpdateOtherNameRequestJsonConverter : JsonConverter<UpdateOtherNameRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateOtherNameRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateOtherNameRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> revisionNumber = default;
            Option<string?> name = default;
            Option<string?> companyName = default;
            Option<string?> salutation = default;
            Option<string?> firstName = default;
            Option<string?> middleName = default;
            Option<string?> lastName = default;
            Option<Address?> address = default;
            Option<AddressBlock?> addressBlock = default;
            Option<string?> phone = default;
            Option<string?> alternatePhone = default;
            Option<string?> fax = default;
            Option<string?> email = default;
            Option<string?> contact = default;
            Option<string?> alternateContact = default;
            Option<string?> accountNumber = default;
            Option<string?> notes = default;
            Option<List<DataExtRequest>?> customFields = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revisionNumber":
                            revisionNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "companyName":
                            companyName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "salutation":
                            salutation = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "firstName":
                            firstName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "middleName":
                            middleName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastName":
                            lastName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "address":
                            address = new Option<Address?>(JsonSerializer.Deserialize<Address>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "addressBlock":
                            addressBlock = new Option<AddressBlock?>(JsonSerializer.Deserialize<AddressBlock>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "phone":
                            phone = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "alternatePhone":
                            alternatePhone = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "fax":
                            fax = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "contact":
                            contact = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "alternateContact":
                            alternateContact = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "accountNumber":
                            accountNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "notes":
                            notes = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "customFields":
                            customFields = new Option<List<DataExtRequest>?>(JsonSerializer.Deserialize<List<DataExtRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revisionNumber.IsSet)
                throw new ArgumentException("Property is required for class UpdateOtherNameRequest.", nameof(revisionNumber));

            if (revisionNumber.IsSet && revisionNumber.Value == null)
                throw new ArgumentNullException(nameof(revisionNumber), "Property is not nullable for class UpdateOtherNameRequest.");

            if (customFields.IsSet && customFields.Value == null)
                throw new ArgumentNullException(nameof(customFields), "Property is not nullable for class UpdateOtherNameRequest.");

            return new UpdateOtherNameRequest(revisionNumber.Value!, name, companyName, salutation, firstName, middleName, lastName, address, addressBlock, phone, alternatePhone, fax, email, contact, alternateContact, accountNumber, notes, customFields);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateOtherNameRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateOtherNameRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateOtherNameRequest updateOtherNameRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateOtherNameRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateOtherNameRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateOtherNameRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateOtherNameRequest updateOtherNameRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateOtherNameRequest.RevisionNumber == null)
                throw new ArgumentNullException(nameof(updateOtherNameRequest.RevisionNumber), "Property is required for class UpdateOtherNameRequest.");

            if (updateOtherNameRequest.CustomFieldsOption.IsSet && updateOtherNameRequest.CustomFields == null)
                throw new ArgumentNullException(nameof(updateOtherNameRequest.CustomFields), "Property is required for class UpdateOtherNameRequest.");

            writer.WriteString("revisionNumber", updateOtherNameRequest.RevisionNumber);

            if (updateOtherNameRequest.NameOption.IsSet)
                if (updateOtherNameRequest.NameOption.Value != null)
                    writer.WriteString("name", updateOtherNameRequest.Name);
                else
                    writer.WriteNull("name");

            if (updateOtherNameRequest.CompanyNameOption.IsSet)
                if (updateOtherNameRequest.CompanyNameOption.Value != null)
                    writer.WriteString("companyName", updateOtherNameRequest.CompanyName);
                else
                    writer.WriteNull("companyName");

            if (updateOtherNameRequest.SalutationOption.IsSet)
                if (updateOtherNameRequest.SalutationOption.Value != null)
                    writer.WriteString("salutation", updateOtherNameRequest.Salutation);
                else
                    writer.WriteNull("salutation");

            if (updateOtherNameRequest.FirstNameOption.IsSet)
                if (updateOtherNameRequest.FirstNameOption.Value != null)
                    writer.WriteString("firstName", updateOtherNameRequest.FirstName);
                else
                    writer.WriteNull("firstName");

            if (updateOtherNameRequest.MiddleNameOption.IsSet)
                if (updateOtherNameRequest.MiddleNameOption.Value != null)
                    writer.WriteString("middleName", updateOtherNameRequest.MiddleName);
                else
                    writer.WriteNull("middleName");

            if (updateOtherNameRequest.LastNameOption.IsSet)
                if (updateOtherNameRequest.LastNameOption.Value != null)
                    writer.WriteString("lastName", updateOtherNameRequest.LastName);
                else
                    writer.WriteNull("lastName");

            if (updateOtherNameRequest.AddressOption.IsSet)
                if (updateOtherNameRequest.AddressOption.Value != null)
                {
                    writer.WritePropertyName("address");
                    JsonSerializer.Serialize(writer, updateOtherNameRequest.Address, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("address");
            if (updateOtherNameRequest.AddressBlockOption.IsSet)
                if (updateOtherNameRequest.AddressBlockOption.Value != null)
                {
                    writer.WritePropertyName("addressBlock");
                    JsonSerializer.Serialize(writer, updateOtherNameRequest.AddressBlock, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("addressBlock");
            if (updateOtherNameRequest.PhoneOption.IsSet)
                if (updateOtherNameRequest.PhoneOption.Value != null)
                    writer.WriteString("phone", updateOtherNameRequest.Phone);
                else
                    writer.WriteNull("phone");

            if (updateOtherNameRequest.AlternatePhoneOption.IsSet)
                if (updateOtherNameRequest.AlternatePhoneOption.Value != null)
                    writer.WriteString("alternatePhone", updateOtherNameRequest.AlternatePhone);
                else
                    writer.WriteNull("alternatePhone");

            if (updateOtherNameRequest.FaxOption.IsSet)
                if (updateOtherNameRequest.FaxOption.Value != null)
                    writer.WriteString("fax", updateOtherNameRequest.Fax);
                else
                    writer.WriteNull("fax");

            if (updateOtherNameRequest.EmailOption.IsSet)
                if (updateOtherNameRequest.EmailOption.Value != null)
                    writer.WriteString("email", updateOtherNameRequest.Email);
                else
                    writer.WriteNull("email");

            if (updateOtherNameRequest.ContactOption.IsSet)
                if (updateOtherNameRequest.ContactOption.Value != null)
                    writer.WriteString("contact", updateOtherNameRequest.Contact);
                else
                    writer.WriteNull("contact");

            if (updateOtherNameRequest.AlternateContactOption.IsSet)
                if (updateOtherNameRequest.AlternateContactOption.Value != null)
                    writer.WriteString("alternateContact", updateOtherNameRequest.AlternateContact);
                else
                    writer.WriteNull("alternateContact");

            if (updateOtherNameRequest.AccountNumberOption.IsSet)
                if (updateOtherNameRequest.AccountNumberOption.Value != null)
                    writer.WriteString("accountNumber", updateOtherNameRequest.AccountNumber);
                else
                    writer.WriteNull("accountNumber");

            if (updateOtherNameRequest.NotesOption.IsSet)
                if (updateOtherNameRequest.NotesOption.Value != null)
                    writer.WriteString("notes", updateOtherNameRequest.Notes);
                else
                    writer.WriteNull("notes");

            if (updateOtherNameRequest.CustomFieldsOption.IsSet)
            {
                writer.WritePropertyName("customFields");
                JsonSerializer.Serialize(writer, updateOtherNameRequest.CustomFields, jsonSerializerOptions);
            }
        }
    }
}
